//JavaScript Document
/*********************************
 *rookie QQ:1123486116
 *rookie making
 *rookie Copyright
 **********************************/
document.writeln("                <!--lesson-->");
document.writeln("                <div id=\"lesson\">");
document.writeln("                        <div class=\"hd\">");
document.writeln("                                <ul>");
document.writeln("                                        <li class=\"on\">自助挂号</li>");
document.writeln("                                        <li>公益导航</li>");
document.writeln("                                        <li>媒体关注</li>");
document.writeln("                                        <li>先进设备</li>");
document.writeln("                                        <li>医院环境</li>");
document.writeln("                                </ul>");
document.writeln("                        </div>");
document.writeln("                        <div class=\"bd\">");
document.writeln("                                <ul>");
document.writeln("                                        <!--自助挂号-->");
document.writeln("                                        <li class=\"on\">");
document.writeln("                                                <link rel=\"stylesheet\" href=\"guahao/laydate/need/laydate.css\"/>");
document.writeln("                                                <div id=\"guahao\">");
document.writeln("                                                        <dl>");
document.writeln("                                                                <dd>");
document.writeln("                                                                        <form name=\"fm\" method=\"post\" action=\"http://swt.gssmart.com/guahao/sockt.php\">");
document.writeln("                                                                                <div class=\"clear-fix\">");
document.writeln("                                                                                        <div class=\"fl guahao-main\">");
document.writeln("                                                                                                <img src=\"images/guahao-main.jpg\" />");
document.writeln("                                                                                                <div class=\"clear-fix\">");
document.writeln("                                                                                                        <div class=\"fl\">");
document.writeln("                                                                                                                <h2><label><span>姓名：</span><input type=\"text\" name=\"名称\" id=\"username\" placeholder=\"请输入您的姓名\"/></label></h2>");
document.writeln("                                                                                                                <h2><label><span>就诊时间：</span><input type=\"text\" name=\"time\" id=\"time\" placeholder=\"请选择您的就诊时间\"/></label></h2>");
document.writeln("                                                                                                        </div>");
document.writeln("                                                                                                        <div class=\"fl sex-age-tel\">");
document.writeln("                                                                                                                <div class=\"clear-fix\">");
document.writeln("                                                                                                                        <h2 class=\"fl sex\"><span>性别：</span><label><input type=\"radio\" name=\"sex\"/>男</label><label><input type=\"radio\" name=\"sex\"/>女</label></h2>");
document.writeln("                                                                                                                        <h2 class=\"fl age\"><label><span>年龄：</span><input type=\"text\" name=\"age\" id=\"age\" placeholder=\"年龄\"/></label></h2>");
document.writeln("                                                                                                                </div>");
document.writeln("                                                                                                                <h2 class=\"tel\"><label><span>联系电话：</span><input type=\"text\" name=\"电话\" id=\"phone\" placeholder=\"请输入您的电话号码\"/></label></h2>");
document.writeln("                                                                                                        </div>");
document.writeln("                                                                                                </div>");
document.writeln("                                                                                                <h2 class=\"description\"><label><span>病情描述：</span><textarea cols=\"30\" rows=\"10\" name=\"病情描述\" id=\"content\" placeholder=\"请输入不适症状和治疗经过、既往疾病、想获得什么样的帮助等，方便医生匹配精准对症的专家，如有意向医院或医生，请您补充（请输入10-200个字）\"></textarea></label></h2>");
document.writeln("                                                                                        </div>");
document.writeln("                                                                                        <div class=\"fr\">");
document.writeln("                                                                                                <img src=\"images/guahao-side.png\" />");
document.writeln("                                                                                                <p>积极响应国家\"网上预约挂号\"政策</p>");
document.writeln("                                                                                                <input type=\"submit\" name=\"send\" value=\"提交预约\"/>");
document.writeln("                                                                                                <em>预约成功患者，系统会将专家号和医院地址下发到您的手机，请注意查收</em>");
document.writeln("                                                                                        </div>");
document.writeln("                                                                                </div>");
document.writeln("                                                                        </form>");
document.writeln("                                                                </dd>");
document.writeln("                                                        </dl>");
document.writeln("                                                </div>");
document.writeln("                                                <script type=\"text/javascript\" src=\"guahao/laydate/laydate.js\"></script>");
document.writeln("                                                <script type=\"text/javascript\" src=\"guahao/js/js.js\"></script>");
document.writeln("                                        </li>");
document.writeln("                                        <!--公益导航-->");
document.writeln("                                        <li class=\"lesson-two-li\">");
document.writeln("                                                <a class=\"lesson-public-a1\" href=\"/zt/shgy/cgz1/\" target=\"_blank\"></a>");
document.writeln("                                                <a class=\"lesson-public-a2\" href=\"/zt/shgy/xmny/\" target=\"_blank\"></a>");
document.writeln("                                                <a class=\"lesson-public-a3\" href=\"/zt/shgy/yuyao/\" target=\"_blank\"></a>");
document.writeln("                                                <a class=\"lesson-public-a4\" href=\"/zt/shgy/shequ/\" target=\"_blank\"></a>");
document.writeln("                                                <a class=\"lesson-public-a5\" href=\"/zt/shgy/yxbr/\" target=\"_blank\"></a>");
document.writeln("                                        </li>");
document.writeln("                                        <!--媒体关注-->");
document.writeln("                                        <li class=\"lesson-thr-li\">");
document.writeln("                                                <a href=\"/meitibaodao/201012211318.shtml\" target=\"_blank\"><img _src=\"images/1.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/yiyuanjians/201010161293.html\" target=\"_blank\"><img _src=\"images/2.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/meitibaodao/201012211326.shtml\" target=\"_blank\"><img _src=\"images/3.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/meitibaodao/201012211332.shtml\" target=\"_blank\"><img _src=\"images/4.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/meitibaodao/201012211319.shtml\" target=\"_blank\"><img _src=\"images/5.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/meitibaodao/201012211325.shtml\" target=\"_blank\"><img _src=\"images/6.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/meitibaodao/201012211324.shtml\" target=\"_blank\"><img _src=\"images/7.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/yiyuanjians/201104261389.html\" target=\"_blank\"><img _src=\"images/8.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/meitibaodao/201104131382.shtml\" target=\"_blank\"><img _src=\"images/9.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/yiyuanjians/201104131380.html\" target=\"_blank\"><img _src=\"images/10.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/yiyuanjians/201010161293.shtml\" target=\"_blank\"><img _src=\"images/11.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/meitibaodao/201012211328.shtml\" target=\"_blank\"><img _src=\"images/12.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/meitibaodao/201010281298.shtml\" target=\"_blank\"><img _src=\"images/13.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/meitibaodao/201012281345.shtml\" target=\"_blank\"><img _src=\"images/14.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/meitibaodao/201012221337.shtml\" target=\"_blank\"><img _src=\"images/15.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/meitibaodao/201102251369.shtml\" target=\"_blank\"><img _src=\"images/16.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/meitibaodao/201012211330.shtml\" target=\"_blank\"><img _src=\"images/17.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/meitibaodao/201101071355.shtml\" target=\"_blank\"><img _src=\"images/18.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/meitibaodao/201308082353.shtml\" target=\"_blank\"><img _src=\"images/19.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/meitibaodao/201012211327.shtml\" target=\"_blank\"><img _src=\"images/20.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/meitibaodao/201102251370.shtml\" target=\"_blank\"><img _src=\"images/21.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/meitibaodao/201012281343.shtml\" target=\"_blank\"><img _src=\"images/22.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/meitibaodao/201102251368.shtml\" target=\"_blank\"><img _src=\"images/23.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/meitibaodao/201012311349.shtml\" target=\"_blank\"><img _src=\"images/24.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/meitibaodao/201101071353.shtml\" target=\"_blank\"><img _src=\"images/25.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/meitibaodao/201012211333.shtml\" target=\"_blank\"><img _src=\"images/26.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/meitibaodao/201012311346.shtml\" target=\"_blank\"><img _src=\"images/27.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/meitibaodao/201012211335.shtml\" target=\"_blank\"><img _src=\"images/28.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/meitibaodao/201012281344.shtml\" target=\"_blank\"><img _src=\"images/29.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/meitibaodao/201101051351.shtml\" target=\"_blank\"><img _src=\"images/30.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/yiyuanjians/201011091112.shtml\" target=\"_blank\"><img _src=\"images/31.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/meitibaodao/201101071354.shtml\" target=\"_blank\"><img _src=\"images/32.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/meitibaodao/201012251340.shtml\" target=\"_blank\"><img _src=\"images/33.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/meitibaodao/201012211321.shtml\" target=\"_blank\"><img _src=\"images/34.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/meitibaodao/201012221338.shtml\" target=\"_blank\"><img _src=\"images/35.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                        </li>");
document.writeln("                                        <!--先进设备-->");
document.writeln("                                        <li class=\"lesson-fou-li\">");
document.writeln("                                                <div>");
document.writeln("                                                        <dl>");
document.writeln("                                                                <dt><img _src=\"images/lesson-fou-li1.jpg\" alt=\"\"/></dt>");
document.writeln("                                                                <dd>SRT-100立体定位疤痕无创修复系统</dd>");
document.writeln("                                                        </dl>");
document.writeln("                                                        <dl>");
document.writeln("                                                                <dt><img _src=\"images/lesson-fou-li2.jpg\" alt=\"\"/></dt>");
document.writeln("                                                                <dd>MD-300S皮肤超声影像诊断系统</dd>");
document.writeln("                                                        </dl>");
document.writeln("                                                        <dl>");
document.writeln("                                                                <dt><img _src=\"images/lesson-fou-li3.jpg\" alt=\"\"/></dt>");
document.writeln("                                                                <dd>王者之冠</dd>");
document.writeln("                                                        </dl>");
document.writeln("                                                        <dl>");
document.writeln("                                                                <dt><img _src=\"images/lesson-fou-li4.jpg\" alt=\"\"/></dt>");
document.writeln("                                                                <dd>JANUS-Ⅱ多媒体人脸检测系统</dd>");
document.writeln("                                                        </dl>");
document.writeln("                                                        <dl>");
document.writeln("                                                                <dt><img _src=\"images/lesson-fou-li5.jpg\" alt=\"\"/></dt>");
document.writeln("                                                                <dd>飞顿雷霆大Q</dd>");
document.writeln("                                                        </dl>");
document.writeln("                                                        <dl>");
document.writeln("                                                                <dt><img _src=\"images/lesson-fou-li6.jpg\" alt=\"\"/></dt>");
document.writeln("                                                                <dd>点阵激光</dd>");
document.writeln("                                                        </dl>");
document.writeln("                                                        <dl>");
document.writeln("                                                                <dt><img _src=\"images/lesson-fou-li7.jpg\" alt=\"\"/></dt>");
document.writeln("                                                                <dd>微晶磨皮治疗仪</dd>");
document.writeln("                                                        </dl>");
document.writeln("                                                </div>");
document.writeln("                                        </li>");
document.writeln("                                        <!--医院环境-->");
document.writeln("                                        <li class=\"lesson-fiv-li\">");
document.writeln("                                                <dl>");
document.writeln("                                                        <dd><img _src=\"images/lesson-fiv-li1.jpg\" alt=\"\"/></dd>");
document.writeln("                                                        <dd><img _src=\"images/lesson-fiv-li2.jpg\" alt=\"\"/></dd>");
document.writeln("                                                        <dd><img _src=\"images/lesson-fiv-li3.jpg\" alt=\"\"/></dd>");
document.writeln("                                                        <dd><img _src=\"images/lesson-fiv-li4.jpg\" alt=\"\"/></dd>");
document.writeln("                                                </dl>");
document.writeln("                                        </li>");
document.writeln("                                </ul>");
document.writeln("                        </div>");
document.writeln("                </div>");
document.writeln("                <!--discuss-->");
document.writeln("                <div id=\"discuss\">");
document.writeln("                        <h2>百姓口碑<small>The reputation of the people</small></h2>");
document.writeln("                        <script type=\"text/javascript\">var uyan_config = {\'du\':\'skinjc.com\',\'su\':\'bh\'};</script>");
document.writeln("                        <div id=\"uyan_frame\"></div>");
document.writeln("                        <script type=\"text/javascript\" src=\"http://v2.uyan.cc/code/uyan.js?uid=2061447\"></script>");
document.writeln("                </div>");
document.writeln("                <!--footer-->");
document.writeln("                <div id=\"footer\">");
document.writeln("                        <div>");
document.writeln("                                <dl>");
document.writeln("                                        <dt><img src=\"images/footer-logo.jpg\" alt=\"\"/></dt>");
document.writeln("                                        <dd>");
document.writeln("                                                <h2>联系我们<small>/Contact us</small></h2>");
document.writeln("                                                <img src=\"images/footer-phone.jpg\" alt=\"\"/>");
document.writeln("                                                <p>地址：上海市杨浦区黄兴路286号 沪医广【2014】第07-14-G123 沪ICP备13034821号</p>");
document.writeln("                                                <p>Copyright (C) 2009 Jiangcheng Dermatology Hospital shanghai.</p>");
document.writeln("                                                <p>温馨提示：任何建议都不能替代执业医师当面诊断，所有门诊时间仅供参考，最终以医院当日公布为准。</p>");
document.writeln("                                                <p>网友 、医生言论仅代表其个人观点，不代表本站同意其说法。</p>");
document.writeln("                                        </dd>");
document.writeln("                                </dl>");
document.writeln("                        </div>");
document.writeln("                </div>");

$(window).load(function(){
        /*lesson*/
        var oParent=$("#lesson");
        var aBtn=oParent.find('.hd').find('li');
        var aCut=oParent.find('.bd').find('li');
        aBtn.click(function(){
                var index=$(this).index();
                $(this).addClass('on').siblings().removeClass('on');
                aCut.eq(index).addClass('on').siblings().removeClass('on');
                var allImg = aCut.eq(index).find('img');
                allImg.each(function (index) {
                        var img = allImg.eq(index);
                        var src = img.attr('src');
                        var _src = img.attr('_src');
                        if (!src) {
                                img.attr('src', _src);
                        }
                })
        });
});