document.writeln("<!--周华飞制作 QQ:1123486116-->");
document.writeln("<style>");
document.writeln("/*清零*/");
document.writeln("body,div,ol,ul,li,dl,dd,dt,h1,h2,h3,h4,h5,h6,input,p,form,img{ padding:0; margin:0; font-weight:normal;}");
document.writeln("body{ font-size:14px; font-family:\"微软雅黑\",Verdana,Arial,\"宋体\",\"微软雅黑\";}");
document.writeln("img{ border:none; outline:none;}");
document.writeln("input,select,textarea{ outline:none; border:none; background:#FFF;resize:none;}");
document.writeln("ul,ol{ list-style-type:none;}");
document.writeln("a{ outline:none; text-decoration:none; color:#000; transition:all 0.3s; -webkit-transition:all 0.3s; -moz-transition:all 0.3s; -o-transition:all 0.3s;}");
document.writeln("p{ line-height:25px;}");
document.writeln("em,i,strong,b,small{ font-style:normal; font-weight:normal;}");
document.writeln("em{ transition:all 1s; -webkit-transition:all 1s; -moz-transition:all 1s; -o-transition:all 1s;}");
document.writeln("/*清楚浮动*/");
document.writeln(".clearFix{ clear:both;*zoom:1;}");
document.writeln(".clearFix:after{ clear:both; display:block; visibility:hidden; height:0; line-height:0; content:\"\"; font-size:0;}");
document.writeln("/*公用的样式*/");
document.writeln(".fl{ float:left;}");
document.writeln(".fr{ float:right;}");
document.writeln(".commonWidth{ width:100%; margin:0 auto; overflow:hidden;}");
document.writeln(".commonWidth_980{ width:980px; margin:0 auto; overflow:hidden;}");
document.writeln("/*the_hospital*/");
document.writeln(".the_hospital{ padding:30px 0;}");
document.writeln(".the_hospital ul{ width:800px; height:385px;}");
document.writeln(".the_hospital ul li{ width:800px; height:100%; display:none;}");
document.writeln(".the_hospital ul .li_active{ display:block;}");
document.writeln(".the_hospital ul .the_word{ height:100%; width:335px; padding:0 20px; position:relative; color:#444444; background:#f4f4f4;}");
document.writeln(".the_hospital ul img{ width:425px; height:385px; background:#ccc;}");
document.writeln(".the_hospital ul h2{ margin:35px 0; font-size:26px;}");
document.writeln(".the_hospital ul p{ text-indent:30px;}");
document.writeln(".the_hospital ul .hospital_dbbtn{ position:absolute; right:20px; bottom:20px;}");
document.writeln(".the_hospital ul .hospital_dbbtn a{ display:inline-block; width:38px; height:38px; margin-right:10px;}");
document.writeln(".the_hospital ul .hospital_dbbtn .hospital_left_a{ background:url(the_hospital_images/the_hospital.png) -36px -455px no-repeat;}");
document.writeln(".the_hospital ul .hospital_dbbtn .hospital_left_a:hover{ background:url(the_hospital_images/the_hospital.png) -36px -508px no-repeat;}");
document.writeln(".the_hospital ul .hospital_dbbtn .hospital_right_a{ background:url(the_hospital_images/the_hospital.png) -36px -562px no-repeat; margin-right:0px;}");
document.writeln(".the_hospital ul .hospital_dbbtn .hospital_right_a:hover{ background:url(the_hospital_images/the_hospital.png) -36px -617px no-repeat;}");
document.writeln(".the_hospital ol{ width:155px;}");
document.writeln(".the_hospital ol li{ height:60px; line-height:60px; background:#ebebeb; font-size:18px; color:#6a6a6a; position:relative; margin-bottom:5px; cursor:pointer;}");
document.writeln(".the_hospital ol .li_active{ background:#006db8; color:#fff;}");
document.writeln(".the_hospital ol em{ display:inline-block; vertical-align:middle; width:35px; height:35px; margin:0 10px; transition:0.3s;}");
document.writeln(".the_hospital ol div{ width:0px; height:0px; border:10px solid; border-color:#fff #006db8 #fff #fff; position:absolute; left:-20px; top:20px; display:none;}");
document.writeln(".the_hospital ol .div_active{ display:block;}");
document.writeln(".the_hospital .the_hospital_icon1{ background:url(the_hospital_images/the_hospital.png) -36px 0px no-repeat;}");
document.writeln(".the_hospital .the_hospital_icon11{ background:url(the_hospital_images/the_hospital.png) -36px -36px no-repeat;}");
document.writeln(".the_hospital .the_hospital_icon2{ background:url(the_hospital_images/the_hospital.png) -36px -72px no-repeat;}");
document.writeln(".the_hospital .the_hospital_icon21{ background:url(the_hospital_images/the_hospital.png) -36px -108px no-repeat;}");
document.writeln(".the_hospital .the_hospital_icon3{ background:url(the_hospital_images/the_hospital.png) -36px -145px no-repeat;}");
document.writeln(".the_hospital .the_hospital_icon31{ background:url(the_hospital_images/the_hospital.png) -36px -181px no-repeat;}");
document.writeln(".the_hospital .the_hospital_icon4{ background:url(the_hospital_images/the_hospital.png) -36px -217px no-repeat;}");
document.writeln(".the_hospital .the_hospital_icon41{ background:url(the_hospital_images/the_hospital.png) -36px -254px no-repeat;}");
document.writeln(".the_hospital .the_hospital_icon5{ background:url(the_hospital_images/the_hospital.png) -36px -290px no-repeat;}");
document.writeln(".the_hospital .the_hospital_icon51{ background:url(the_hospital_images/the_hospital.png) -36px -326px no-repeat;}");
document.writeln(".the_hospital .the_hospital_icon6{ background:url(the_hospital_images/the_hospital.png) -36px -363px no-repeat;}");
document.writeln(".the_hospital .the_hospital_icon61{ background:url(the_hospital_images/the_hospital.png) -36px -399px no-repeat;}");
document.writeln("</style>");
document.writeln("<!--the_hospital-->");
document.writeln("<div class=\"the_hospital commonWidth_980\" id=\"the_hospital\">");
document.writeln("	<ul class=\"fl\">");
document.writeln("        	<li class=\"li_active\">");
document.writeln("                	<div class=\"fl the_word\">");
document.writeln("                        	<h2>提前预约 无需等待</h2>");
document.writeln("                                <p>上海江城皮肤病医院积极贯彻卫生部《在网上施行预约诊疗服务工作的意见》，率先推出网上预约挂号服务，切实解决百姓看病难问题。全国男性患者可通过网络，与上海江城皮肤病医院在线专家一对一对话咨询，在线免费预约上海江城皮肤病医院专家号，并凭预约号到院直接就诊，无需排队。</p>");
document.writeln("				<div class=\"hospital_dbbtn\"><a class=\"hospital_left_a\"  href=\"javascript:void(0)\" onclick=\"openZoosUrl();return false;\"></a><a class=\"hospital_right_a\"  href=\"javascript:void(0)\" onclick=\"openZoosUrl();return false;\"></a></div>");
document.writeln("                        </div>");
document.writeln("                        <img class=\"fr\" src=\"the_hospital_images/hospital1.jpg\" alt=\"提前预约 无需等待\" />");
document.writeln("                </li>");
document.writeln("        	<li>");
document.writeln("                	<div class=\"fl the_word\">");
document.writeln("                        	<h2>医院概况</h2>");
document.writeln("                                <p>上海江城皮肤病医院是按国家三级医院设置的大型皮肤病专科医院。医院面积10000余平方米，开设病床104张。设有皮肤内科、皮肤外科、中医科、中西医结合科、银屑病门诊、白癜风门诊、性病科、激光美容科、医学美容科、康复理疗科、预防保健科等专业化特色诊疗科室及皮肤病理实验室、性病实验室等多个精微化科研实验室。是集临床、科研、教学、预防为一体的国际化、现代化皮肤病专业医院</p>");
document.writeln("				<div class=\"hospital_dbbtn\"><a class=\"hospital_left_a\"  href=\"javascript:void(0)\" onclick=\"openZoosUrl();return false;\"></a><a class=\"hospital_right_a\"  href=\"javascript:void(0)\" onclick=\"openZoosUrl();return false;\"></a></div>");
document.writeln("			</div>");
document.writeln("                        <img class=\"fr\" src=\"the_hospital_images/hospital2.jpg\" alt=\"医院概况\" />");
document.writeln("                </li>");
document.writeln("        	<li>");
document.writeln("                	<div class=\"fl the_word\">");
document.writeln("                        	<h2>专家团队</h2>");
document.writeln("                                <p>上海江城皮肤病医院一直拥有着强大的医师团队，这是一支由国务院特殊津贴专家、教授及硕士研究生及高级职称医师组成的疑难病症攻关型队伍。全院500余名职工之中，医疗专业技术人员占80％，其中主任医师、教授、博士生导师和享受国务院政府特殊津贴的专家等副高职以上专家50多人，许多专家教授在国内外享有较高知名度。</p>");
document.writeln("                                 <div class=\"hospital_dbbtn\"><a class=\"hospital_left_a\"  href=\"javascript:void(0)\" onclick=\"openZoosUrl();return false;\"></a><a class=\"hospital_right_a\"  href=\"javascript:void(0)\" onclick=\"openZoosUrl();return false;\"></a></div>");
document.writeln("                        </div>");
document.writeln("                        <img class=\"fr\" src=\"the_hospital_images/hospital3.jpg\" alt=\"专家团队\" />");
document.writeln("                </li>");
document.writeln("        	<li>");
document.writeln("                	<div class=\"fl the_word\">");
document.writeln("                        	<h2> 服务理念</h2>");
document.writeln("                                <p>上海江城皮肤病医院倡导优质的服务理念，疗效与医患关系作为首要工作。始终把爱心、耐心、细心和责任心奉献给病人，以其全新的创意，独特的风格，为前来就诊的患者提供\"享受就诊\"服务。医院良好的医德医风得到了就诊病人的广泛赞誉，病人满意率始终保持在98％以上</p>");
document.writeln("                                <div class=\"hospital_dbbtn\"><a class=\"hospital_left_a\"  href=\"javascript:void(0)\" onclick=\"openZoosUrl();return false;\"></a><a class=\"hospital_right_a\"  href=\"javascript:void(0)\" onclick=\"openZoosUrl();return false;\"></a></div>");
document.writeln("                        </div>");
document.writeln("                        <img class=\"fr\" src=\"the_hospital_images/hospital4.jpg\" alt=\"服务理念\" />");
document.writeln("                </li>");
document.writeln("        	<li>");
document.writeln("                	<div class=\"fl the_word\">");
document.writeln("                        	<h2>医疗设备</h2>");
document.writeln("                                <p>上海江城皮肤病医院积极贯彻卫生部《在网上施行预约诊疗服务工作的意见》，率先推出网上预约挂号服务，切实解决百姓看病难问题。全国男性患者可通过网络，与上海江城皮肤病医院在线专家一对一对话咨询，在线免费预约上海江城皮肤病医院专家号，并凭预约号到院直接就诊，无需排队。</p>");
document.writeln("                                <div class=\"hospital_dbbtn\"><a class=\"hospital_left_a\"  href=\"javascript:void(0)\" onclick=\"openZoosUrl();return false;\"></a><a class=\"hospital_right_a\"  href=\"javascript:void(0)\" onclick=\"openZoosUrl();return false;\"></a></div>");
document.writeln("                        </div>");
document.writeln("                        <img class=\"fr\" src=\"the_hospital_images/hospital5.jpg\" alt=\"医疗设备\" />");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                	<div class=\"fl the_word\">");
document.writeln("                        	<h2>收费规范</h2>");
document.writeln("                                <p>上海江城皮肤病医院各项收费认真贯彻国家物价管理部门和医保政策规定，严格执行上海市物价局收费标准，建立了完善的监察、督察制度，杜绝不合理收费，于医院直接设立价格公示牌，真正做到让患者明明白白看病、清清楚楚花钱。以鲜明严格的制度严把医疗质量和收费关，实质性地帮助百姓节省医疗开支，切实解决老百姓\"看病贵\"难题，给患者一个安定放心的就医环境。</p>");
document.writeln("                                <div class=\"hospital_dbbtn\"><a class=\"hospital_left_a\"  href=\"javascript:void(0)\" onclick=\"openZoosUrl();return false;\"></a><a class=\"hospital_right_a\"  href=\"javascript:void(0)\" onclick=\"openZoosUrl();return false;\"></a></div>");
document.writeln("                        </div>");
document.writeln("                        <img class=\"fr\" src=\"the_hospital_images/hospital6.jpg\" alt=\"收费规范\" />");
document.writeln("                </li>");
document.writeln("        </ul>");
document.writeln("        <ol class=\"fr\">");
document.writeln("        	<li class=\"li_active\"><em class=\"the_hospital_icon11\"></em>网络预约<div class=\"div_active\"></div></li>");
document.writeln("        	<li><em class=\"the_hospital_icon2\"></em>医院概括<div></div></li>");
document.writeln("        	<li><em class=\"the_hospital_icon3\"></em>专家团队<div></div></li>");
document.writeln("        	<li><em class=\"the_hospital_icon4\"></em>服务理念<div></div></li>");
document.writeln("        	<li><em class=\"the_hospital_icon5\"></em>医疗设备<div></div></li>");
document.writeln("        	<li style=\"margin-bottom:0;\"><em class=\"the_hospital_icon6\"></em>收费规范<div></div></li>");
document.writeln("        </ol>	");
document.writeln("</div>");
document.writeln("<script>");
document.writeln("/*the_hospital*/");
document.writeln("var oThe_hospital=document.getElementById(\'the_hospital\');");
document.writeln("var oThe_ol=oThe_hospital.getElementsByTagName(\'ol\')[0];");
document.writeln("var aThe_ol_li=oThe_ol.getElementsByTagName(\'li\');");
document.writeln("var aThe_ol_div=oThe_ol.getElementsByTagName(\'div\');");
document.writeln("var aThe_ol_em=oThe_ol.getElementsByTagName(\'em\');");
document.writeln("var oThe_ul=oThe_hospital.getElementsByTagName(\'ul\')[0];");
document.writeln("var aThe_ul_li=oThe_ul.getElementsByTagName(\'li\');");
document.writeln("for(var i=0; i<aThe_ol_li.length;i++)");
document.writeln("{");
document.writeln("	aThe_ol_li[i].index=i;");
document.writeln("	aThe_ol_li[i].onmouseover=function()");
document.writeln("	{");
document.writeln("		for(var i=0; i<aThe_ol_li.length;i++)");
document.writeln("		{");
document.writeln("			aThe_ol_li[i].className=\'\';");
document.writeln("			aThe_ol_div[i].className=\'\';");
document.writeln("			aThe_ul_li[i].className=\'\'	");
document.writeln("			aThe_ol_em[i].className=\'the_hospital_icon\'+(i+1)+\'\'");
document.writeln("		}");
document.writeln("		this.className=\'li_active\';");
document.writeln("		aThe_ol_div[this.index].className=\'div_active\';");
document.writeln("		aThe_ol_em[this.index].className=\'the_hospital_icon\'+(this.index+1+\'1\')+\'\';");
document.writeln("		aThe_ul_li[this.index].className=\'li_active\'");
document.writeln("	}	");
document.writeln("}");
document.writeln("</script>");
document.writeln("<!--周华飞制作 QQ:1123486116-->");