// JavaScript Document
document.writeln("<link rel=\"stylesheet\" href=\"css/base.css\" /><!--基础清零样式(调用需引入)-->");
document.writeln("<script src=\"js/base.js\"></script><!--基础菜鸟插件(调用需引入)-->");
document.writeln("");
document.writeln("<!--header-->");
document.writeln("<style>");
document.writeln("/*header*/");
document.writeln("#header{ height:17px; padding:5px 0; color:#a7a7a7; font-size:12px; background:#414141; line-height:1;}");
document.writeln("#header dl{ width:1200px; margin:0 auto;line-height:17px;}");
document.writeln("#header dt.icon1{ padding-left:20px; margin-right:33px; position:relative;}");
document.writeln("#header dt.icon1:before{ content:\"\"; display:block; width:2px; height:2px; background:#a7a7a7; position:absolute; left:7px; top:8px;}");
document.writeln("#header dt.icon2{ padding-left:22px; position:relative;}");
document.writeln("#header dt.icon2:before{ content:\"\"; display:block; width:17px; height:17px; background:url(images/header.png) left top no-repeat; animation:circle 6s linear infinite; -webkit-animation:circle 6s linear infinite; position:absolute; left:0; top:0;}");
document.writeln("#header a{ float:left; width:17px; height:17px; margin-right:3px; color:#a7a7a7; background:url(images/header.png) no-repeat;}");
document.writeln("#header a.one{ width:68px; background:none;}");
document.writeln("#header a.two{ background-position:left -36px;}");
document.writeln("#header a.thr{ background-position:left -108px;}");
document.writeln("#header a.fou{ background-position:left -180px; position:relative;}");
document.writeln("#header a.fiv{ background-position:left -252px;}");
document.writeln("#header a.six{ background-position:left -324px; margin-right:6px;}");
document.writeln("#header a.two:hover{ background-position:left -72px;}");
document.writeln("#header a.thr:hover{ background-position:left -144px;}");
document.writeln("#header a.fou:hover{ background-position:left -216px;}");
document.writeln("#header a.fiv:hover{ background-position:left -288px;}");
document.writeln("#header a.six:hover{ background-position:left -360px;}");
document.writeln("#header a.fou .erWeiCode{ width:130px; text-align:center; height:0; overflow:hidden; color:#fff; position:absolute; left:50%; margin-left:-65px; top:22px; z-index:5; transition:0.4s;}");
document.writeln("#header a.fou:hover .erWeiCode{ height:131px;}");
document.writeln("#header a.fou:hover .erWeiCode:before{ content:\"\"; display:block; width:100%; height:1px; background:rgba(10,160,180,0.9); animation:erWeiCode 4s linear infinite; -webkit-animation:erWeiCode 4s linear infinite; z-index:6; position:absolute; left:0; top:0;}");
document.writeln("</style>");
document.writeln("<!--header-->");
document.writeln("<div id=\"header\">");
document.writeln("	<dl class=\"clearFix\">");
document.writeln("        	<dt class=\"fl icon1\">国家三级专科医院</dt>");
document.writeln("        	<dt class=\"fl icon2\">门诊时间(无假日医院):8:00 - 17:00</dt>");
document.writeln("                <dd class=\"fr\">");
document.writeln("                	<a class=\"one\">关注我们：</a>");
document.writeln("                	<a href=\"http://weibo.com/shjiangcheng/profile?s=6cm7D0\" target=\"_blank\" class=\"two\"></a>");
document.writeln("                	<a href=\"http://e.t.qq.com/jcpfkl20\" target=\"_blank\" class=\"thr\"></a>");
document.writeln("                	<a href=\"#\" target=\"_blank\" class=\"fou\"><div class=\"erWeiCode\"><img src=\"images/er.jpg\" /></div></a>");
document.writeln("                	<a href=\"http://user.qzone.qq.com/1054199822/main\" target=\"_blank\" class=\"fiv\"></a>");
document.writeln("                	<a href=\"http://wapmr.skinjc.com/\" target=\"_blank\" class=\"six\"></a>");
document.writeln("                </dd>");
document.writeln("        </dl>");
document.writeln("</div>");
document.writeln("");
document.writeln("<!--logo-->");
document.writeln("<style>");
document.writeln("/*loge*/");
document.writeln("#logo{ height:83px; background:url(images/logo.jpg) left top no-repeat;}");
document.writeln("</style>");
document.writeln("<!--logo-->");
document.writeln("<div id=\"logo\" class=\"w1200\"></div>");
document.writeln("");
document.writeln("<!--nav-->");
document.writeln("<style>");
document.writeln("/*nav*/");
document.writeln("#nav{ height:40px; color:#fff; font-size:18px; background:#0aa0b4; line-height:1;}");
document.writeln("#nav #navMain{ width:1200px; margin:0 auto;}");
document.writeln("#nav dl{ width:241px; position:relative; z-index:4;}");
document.writeln("#nav dt{ text-indent:18px; line-height:40px; background:#00647f; position:relative;}");
document.writeln("#nav dt:after{ content:\"\"; display:block; width:22px; height:9px; background:url(images/nav.png) left -324px no-repeat; position:absolute; right:23px; top:17px;}");
document.writeln("#nav dl:hover dt:after{ background:url(images/nav.png) left -288px no-repeat;}");
document.writeln("#nav dd{ height:399px; width:100%; border-bottom:1px solid #e0e0e0; display:none; background:#f4f4f4; transition:0.4s; position:absolute; left:0; top:40px;}");
document.writeln("#nav dl:hover dd{ display:block;}");
document.writeln("#nav ul{ padding:24px 0 0 12px; height:109px; position:relative;}");
document.writeln("#nav ul.ul1,#nav ul.ul2{ height:108px; border-bottom:1px solid #e0e0e0;}");
document.writeln("#nav ul h2{ height:23px; line-height:21px; padding-left:29px; font-size:16px; font-weight:bold; color:#000; margin-bottom:14px; position:relative; transition:0.4s;}");
document.writeln("#nav ul h2:before{ content:\"\"; display:block; width:23px; height:23px; background:url(images/nav.png) no-repeat; position:absolute; left:0; top:0; transition:0.4s;}");
document.writeln("#nav ul h2.icon1:before{ background-position:left 0;}");
document.writeln("#nav ul h2.icon2:before{ background-position:left -72px;}");
document.writeln("#nav ul h2.icon3:before{ background-position:left -144px;}");
document.writeln("#nav ul h2:after{ content:\"\"; display:block; width:14px; height:17px; background:url(images/nav.png) left -252px; display:none; position:absolute; right:0; top:34px;}");
document.writeln("#nav ul a{ color:#656565; font-size:12px; margin:0 24px 12px 0; float:left;}");
document.writeln("#nav ul li{ width:921px; height:380px; padding:20px 0 0 38px; background:#f8f8f8; display:none; position:absolute; left:241px; top:0;}");
document.writeln("#nav ul.ul2 li{ top:-133px;}");
document.writeln("#nav ul.ul3 li{ top:-266px;}");
document.writeln("#nav ul.ul3 li div{ width:630px;}");
document.writeln("#nav ul li div{ width:300px; margin-right:30px;}");
document.writeln("#nav ul li span{ float:left; width:100%; border-bottom:1px dashed #999999; margin-bottom:22px; padding-bottom:5px;}");
document.writeln("#nav ul li h3{ font-size:14px; font-weight:bold; color:#000; margin-bottom:15px; line-height:1;}");
document.writeln("#nav ul li h3.fl{ margin-right:10px;}");
document.writeln("#nav ul li a{ margin:0 6px 12px 0;}");
document.writeln("#nav ul li a.reStyle{ margin:1px 6px 0 0;}");
document.writeln("#nav ul li strong{ width:232px; text-align:center; height:366px; line-height:366px; background:#000; color:#fff; font-size:20px; position:relative;}");
document.writeln("#nav ul li strong em.abtns{ position:absolute; right:0; top:0; z-index:3;}");
document.writeln("#nav ul li strong em.abtns i{ width:10px; height:10px; float:left; margin:5px; border-radius:50%; background:#dcdcdc; transition:0s;}");
document.writeln("#nav ul li strong em.abtns i.active{ background:#0aa0b4;}");
document.writeln("#nav ul li strong em.acuts{ width:100%; height:100%; position:relative;}");
document.writeln("#nav ul li strong em.acuts i{ width:100%; height:100%; opacity:0; filter:alpha(opacity:0); position:absolute; left:0; top:0; transition:0s;}");
document.writeln("#nav ul li strong em.acuts i.active{ opacity:1; filter:alpha(opacity:100); z-index:2;}");
document.writeln("#nav ul:hover{ background:#0cb1c7;}");
document.writeln("#nav ul:hover a{ color:#fff;}");
document.writeln("#nav ul:hover li a{ color:#656565;}");
document.writeln("#nav ul:hover li a:hover{ color:#017d8d;}");
document.writeln("#nav ul:hover a:hover{ text-decoration:underline;}");
document.writeln("#nav ul:hover h2{ color:#fff;}");
document.writeln("#nav ul:hover h2.icon1:before{ background-position:left -36px;}");
document.writeln("#nav ul:hover h2.icon2:before{ background-position:left -108px;}");
document.writeln("#nav ul:hover h2.icon3:before{ background-position:left -180px;}");
document.writeln("#nav ul:hover h2:after{ display:block;}");
document.writeln("#nav ul:hover li{ display:block;}");
document.writeln("#nav ol li{ float:left; width:137px; line-height:40px; text-align:center; position:relative;}");
document.writeln("#nav ol li a:after{ content:\"\"; display:block; width:2px; height:18px; background:url(images/nav.png) left -216px no-repeat; position:absolute; right:0; top:13px; animation:circle 2s linear infinite; -webkit-animation:circle 2s linear infinite; z-index:2;}");
document.writeln("#nav ol li.last a:after{ display:none;}");
document.writeln("#nav ol li:hover{ background:#00647f;}");
document.writeln("#nav ol a{ color:#fff; display:block; line-height:40px;}");
document.writeln("</style>");
document.writeln("<!--nav-->");
document.writeln("<div id=\"nav\">");
document.writeln("        <div id=\"navMain\" class=\"clearFix\">");
document.writeln("                <dl class=\"fl\">");
document.writeln("                        <dt>江城塑美项目导航</dt>");
document.writeln("                        <dd>");
document.writeln("                                <ul class=\"ul1\">");
document.writeln("                                	<h2 class=\"icon1\">整形美容中心</h2>");
document.writeln("                                        <a href=\"#\" target=\"_blank\">眼部</a>");
document.writeln("                                        <a href=\"#\" target=\"_blank\">鼻部</a>");
document.writeln("                                        <a href=\"#\" target=\"_blank\">体型</a>");
document.writeln("                                        <a href=\"#\" target=\"_blank\">面部</a>");
document.writeln("                                        <a href=\"#\" target=\"_blank\">胸部</a>");
document.writeln("                                        <a href=\"#\" target=\"_blank\">面廓</a>");
document.writeln("                                        <a href=\"#\" target=\"_blank\">唇部</a>");
document.writeln("                                        <a href=\"#\" target=\"_blank\">耳部</a>");
document.writeln("                                        <li class=\"clearFix\">                                                ");
document.writeln("                                                <div class=\"fl\">");
document.writeln("                                                	<span>");
document.writeln("                                                		<h3>眼部精雕:</h3>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">双眼皮</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">祛眼袋</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">开眼角</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">上睑下垂</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">韩式无痕提眉</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">提眉悬吊</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">眉部术后修复</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">眼部手术修复</a>");
document.writeln("                                                        </span>");
document.writeln("                                                	<span>");
document.writeln("                                                		<h3>身体塑形:</h3>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">360°水动力吸脂</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">腰腹部吸脂</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">腿部吸脂</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">背部吸脂</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">臀部吸脂</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">手臂吸脂</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">面部吸脂</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">颈部松弛提拉</a>");
document.writeln("                                                        </span>");
document.writeln("                                                	<span>");
document.writeln("                                                		<h3>胸部整形:</h3>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">巨乳缩小</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">乳房下垂</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">乳头乳晕</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">整形副乳切除术</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">丰胸</a>");
document.writeln("                                                        </span>");
document.writeln("                                                	<span>");
document.writeln("                                                		<h3>面廓整形:</h3>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">隆眉弓</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">隆下巴</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">去颊脂</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">垫颧骨</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">颧弓整形</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">下颌角整形</a>");
document.writeln("                                                        </span>");
document.writeln("                                                </div>");
document.writeln("                                                <div class=\"fl\">");
document.writeln("                                                	<span>");
document.writeln("                                                		<h3>鼻部塑形:</h3>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">自体软骨隆鼻</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">鼻小柱整形</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">假体隆鼻</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">驼峰鼻矫正</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">鼻翼缩小</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">隆鼻修复</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">鼻尖整形</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">歪鼻矫正</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">鹰钩鼻矫正</a>");
document.writeln("                                                        </span>");
document.writeln("                                                	<span>");
document.writeln("                                                		<h3 class=\"fl\">自体脂肪移植:</h3>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\" class=\"reStyle\">自体脂肪丰苹果肌</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\" class=\"reStyle\">自体脂肪丰唇</a>");
document.writeln("                                                                <div class=\"clearFix\"></div>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">自体脂肪丰下巴</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">自体脂肪丰面颊</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">自体脂肪丰太阳穴</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">自体脂肪丰额头</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">自体脂肪隆鼻</a>");
document.writeln("                                                        </span>");
document.writeln("                                                	<span>");
document.writeln("                                                		<h3>唇部整形:</h3>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">兔唇修复</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">厚唇改薄</a>");
document.writeln("                                                        </span>");
document.writeln("                                                	<span>");
document.writeln("                                                		<h3>耳部整形:</h3>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">耳再造</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">副耳切除</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">杯状耳</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">招风耳</a>");
document.writeln("                                                        </span>");
document.writeln("                                                </div>");
document.writeln("                                                <strong class=\"fl\">");
document.writeln("                                                	<em class=\"abtns clearFix\">");
document.writeln("                                                        	<i class=\"active\"></i>");
document.writeln("                                                        	<i></i>");
document.writeln("                                                        	<i></i>");
document.writeln("                                                        	<i></i>");
document.writeln("                                                        </em>");
document.writeln("                                                        <em class=\"acuts\">");
document.writeln("                                                        	<i class=\"active\">PSD上没有切换</i>");
document.writeln("                                                        	<i>我觉得应该有</i>");
document.writeln("                                                        	<i>于是我就</i>");
document.writeln("                                                        	<i>加上了</i>");
document.writeln("                                                        </em>");
document.writeln("                                                </strong>");
document.writeln("                                        </li>");
document.writeln("                                </ul>");
document.writeln("                                <ul class=\"ul2\">");
document.writeln("                                        <h2 class=\"icon2\">皮肤美容中心</h2>");
document.writeln("                                        <a href=\"#\" target=\"_blank\">除皱紧肤</a>");
document.writeln("                                        <a href=\"#\" target=\"_blank\">无痛脱毛</a>");
document.writeln("                                        <a href=\"#\" target=\"_blank\">祛斑祛痣</a>");
document.writeln("                                        <a href=\"#\" target=\"_blank\">净痘靓肤</a>");
document.writeln("                                        <a href=\"#\" target=\"_blank\">美白嫩肤</a>");
document.writeln("                                        <a href=\"#\" target=\"_blank\">疤痕修复</a>");
document.writeln("                                        <li class=\"clearFix\">                                                ");
document.writeln("                                                <div class=\"fl\">");
document.writeln("                                                	<span>");
document.writeln("                                                		<h3>除皱紧肤:</h3>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">深蓝射频紧肤</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">腰腹部塑形</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">眼周细纹</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">松弛下垂</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">产后恢复</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">面部皱纹</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">颈纹</a>");
document.writeln("                                                        </span>");
document.writeln("                                                	<span>");
document.writeln("                                                		<h3>无痛脱毛:</h3>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">腰背多毛</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">腿部脱毛</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">腋下脱毛</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">唇部脱毛</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">手臂脱毛</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">比基尼脱毛</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">络腮胡</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">发际线修整</a>");
document.writeln("                                                        </span>");
document.writeln("                                                	<span>");
document.writeln("                                                		<h3>祛斑祛痣:</h3>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">日晒斑</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">黄褐斑</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">雀斑</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">老年斑</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">咖啡斑</a>");
document.writeln("                                                                <a href=\"#\" target=\"_blank\">雀斑样痣</a>");
document.writeln("                                                                <a href=\"#\" target=\"_blank\">太田痣</a>");
document.writeln("                                                                <a href=\"#\" target=\"_blank\">褐青色痣</a>");
document.writeln("                                                                <a href=\"#\" target=\"_blank\">贝克痣</a>");
document.writeln("                                                                <a href=\"#\" target=\"_blank\">伊藤痣</a>");
document.writeln("                                                                <a href=\"#\" target=\"_blank\">鲜红斑痣</a>");
document.writeln("                                                                <a href=\"#\" target=\"_blank\">祛胎记</a>");
document.writeln("                                                        </span>");
document.writeln("                                                	<span>");
document.writeln("                                                		<h3>净痘靓肤:</h3>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">白头粉刺</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">黑头粉刺</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">祛痘印</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">祛青春痘</a>");
document.writeln("                                                        </span>");
document.writeln("                                                </div>");
document.writeln("                                                <div class=\"fl\">");
document.writeln("                                                	<span>");
document.writeln("                                                		<h3>美白嫩肤:</h3>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">毛孔粗大</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">祛红血丝</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">祛黑眼圈</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">肤色晦暗</a>");
document.writeln("                                                                <div class=\"clearFix\"></div>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">面部美白</a>");
document.writeln("                                                        </span>");
document.writeln("                                                	<span>");
document.writeln("                                                		<h3>艺术纹绣:</h3>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">洗眼线</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">洗纹身</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">洗纹眉</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">洗唇线</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">开运眉</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">纹眉</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">漂唇</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">韩式隐形眼线</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">乳晕漂红</a>");
document.writeln("                                                        </span>");
document.writeln("                                                	<span>");
document.writeln("                                                		<h3>疤痕修复:</h3>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">手术疤痕修复</a>");
document.writeln("                                                                <div class=\"clearFix\"></div>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">意外疤痕修复</a>");
document.writeln("                                                        </span>");
document.writeln("                                                </div>");
document.writeln("                                                <strong class=\"fl\">");
document.writeln("                                                	<em class=\"abtns clearFix\">");
document.writeln("                                                        	<i class=\"active\"></i>");
document.writeln("                                                        	<i></i>");
document.writeln("                                                        	<i></i>");
document.writeln("                                                        	<i></i>");
document.writeln("                                                        </em>");
document.writeln("                                                        <em class=\"acuts\">");
document.writeln("                                                        	<i class=\"active\">PSD上没有切换</i>");
document.writeln("                                                        	<i>我觉得应该有</i>");
document.writeln("                                                        	<i>于是我就</i>");
document.writeln("                                                        	<i>加上了</i>");
document.writeln("                                                        </em>");
document.writeln("                                                </strong>");
document.writeln("                                        </li>");
document.writeln("                                </ul>");
document.writeln("                                <ul  class=\"ul3\">");
document.writeln("                                        <h2 class=\"icon3\">抗衰老中心</h2>");
document.writeln("                                        <a href=\"#\" target=\"_blank\">注射瘦脸</a>");
document.writeln("                                        <a href=\"#\" target=\"_blank\">注射隆鼻</a>");
document.writeln("                                        <a href=\"#\" target=\"_blank\">注射除皱</a>");
document.writeln("                                        <a href=\"#\" target=\"_blank\">瘦小腿</a>");
document.writeln("                                        <a href=\"#\" target=\"_blank\">丰唇</a>");
document.writeln("                                        <a href=\"#\" target=\"_blank\">丰太阳穴</a>");
document.writeln("                                        <a href=\"#\" target=\"_blank\" class=\"noMr\">丰下巴</a>");
document.writeln("                                        <li class=\"clearFix\">                                                ");
document.writeln("                                                <div class=\"fl\">");
document.writeln("                                                	<span>");
document.writeln("                                                		<h3>注射除皱: </h3>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">嘴角纹          </a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">颈纹</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">眉川纹</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">鱼尾纹</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">抬头纹</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">法令纹</a>");
document.writeln("                                                        </span>");
document.writeln("                                                	<span>");
document.writeln("                                                		<h3>精细塑形:</h3>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">注射丰苹果肌</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">注射丰额头</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">注射丰面颊</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">BOTOX注射瘦小腿</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">注射丰下巴</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">注射瘦脸</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">注射丰耳垂</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">注射丰唇</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">注射隆鼻</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">注射丰太阳穴</a>");
document.writeln("                                                        </span>");
document.writeln("                                                	<span>");
document.writeln("                                                		<h3>凹陷填充:</h3>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">痘坑痘印填充</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">泪沟填</a>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">充鼻唇沟填充</a>");
document.writeln("                                                        </span>");
document.writeln("                                                	<span>");
document.writeln("                                                		<h3>注射祛腋臭:</h3>");
document.writeln("                                        			<a href=\"#\" target=\"_blank\">注射祛腋臭</a>");
document.writeln("                                                        </span>");
document.writeln("                                                </div>");
document.writeln("                                                <strong class=\"fl\">");
document.writeln("                                                	<em class=\"abtns clearFix\">");
document.writeln("                                                        	<i class=\"active\"></i>");
document.writeln("                                                        	<i></i>");
document.writeln("                                                        	<i></i>");
document.writeln("                                                        	<i></i>");
document.writeln("                                                        </em>");
document.writeln("                                                        <em class=\"acuts\">");
document.writeln("                                                        	<i class=\"active\">PSD上没有切换</i>");
document.writeln("                                                        	<i>我觉得应该有</i>");
document.writeln("                                                        	<i>于是我就</i>");
document.writeln("                                                        	<i>加上了</i>");
document.writeln("                                                        </em>");
document.writeln("                                                </strong>");
document.writeln("                                        </li>");
document.writeln("                                </ul>");
document.writeln("                        </dd>");
document.writeln("                </dl>");
document.writeln("                <ol class=\"fl\">");
document.writeln("                        <li><a href=\"/\" target=\"_blank\">江城首页</a></li>");
document.writeln("                        <li><a href=\"#\" target=\"_blank\">品牌中心</a></li>");
document.writeln("                        <li><a href=\"#\" target=\"_blank\">案例中心</a></li>");
document.writeln("                        <li><a href=\"#\" target=\"_blank\">专家团队</a></li>");
document.writeln("                        <li><a href=\"#\" target=\"_blank\">塑美设备</a></li>");
document.writeln("                        <li><a href=\"#\" target=\"_blank\">来院路线</a></li>");
document.writeln("                        <li class=\"last\"><a href=\"#\" target=\"_blank\">在线咨询</a></li>");
document.writeln("                </ol>");
document.writeln("        </div>");
document.writeln("</div>");
document.writeln("<script>	");
document.writeln("var r=new Rookie();");
document.writeln("r.version();");
document.writeln("r.addEvent(window,\'load\',function(){");
document.writeln("	/*nav*/");
document.writeln("	for(var i=1; i<=3;i++){");
document.writeln("		r.tabSwitch({aBtn:\"#nav ul.ul\"+i+\" em.abtns i\",aCut:\"#nav ul.ul\"+i+\" em.acuts i\"});");
document.writeln("	}");
document.writeln("})");
document.writeln("</script>");