//JavaScript Document
document.writeln("                        <!--guahao-->");
document.writeln("                        <section id=\"guahao\">");
document.writeln("                                <section class=\"guahao-logo\"><img src=\"images/guahao-logo.jpg\" alt=\"\"/></section>");
document.writeln("                                <h2>积极响应国家“网上预约挂号”政策</h2>");
document.writeln("                                <form method=\"post\" action=\"http://swt.gssmart.com/guahao/sockt.php\" name=\"comment\">");
document.writeln("                                        <div class=\"clear-fix\">");
document.writeln("                                                <label class=\"fl\" for=\"username\">姓名：</label>");
document.writeln("                                                <input id=\"username\" name=\"username\" class=\"fr\" placeholder=\"请输入你的姓名\" required=\"required\" type=\"text\">");
document.writeln("                                        </div>");
document.writeln("                                        <div class=\"clear-fix\">");
document.writeln("                                                <label class=\"fl\">性别：</label>");
document.writeln("                                                <article>");
document.writeln("                                                        <input name=\"sex\" id=\"man\" checked=\"checked\" type=\"radio\">");
document.writeln("                                                        <label for=\"man\">男</label>");
document.writeln("                                                        <input name=\"sex\" id=\"woman\" type=\"radio\">");
document.writeln("                                                        <label for=\"woman\">女</label>");
document.writeln("                                                </article>");
document.writeln("                                        </div>");
document.writeln("                                        <div class=\"clear-fix\">");
document.writeln("                                                <label class=\"fl\" for=\"age\">年龄：</label>");
document.writeln("                                                <input name=\"age\" id=\"age\" class=\"fr\" placeholder=\"年龄\" required=\"required\" type=\"tel\">");
document.writeln("                                        </div>");
document.writeln("                                        <div class=\"clear-fix\">");
document.writeln("                                                <label class=\"fl\" for=\"time\">就诊时间：</label>");
document.writeln("                                                <input name=\"time\" id=\"time\" class=\"fr\" placeholder=\"请选择您的就诊时间\" required=\"required\" type=\"date\">");
document.writeln("                                        </div>");
document.writeln("                                        <div class=\"clear-fix\">");
document.writeln("                                                <label class=\"fl\" for=\"phone\">联系方式：</label>");
document.writeln("                                                <input name=\"tel\" id=\"phone\" class=\"fr\" placeholder=\"请输入你的联系方式\" required=\"required\" type=\"tel\">");
document.writeln("                                        </div>");
document.writeln("                                        <div class=\"clear-fix\">");
document.writeln("                                                <label class=\"fl\" for=\"content\">疾病：</label>");
document.writeln("                                                <textarea type=\"text\" name=\"content\" id=\"content\" class=\"fr\" placeholder=\"请简述病情\" required=\"required\"></textarea>");
document.writeln("                                        </div>");
document.writeln("                                        <div class=\"submit\">");
document.writeln("                                                <input value=\"提交在线挂号\" onclick=\"return checkForm();\" type=\"submit\">");
document.writeln("                                        </div>");
document.writeln("                                </form>");
document.writeln("                                <p><em>温馨提醒：</em>预约成功患者，系统会将专家号和医院地址下发到您的手机，请注意查收。</p>");
document.writeln("                        </section>");

document.writeln("                        <footer>");
document.writeln("                                <h2><img src=\"images/footer-logo.jpg\" alt=\"\"/></h2>");
document.writeln("                                <p>医院地址：上海杨浦区黄兴路286号</p>");
document.writeln("                                <p>门诊时间 : 08:00--17:00 （无假日医院）</p>");
document.writeln("                                <p>咨询电话：<a href=\"tel:02152721929\">021-52721929</a></p>");
document.writeln("                                <section>");
document.writeln("                                        <a href=\"tel:02152721929\"><em><img src=\"images/swt-phone.png\" alt=\"\"/></em>电话咨询</a>");
document.writeln("                                        <a href=\"\"><em><img src=\"images/swt-consult.png\" alt=\"\"/><i></i></em>在线咨询</a>");
document.writeln("                                </section>");
document.writeln("                        </footer>");
document.writeln("                        <!--swt-->");
document.writeln("                        <section id=\"swt\">");
document.writeln("                                <article><img src=\"images/swt-close.jpg\" alt=\"\"/></article>");
document.writeln("                                <h2>上海江城皮肤专家在线</h2>");
document.writeln("                                <h3>Jiangcheng Hospital Skin Experts Online</h3>");
document.writeln("                                <section>");
document.writeln("                                        <input type=\"tel\" placeholder=\"请输入您的电话号码\"/>");
document.writeln("                                        <span>免费回电</span>");
document.writeln("                                </section>");
document.writeln("                                <a href=\"tel:02152721929\"><em><img src=\"images/swt-phone.png\" alt=\"\"/></em>电话咨询</a>");
document.writeln("                                <a href=\"\"><em><img src=\"images/swt-consult.png\" alt=\"\"/><i></i></em>在线咨询</a>");
document.writeln("                        </section>");