//JavaScript Document
/*html*/
(function(win,doc){
        /*页面自适应*/
        var oContainer=doc.getElementById('container');
        var oHtml=doc.getElementsByTagName('html')[0];
        fnResetHtmlFontSize();
        function fnResetHtmlFontSize(){
                var iContainerWidth=oContainer.offsetWidth;
                oHtml.style.fontSize=iContainerWidth/10+'px';
        }
        win.addEventListener('resize',fnResetHtmlFontSize,false);
})(window,document);

document.writeln("                        <header>");
document.writeln("                                <div class=\"header-nav\">");
document.writeln("                                        <ul>");
document.writeln("                                                <li></li>");
document.writeln("                                                <li></li>");
document.writeln("                                                <li><a href=\"tel:02152721929\"></a></li>");
document.writeln("                                        </ul>");
document.writeln("                                </div>");
document.writeln("                                <div class=\"header-content\">");
document.writeln("                                        <h2><em></em></h2>");
document.writeln("                                        <div id=\"header-content\">");
document.writeln("                                                <div class=\"hd\" id=\"header-btn\">");
document.writeln("                                                        <ol>");
document.writeln("                                                                <li class=\"on\">关于我们</li>");
document.writeln("                                                                <li>皮肤科</li>");
document.writeln("                                                                <li>皮肤外科</li>");
document.writeln("                                                                <li>皮肤美容科</li>");
document.writeln("                                                        </ol>");
document.writeln("                                                </div>");
document.writeln("                                                <div class=\"bd\">");
document.writeln("                                                        <ul>");
document.writeln("                                                                <li>");
document.writeln("                                                                        <div id=\"header-cut1\">");
document.writeln("                                                                                <span>");
document.writeln("                                                                                        <a href=\"\">后台后台1</a>");
document.writeln("                                                                                        <a href=\"\">后台后台</a>");
document.writeln("                                                                                        <a href=\"\">后台后台</a>");
document.writeln("                                                                                        <a href=\"\">后台后台</a>");
document.writeln("                                                                                        <a href=\"\">后台后台</a>");
document.writeln("                                                                                </span>");
document.writeln("                                                                        </div>");
document.writeln("                                                                </li>");
document.writeln("                                                                <li>");
document.writeln("                                                                        <div id=\"header-cut2\">");
document.writeln("                                                                                <span>");
document.writeln("                                                                                        <a href=\"\">后台后台2</a>");
document.writeln("                                                                                        <a href=\"\">后台后台</a>");
document.writeln("                                                                                        <a href=\"\">后台后台</a>");
document.writeln("                                                                                        <a href=\"\">后台后台</a>");
document.writeln("                                                                                        <a href=\"\">后台后台</a>");
document.writeln("                                                                                        <a href=\"\">后台后台</a>");
document.writeln("                                                                                </span>");
document.writeln("                                                                        </div>");
document.writeln("                                                                </li>");
document.writeln("                                                                <li>");
document.writeln("                                                                        <div id=\"header-cut3\">");
document.writeln("                                                                                <span>");
document.writeln("                                                                                        <a href=\"\">后台后台3</a>");
document.writeln("                                                                                        <a href=\"\">后台后台</a>");
document.writeln("                                                                                        <a href=\"\">后台后台</a>");
document.writeln("                                                                                        <a href=\"\">后台后台</a>");
document.writeln("                                                                                        <a href=\"\">后台后台</a>");
document.writeln("                                                                                        <a href=\"\">后台后台</a>");
document.writeln("                                                                                        <a href=\"\">后台后台</a>");
document.writeln("                                                                                        <a href=\"\">后台后台</a>");
document.writeln("                                                                                        <a href=\"\">后台后台</a>");
document.writeln("                                                                                        <a href=\"\">后台后台</a>");
document.writeln("                                                                                        <a href=\"\">后台后台</a>");
document.writeln("                                                                                        <a href=\"\">后台后台</a>");
document.writeln("                                                                                        <a href=\"\">后台后台</a>");
document.writeln("                                                                                        <a href=\"\">后台后台</a>");
document.writeln("                                                                                        <a href=\"\">后台后台</a>");
document.writeln("                                                                                        <a href=\"\">后台后台</a>");
document.writeln("                                                                                        <a href=\"\">后台后台</a>");
document.writeln("                                                                                </span>");
document.writeln("                                                                        </div>");
document.writeln("                                                                </li>");
document.writeln("                                                                <li>");
document.writeln("                                                                        <div id=\"header-cut4\">");
document.writeln("                                                                                <span>");
document.writeln("                                                                                        <a href=\"\">后台后台4</a>");
document.writeln("                                                                                        <a href=\"\">后台后台</a>");
document.writeln("                                                                                        <a href=\"\">后台后台</a>");
document.writeln("                                                                                        <a href=\"\">后台后台</a>");
document.writeln("                                                                                        <a href=\"\">后台后台</a>");
document.writeln("                                                                                        <a href=\"\">后台后台</a>");
document.writeln("                                                                                        <a href=\"\">后台后台</a>");
document.writeln("                                                                                        <a href=\"\">后台后台</a>");
document.writeln("                                                                                        <a href=\"\">后台后台</a>");
document.writeln("                                                                                        <a href=\"\">后台后台</a>");
document.writeln("                                                                                        <a href=\"\">后台后台</a>");
document.writeln("                                                                                        <a href=\"\">后台后台</a>");
document.writeln("                                                                                        <a href=\"\">后台后台</a>");
document.writeln("                                                                                        <a href=\"\">后台后台</a>");
document.writeln("                                                                                        <a href=\"\">后台后台</a>");
document.writeln("                                                                                        <a href=\"\">后台后台</a>");
document.writeln("                                                                                        <a href=\"\">后台后台</a>");
document.writeln("                                                                                        <a href=\"\">后台后台</a>");
document.writeln("                                                                                        <a href=\"\">后台后台</a>");
document.writeln("                                                                                        <a href=\"\">后台后台</a>");
document.writeln("                                                                                        <a href=\"\">后台后台</a>");
document.writeln("                                                                                        <a href=\"\">后台后台</a>");
document.writeln("                                                                                        <a href=\"\">后台后台</a>");
document.writeln("                                                                                        <a href=\"\">后台后台</a>");
document.writeln("                                                                                        <a href=\"\">后台后台</a>");
document.writeln("                                                                                        <a href=\"\">后台后台</a>");
document.writeln("                                                                                        <a href=\"\">后台后台</a>");
document.writeln("                                                                                        <a href=\"\">后台后台</a>");
document.writeln("                                                                                        <a href=\"\">后台后台</a>");
document.writeln("                                                                                        <a href=\"\">后台后台</a>");
document.writeln("                                                                                        <a href=\"\">后台后台</a>");
document.writeln("                                                                                        <a href=\"\">后台后台</a>");
document.writeln("                                                                                        <a href=\"\">后台后台</a>");
document.writeln("                                                                                        <a href=\"\">后台后台</a>");
document.writeln("                                                                                        <a href=\"\">后台后台</a>");
document.writeln("                                                                                        <a href=\"\">后台后台</a>");
document.writeln("                                                                                </span>");
document.writeln("                                                                        </div>");
document.writeln("                                                                </li>");
document.writeln("                                                        </ul>");
document.writeln("                                                </div>");
document.writeln("                                        </div>");
document.writeln("                                </div>");
document.writeln("                        </header>");