//JavaScript Document
document.writeln("                        <nav>");
document.writeln("                                <ul>");
document.writeln("                                        <li>");
document.writeln("                                                <a href=\"/\">");
document.writeln("                                                        <em><img src=\"images/nav1.png\" alt=\"\"/></em>");
document.writeln("                                                        <p>首 页</p>");
document.writeln("                                                </a>");
document.writeln("                                        </li>");
document.writeln("                                        <li>");
document.writeln("                                                <a href=\"/yyjj/\">");
document.writeln("                                                        <em><img src=\"images/nav2.png\" alt=\"\"/></em>");
document.writeln("                                                        <p>医院简介</p>");
document.writeln("                                                </a>");
document.writeln("                                        </li>");
document.writeln("                                        <li>");
document.writeln("                                                <a href=\"/dianxinganli/\">");
document.writeln("                                                        <em><img src=\"images/nav5.png\" alt=\"\"/></em>");
document.writeln("                                                        <p>病友交流</p>");
document.writeln("                                                </a>");
document.writeln("                                        </li>");
document.writeln("                                        <li>");
document.writeln("                                                <a href=\"/zt/mtbd/\">");
document.writeln("                                                        <em><img src=\"images/nav6.png\" alt=\"\"/></em>");
document.writeln("                                                        <p>社会公益</p>");
document.writeln("                                                </a>");
document.writeln("                                        </li>");
document.writeln("                                </ul>");
document.writeln("                        </nav>");