// JavaScript Document
document.writeln("<!--header-->");
document.writeln("<style>");
document.writeln("/*clearFix*/");
document.writeln(".clearFix{ clear:both; *zoom:1;}");
document.writeln(".clearFix:after{ clear:both; display:block; visibility:hidden; height:0; line-height:0; content:\"\"; font-size:0;}");
document.writeln("/*common*/");
document.writeln(".fl{ float:left;}");
document.writeln(".fr{ float:right;}");
document.writeln("/*zero*/");
document.writeln("div,ul,ol,li,em,a,img{ margin:0; padding:0;}");
document.writeln("/*head*/");
document.writeln("#header img{ vertical-align:middle; border:none; outline:none;}");
document.writeln("#header a{ display:block; color:#000; text-decoration:none; outline:none;}");
document.writeln("#header em{ display:inline-block; font-style:normal;}");
document.writeln("#header  ul,ol,li{ list-style:none;}");
document.writeln("#header .w320{ width:320px; margin:0 auto; overflow:hidden;}");
document.writeln("#header #nav{ margin-bottom:20px;}");
document.writeln("#header #nav li{ width:80px; text-align:center; height:40px; line-height:40px; background:#a2151e; float:left;}");
document.writeln("#header #nav li a{ color:#fff; font-size:16px; border-right:1px solid #870007;}");
document.writeln("#header #nav li a.noBr{ border-right:none;}");
document.writeln("#header #banner{ position:relative;}");
document.writeln("#header #banner ol{ position:absolute; right:0; bottom:0;}");
document.writeln("#header #banner ol li{ float:left; width:10px; height:10px; background:#494949; border-radius:50%; margin:5px;}");
document.writeln("#header #banner ol li.on{ background:#a1151e;}");
document.writeln("#header #banner ul{ width:3000px;}");
document.writeln("#header #banner ul li{ float:left; width:320px;}");
document.writeln("#header #menu{ margin-top:20px; background:#fcfcfc;}");
document.writeln("#header #menu ul{ border:1px solid #ededed;}");
document.writeln("#header #menu li{ float:left; width:119px; padding:0 20px;}");
document.writeln("#header #menu li.br{ width:118px; border-right:1px solid #ededed;}");
document.writeln("#header #menu a{ padding:5px 0; font-size:14px; color:#666666;}");
document.writeln("#header #menu a.bt{ border-top:1px dashed #ededed;}");
document.writeln("#header #menu a.bb{ border-bottom:1px dashed #ededed;}");
document.writeln("#header #menu em{ vertical-align:middle; margin-right:14px;}");
document.writeln("</style>");
document.writeln("<div id=\"header\" class=\"w320\">");
document.writeln("	<div id=\"logo\"><img src=\"/images/logo.jpg\" /></div>");
document.writeln("	<div id=\"nav\">");
document.writeln("        	<ul class=\"clearFix\">");
document.writeln("                	<li><a href=\"/\">网站首页</a></li>");
document.writeln("                	<li><a href=\"/zt/qwzj/\">专家介绍</a></li>");
document.writeln("                	<li><a href=\"/zt/lylx/\">来院路线</a></li>");
document.writeln("                	<li><a href=\"javascript:void(0)\" onclick=\"swt()\">在线挂号</a></li>");
document.writeln("                </ul>");
document.writeln("        </div>");
document.writeln("        <div id=\"banner\">");
document.writeln("        	<ul class=\"clearFix\">");
document.writeln("                	<li><img src=\"/images/banner1.jpg\" /></li>");
document.writeln("                	<li><img src=\"/images/banner2.jpg\" /></li>");
document.writeln("                	<li><img src=\"/images/banner3.jpg\" /></li>");
document.writeln("                </ul>");
document.writeln("        	<ol class=\"clearFix\">");
document.writeln("                	<li class=\"on\"></li>");
document.writeln("                	<li></li>");
document.writeln("                	<li></li>");
document.writeln("                </ol>");
document.writeln("        </div>");
document.writeln("        <div id=\"menu\">");
document.writeln("        	<ul class=\"clearFix\">");
document.writeln("                	<li class=\"br\"><a href=\"javascript:void(0)\" onclick=\"swt()\"><em><img src=\"/images/menu1.jpg\" /></em>门诊时间</a></li>");
document.writeln("                	<li><a href=\"javascript:void(0)\" onclick=\"swt()\"><em><img src=\"/images/menu2.jpg\" /></em>病例检查</a></li>");
document.writeln("                	<li class=\"br \"><a class=\"bt\" href=\"javascript:void(0)\" onclick=\"swt()\"><em><img src=\"/images/menu3.jpg\" /></em>预约挂号</a></li>");
document.writeln("                	<li class=\"\"><a class=\"bt\" href=\"javascript:void(0)\" onclick=\"swt()\"><em><img src=\"/images/menu4.jpg\" /></em>挂号须知</a></li>");
document.writeln("                </ul>");
document.writeln("        </div>");
document.writeln("</div>");
document.writeln("<script>TouchSlide({ slideCell:\"#banner\",titCell:\"ol li\",mainCell:\"ul\",autoPlay:true});</script>");