// JavaScript Document
document.writeln("    	<div class=\"registered_box\">");
document.writeln("");
document.writeln("   <form method=\"post\" accept-charset=\"GB2312\" onsubmit=\"if(isIE)document.charset='GB2312'\" action=\"http://swt.gssmart.com/guahao/sockt.php\" name=\"comment\" id=\"guahaoform\" >");
document.writeln("");
document.writeln("        	<h3>（提交信息已加密，保障个人隐私）</h3>");
document.writeln("");
document.writeln("        	<ul>");
document.writeln("");
document.writeln("            	<li>");
document.writeln("");
document.writeln("                    <span>患者姓名：</span><input type=\"text\"  name=\"名称\"  id=\"username\" placeholder=\"请输入您的姓名！\"/>");
document.writeln("");
document.writeln("    			</li>");
document.writeln("");
document.writeln("                <li>");
document.writeln("");
document.writeln("                    <span>联系电话：</span><input type=\"tel\" name=\"电话\"  id=\"phone\" placeholder=\"请输入您的联系方式！\"/>");
document.writeln("");
document.writeln("    			</li>");
document.writeln("");
document.writeln("                <li>");
document.writeln("");
document.writeln("                    <span>疾病症状：</span><input type=\"text\"  name=\"病情描述\" id=\"content\" placeholder=\"请输入您的症状！\"/>");
document.writeln("");
document.writeln("    			</li>");
document.writeln("");
document.writeln("    		</ul>");
document.writeln("");
document.writeln("            <div class=\"tijiao\">");
document.writeln("");
document.writeln("                <dl>");
document.writeln("");
document.writeln("             <button class=\"tijiao_inner\" class=\"submit\" onClick=\"return checkForm();\" >提交</button>");
document.writeln("             <button type=\"reset\" value=\"重置\">重置</button>");
document.writeln("");
document.writeln("                </dl>");
document.writeln("");
document.writeln("            </div>");
document.writeln("");
document.writeln("          </form>");
document.writeln("    <script type=\"text/javascript\" src=\"js/guahao.js\"></script>");
document.writeln("    	</div>");