// JavaScript Document
document.writeln("        <!--banner-->");
document.writeln("        <!--rookie making about javascript-->      ");
document.writeln("        <style>");
document.writeln("		#focusindex {    height: 500px;    overflow: hidden;    position:relative;}");
document.writeln("		#focusindex li {    height: 500px;    overflow: hidden;    position: absolute;    width: 100%;}");
document.writeln("		#focusindex .btn1 {    bottom: 0;    height: 100px;    position: absolute;    text-align: center;    width: 100%;    z-index: 9; background:#000; opacity:0.4; filter:alpha(opacity=40);}");
document.writeln("		#focusindex .btn { width:1000px; height: 100px; position:absolute; bottom:0; z-index: 10; left:50%; margin-left:-500px  }");
document.writeln("		");
document.writeln("		#focusindex .btn span { cursor: pointer;    display: inline; margin: 4px;  z-index: 9; border:#999 2px solid ; float:left}");
document.writeln("		#focusindex .btn span.on {  border:#eb6100 2px solid ; z-index: 11;}");
document.writeln("		");
document.writeln("		#focusindex .preNext { background: url(http://pfb.skinjc.com/img_new/lr.png) no-repeat scroll left bottom ; position:absolute;    cursor: pointer;    height: 54px;    opacity: 1;  width: 29px;   z-index:11;}");
document.writeln("		#focusindex .pre { top:23px; left:0; z-index:11;}");
document.writeln("		#focusindex .next {background-position: right bottom;top:23px; right:0; z-index: 11;}");
document.writeln("		#focusindex:hover .preNext {    opacity: 0.5;}");
document.writeln("				");
document.writeln("		#focusindex .pre:hover, #focusindex .next:hover {  opacity: 1;}");
document.writeln("		.banner1 {    background: url(http://pfb.skinjc.com/img_new/1m.jpg) no-repeat scroll center center;    z-index: 1;}");
document.writeln("		.banner2 {    background: url(http://pfb.skinjc.com/img_new/2m.jpg) no-repeat scroll center center;}");
document.writeln("		.banner3 {    background: url(http://pfb.skinjc.com/img_new/3m.jpg) no-repeat scroll center center;}");
document.writeln("		.banner4 {    background: url(http://pfb.skinjc.com/img_new/4m.jpg) no-repeat scroll center center;}");
document.writeln("		.banner5 {    background: url(http://pfb.skinjc.com/img_new/5m.jpg) no-repeat scroll center center;}");
document.writeln("		.banner6 {    background: url(http://pfb.skinjc.com/img_new/6m.jpg) no-repeat scroll center center;}");
document.writeln("		.banner7 {    background: url(http://pfb.skinjc.com/img_new/7m.jpg) no-repeat scroll center center;}");
document.writeln("		.banner8 {    background: url(http://pfb.skinjc.com/img_new/8m.jpg) no-repeat scroll center center;}");
document.writeln("		.banner9 {    background: url(http://pfb.skinjc.com/img_new/9m.jpg) no-repeat scroll center center;}");
document.writeln("		.banner10 {    background: url(http://pfb.skinjc.com/img_new/10m.jpg) no-repeat scroll center center;}");
document.writeln("		.banner11 {    background: url(http://pfb.skinjc.com/img_new/11m.jpg) no-repeat scroll center center;}");
document.writeln("		.banner12 {    background: url(http://pfb.skinjc.com/img_new/12m.jpg) no-repeat scroll center center;}");
document.writeln("		.banner13 {    background: url(http://pfb.skinjc.com/img_new/13m.jpg) no-repeat scroll center center;}");
document.writeln("	</style>");
document.writeln("        <div id=\"focusindex\">");
document.writeln("                <ul class=\"index_banner_box\">");
document.writeln("                        <a href=\"/zt/mtbd/dfmz/\" target=\"_blank\" title=\"东方明珠\"><li style=\"opacity: 1; z-index: 1;\" class=\"banner6\"></li></a>");
document.writeln("                        <a href=\"/special/surprise/\" target=\"_blank\" title=\"活动\"><li style=\"opacity: 0; z-index: 0;\" class=\"banner7\"></li></a>");
document.writeln("                        <a href=\"/special/weixin/\" target=\"_blank\" title=\"微信\"><li style=\"opacity: 0; z-index: 0;\" class=\"banner13\"></li></a> ");
document.writeln("                        <a href=\"/zt/mtbd/zzhz/\" target=\"_blank\" title=\"重症患者\"><li style=\"opacity: 0; z-index: 0;\" class=\"banner5\"></li></a> ");
document.writeln("                        <a href=\"/zt/mtbd/index5.html\" target=\"_blank\" title=\"熊猫女婴\"><li style=\"opacity: 0; z-index: 0;\" class=\"banner1\"></li></a> ");
document.writeln("                        <a href=\"/zt/mtbd/\" target=\"_blank\" title=\"穿山甲宝宝\"><li style=\"opacity: 0; z-index: 0;\" class=\"banner2\"></li></a> ");
document.writeln("                        <a href=\"/zt/mtbd/index2.html\" target=\"_blank\" title=\"血管瘤感恩\"><li style=\"opacity: 0; z-index: 0;\" class=\"banner3\"></li></a> ");
document.writeln("                        <a href=\"http://zhifa.skinjc.com/zhifadongtai/2014/1022/639.html\" target=\"_blank\" title=\"李衡华采访\"><li style=\"opacity: 0; z-index: 0;\" class=\"banner10\"></li></a> ");
document.writeln("                        <a href=\"/zt/wyq/\" target=\"_blank\" title=\"吴玉琴采访\"><li style=\"opacity: 0; z-index: 0;\" class=\"banner11\"></li></a> ");
document.writeln("                        <a href=\"/special/zjzt/index16.html\" target=\"_blank\" title=\"彭静\"><li style=\"opacity: 0; z-index: 0;\" class=\"banner12\"></li></a> ");
document.writeln("                        <a href=\"/zt/mtbd/index6.html\" target=\"_blank\" title=\"走进社区\"><li style=\"opacity: 0; z-index: 0;\" class=\"banner4\"></li></a> ");
document.writeln("                        <a href=\"/special/zjzt/\" target=\"_blank\" title=\"专家团队\"><li style=\"opacity: 0; z-index: 0;\" class=\"banner9\"></li></a>");
document.writeln("                </ul>");
document.writeln("                <div class=\"btn\">");
document.writeln("                        <div style=\"position:relative; width:795px; height:100px; \">");
document.writeln("                                <div class=\"preNext pre\" id=\"LeftArr2\"></div>");
document.writeln("                                <div class=\"preNext next\" id=\"RightArr2\"></div>");
document.writeln("                                <div style=\"width: 725px; position: absolute; left: 50%; margin: 0px 0px 0px -367px; overflow: hidden;\" id=\"picgun2\">");
document.writeln("                                        <div style=\"overflow: hidden; width: 32766px;\">");
document.writeln("                                                <div class=\"picgun2_pos\" style=\"float: left; position:relative; left:0; top:0;\"> ");
document.writeln("                                                	  <span class=\"on\" style=\"opacity: 1;\"><img src=\"http://pfb.skinjc.com/img_new/6small.png\" height=\"81\" width=\"133\"></span>");
document.writeln("                                                        <span class=\"\" style=\"opacity: 1;\"><img src=\"http://pfb.skinjc.com/img_new/7small.jpg\" height=\"81\" width=\"133\"></span> ");
document.writeln("                                                        <span class=\"\" style=\"opacity: 1;\"><img src=\"http://pfb.skinjc.com/img_new/13small.jpg\" height=\"81\" width=\"133\"></span> ");
document.writeln("                                                        <span class=\"\" style=\"opacity: 1;\"><img src=\"http://pfb.skinjc.com/img_new/5small.jpg\" height=\"81\" width=\"133\"></span> ");
document.writeln("                                                        <span class=\"\" style=\"opacity: 1;\"><img src=\"http://pfb.skinjc.com/img_new/1small.jpg\" height=\"81\" width=\"133\"></span> ");
document.writeln("                                                        <span class=\"\" style=\"opacity: 1;\"><img src=\"http://pfb.skinjc.com/img_new/2small.jpg\" height=\"81\" width=\"133\"></span> ");
document.writeln("                                                        <span class=\"\" style=\"opacity: 1;\"><img src=\"http://pfb.skinjc.com/img_new/3small.jpg\" height=\"81\" width=\"133\"></span> ");
document.writeln("                                                        <span class=\"\" style=\"opacity: 1;\"><img src=\"http://pfb.skinjc.com/img_new/10small.jpg\" height=\"81\" width=\"133\"></span> ");
document.writeln("                                                        <span class=\"\" style=\"opacity: 1;\"><img src=\"http://pfb.skinjc.com/img_new/11small.jpg\" height=\"81\" width=\"133\"></span> ");
document.writeln("                                                        <span class=\"\" style=\"opacity: 1;\"><img src=\"http://pfb.skinjc.com/img_new/12small.jpg\" height=\"81\" width=\"133\"></span>");
document.writeln("                                                        <span class=\"\" style=\"opacity: 1;\"><img src=\"http://pfb.skinjc.com/img_new/4small.jpg\" height=\"81\" width=\"133\"></span> ");
document.writeln("                                                        <span class=\"\" style=\"opacity: 1;\"><img src=\"http://pfb.skinjc.com/img_new/9small.jpg\" height=\"81\" width=\"133\"></span>");
document.writeln("                                                </div>                                                ");
document.writeln("                                        </div>");
document.writeln("                                </div>");
document.writeln("                        </div>");
document.writeln("                        <a onclick=\"openZoosUrl();return false;\" href=\"javascript:void(0)\" style=\" position:absolute; right:0; top:5px\"><img src=\"http://pfb.skinjc.com/img_new/zx.png\"></a> ");
document.writeln("                </div>");
document.writeln("                <div class=\"btn1\"></div>");
document.writeln("        </div>");
document.writeln("        <script>");
document.writeln("        <!--rookie making about javascript-->   ");
document.writeln("		(function(){");
document.writeln("			var aBtn=document.querySelectorAll(\'#focusindex .btn span\');");
document.writeln("			var aCut=document.querySelectorAll(\'#focusindex li\');");
document.writeln("			var oBtn=document.querySelector(\'#focusindex #picgun2 .picgun2_pos\');	");
document.writeln("			var oPrev=document.querySelector(\'#focusindex #LeftArr2\');");
document.writeln("			var oNext=document.querySelector(\'#focusindex #RightArr2\');		");
document.writeln("			var iLen=aBtn.length;");
document.writeln("			var iWidth=aBtn[0].offsetWidth+8;");
document.writeln("			var now=0;");
document.writeln("			var timer=null;");
document.writeln("			for(var i=0; i<iLen; i++){");
document.writeln("				aBtn[i].index=i;");
document.writeln("				aBtn[i].onclick=function(){");
document.writeln("					now=this.index;");
document.writeln("					tab();");
document.writeln("				}	");
document.writeln("			}");
document.writeln("			oNext.onclick=function(){");
document.writeln("				now++;");
document.writeln("				now%=iLen;");
document.writeln("				tab();");
document.writeln("			}");
document.writeln("			timer=setInterval(oNext.onclick,5000)");
document.writeln("			aCut[0].parentNode.parentNode.onmouseover=function(){");
document.writeln("				clearInterval(timer);	");
document.writeln("			}");
document.writeln("			aCut[0].parentNode.parentNode.onmouseout=function(){				");
document.writeln("				timer=setInterval(oNext.onclick,5000)	");
document.writeln("			}");
document.writeln("			oPrev.onclick=function(){				");
document.writeln("				now--;");
document.writeln("				(now==-1)&&(now=iLen-1);");
document.writeln("				tab();");
document.writeln("			}	");
document.writeln("			function tab(){				");
document.writeln("					for(var i=0; i<iLen; i++){");
document.writeln("						aBtn[i].className=\'\';");
document.writeln("						aCut[i].style.zIndex=0;");
document.writeln("						move(aCut[i],{\'opacity\':0})							");
document.writeln("					}");
document.writeln("					aBtn[now].className=\'on\';");
document.writeln("					aCut[now].style.zIndex=1;");
document.writeln("					move(aCut[now],{\'opacity\':100})	;");
document.writeln("					now>=4?move(oBtn,{\'left\':-iWidth*(now-3)}):move(oBtn,{\'left\':0});");
document.writeln("					now>=(iLen-2)&&move(oBtn,{\'left\':-iWidth*(iLen-5)});	");
document.writeln("			}");
document.writeln("			function getStyle(obj,attr){return obj.currentStyle?obj.currentStyle[attr]:getComputedStyle(obj,false)[attr];}");
document.writeln("			function move(obj,json){");
document.writeln("				clearInterval(obj.timer);");
document.writeln("				obj.timer=setInterval(function(){");
document.writeln("					var bStop=true;");
document.writeln("					for(var attr in json){");
document.writeln("						var cur=(attr==\'opacity\')?Math.round(getStyle(obj,attr)*100):parseInt(getStyle(obj,attr));");
document.writeln("						var speed=(json[attr]-cur)/10;");
document.writeln("						var speed=(speed>0)?Math.ceil(speed):Math.floor(speed);");
document.writeln("						(cur!=json[attr])&&(bStop=false);");
document.writeln("						if(attr==\'opacity\'){");
document.writeln("							obj.style.opacity=(cur+speed)/100;");
document.writeln("							obj.style.fillter=\'alpha(opacity:\'+(cur+speed)+\')\';	");
document.writeln("						}else{");
document.writeln("							obj.style[attr]=cur+speed+\'px\';");
document.writeln("						}");
document.writeln("					}");
document.writeln("					bStop&&clearInterval(obj.timer);");
document.writeln("				},30)");
document.writeln("			}");
document.writeln("		})();");
document.writeln("        <!--rookie making about javascript--> ");
document.writeln("        </script>");