document.writeln("<!--周华飞制作 QQ:1123486116-->");
document.writeln("<style>");
document.writeln("/*--------------------------------top_nav------------------------------------------*/");
document.writeln(".top_nav{ height:55px; background:#0064b4;}");
document.writeln(".top_nav ul{ height:100%; width:1000px; margin:0 auto;}");
document.writeln(".top_nav li{ height:100%; float:left;}");
document.writeln(".top_nav li a{ height:100%; line-height:55px; padding:0 30px; font-size:20px; color:#fff;}");
document.writeln(".top_nav li .a_active{ background:#323232; box-shadow:1px -1px 10px #fff;}");
document.writeln("</style>");
document.writeln("<!---------------------------------top_nav------------------------------------------>");
document.writeln("<div class=\"top_nav\" id=\"top_nav\">");
document.writeln("	<ul>");
document.writeln("		<li><a class=\"a_active\" href=\"/\">首页</a></li>");
document.writeln("		<li><a href=\"/special/yyjs/\">医院简介</a></li>");
document.writeln("		<li><a href=\"/special/zjzt/\">专家介绍</a></li>");
document.writeln("		<li><a href=\"/\">毛发移植</a></li>");
document.writeln("		<li><a href=\"/special/yysb/\">设备安全保障</a></li>");
document.writeln("		<li><a href=\"/special/jcal/\">典型案例</a></li>");
document.writeln("		<li><a href=\"/special/map/\">来院路线</a></li>");
document.writeln("		<li><a href=\"javascript:void(0);return false;\" onclick=\"openZoosUrl();return false;\">在线预约</a></li>                                         ");
document.writeln("	</ul>");
document.writeln("</div>");
document.writeln("<script>");
document.writeln("eventBind(window,\'load\',function()");
document.writeln("{");
document.writeln("	/*top_nav*/");
document.writeln("	var oTop_nav=document.getElementById(\'top_nav\'); ");
document.writeln("	var aTop_li=oTop_nav.getElementsByTagName(\'a\');");
document.writeln("	navTab(aTop_li,\'a_active\')");
document.writeln("	function navTab(obj,attr)");
document.writeln("	{");
document.writeln("		for(var i=0; i<obj.length; i++)");
document.writeln("		{");
document.writeln("			obj[i].onmouseover=function()");
document.writeln("			{");
document.writeln("				for(var i=0; i<obj.length; i++)");
document.writeln("				{");
document.writeln("					obj[i].className=\'\';	");
document.writeln("				}");
document.writeln("				this.className=attr;");
document.writeln("			}	");
document.writeln("		}");
document.writeln("		");
document.writeln("	}");
document.writeln("})");
document.writeln("function eventBind(obj,ev,fn)");
document.writeln("{");
document.writeln("	if(obj.attachEvent)");
document.writeln("	{");
document.writeln("		obj.attachEvent(\'on\'+ev,fn);");
document.writeln("	}");
document.writeln("	else");
document.writeln("	{");
document.writeln("		obj.addEventListener(ev,fn,false);");
document.writeln("	}	");
document.writeln("}");
document.writeln("</script>");
document.writeln("<!--周华飞制作 QQ:1123486116-->");