// JavaScript Document
/*********************************
 *周华飞制作 QQ:1123486116
 *rookie making
 *rookie Copyright
 *未经允许禁止复制和盗用违权必究
**********************************/
document.writeln("<style>");
document.writeln("/*footerSlide*/");
document.writeln("#footerSlide,#footerTab{ margin-top:70px;}");
document.writeln("#footerSlide ol,#footerTab ol{ border-bottom:2px solid #e1e1e1;}");
document.writeln("#footerSlide ol li,#footerTab ol li{ float:left; margin:0 40px -2px 0; font-size:22px; color:#4b4b4b; border-bottom:2px solid #e1e1e1; padding-bottom:14px; margin-bottom:-2px; position:relative;}");
document.writeln("#footerSlide ol em,#footerTab ol em{ opacity:0; filter:alpha(opacity:0); width:0px; height:0px; border:6px solid transparent; border-bottom:6px solid #0064b4;  position:absolute; bottom:0; left:50%; margin-left:-6px;}");
document.writeln("#footerSlide ol .active,#footerTab ol .active{ border-bottom:2px solid #0064b4;}");
document.writeln("#footerSlide ol .active em,#footerTab ol .active em{ opacity:1; filter:alpha(opacity:100);}");
document.writeln("#footerSlide div{ display:none; margin-top:32px; height:190px; overflow:hidden; position:relative;}");
document.writeln("#footerSlide div ul{ height:190px; position:absolute; left:0; top:0; width:3000px;}");
document.writeln("#footerSlide div.active{ display:block;}");
document.writeln("#footerSlide div li{ float:left; padding:7px; background:#e6e6e6; width:230px; height:176px; margin-right:8px;}");
document.writeln("#footerSlide div a{ display:block;}");
document.writeln("/*footerTab*/");
document.writeln("#footerTab div{ overflow:hidden; height:94px; margin-top:34px;}");
document.writeln("#footerTab ul{ display:none; height:94px;}");
document.writeln("#footerTab ul.active{ display:block;}");
document.writeln("#footerTab ul li{ float:left; margin-right:57px;}");
document.writeln("#footerTab ul em{ width:94px; height:94px; background:url(images/footerEm.png) left top no-repeat;}");
document.writeln("#footerTab ul .footerEm1_1{ background-position: left top;}");
document.writeln("#footerTab ul .footerEm1_2{ background-position: left -216px;}");
document.writeln("#footerTab ul .footerEm1_3{ background-position: left -432px;}");
document.writeln("#footerTab ul .footerEm1_4{ background-position: left -648px;}");
document.writeln("#footerTab ul .footerEm1_5{ background-position: left -864px;}");
document.writeln("#footerTab ul .footerEm1_6{ background-position: left -1080px;}");
document.writeln("#footerTab ul .footerEm1_7{ background-position: left -1296px;}");
document.writeln("#footerTab ul .active .footerEm1_1{ background-position: left -108px;}");
document.writeln("#footerTab ul .active .footerEm1_2{ background-position: left -324px;}");
document.writeln("#footerTab ul .active .footerEm1_3{ background-position: left -540px;}");
document.writeln("#footerTab ul .active .footerEm1_4{ background-position: left -756px;}");
document.writeln("#footerTab ul .active .footerEm1_5{ background-position: left -972px;}");
document.writeln("#footerTab ul .active .footerEm1_6{ background-position: left -1188px;}");
document.writeln("#footerTab ul .active .footerEm1_7{ background-position: left -1404px;}");
document.writeln("#footerTab ul .footerEm2_1{ background-position: left top;}");
document.writeln("#footerTab ul .footerEm2_2{ background-position: left -216px;}");
document.writeln("#footerTab ul .footerEm2_3{ background-position: left -432px;}");
document.writeln("#footerTab ul .footerEm2_4{ background-position: left -648px;}");
document.writeln("#footerTab ul .footerEm2_5{ background-position: left -864px;}");
document.writeln("#footerTab ul .footerEm2_6{ background-position: left -1080px;}");
document.writeln("#footerTab ul .footerEm2_7{ background-position: left -1296px;}");
document.writeln("#footerTab ul .active .footerEm2_1{ background-position: left -108px;}");
document.writeln("#footerTab ul .active .footerEm2_2{ background-position: left -324px;}");
document.writeln("#footerTab ul .active .footerEm2_3{ background-position: left -540px;}");
document.writeln("#footerTab ul .active .footerEm2_4{ background-position: left -756px;}");
document.writeln("#footerTab ul .active .footerEm2_5{ background-position: left -972px;}");
document.writeln("#footerTab ul .active .footerEm2_6{ background-position: left -1188px;}");
document.writeln("#footerTab ul .active .footerEm2_7{ background-position: left -1404px;}");
document.writeln("/*footerNav*/");
document.writeln("#footerNav{ background:#646464; margin-top:70px;}");
document.writeln("#footerNav ul{ background:#4b4b4b; width:1000px; margin:0 auto;}");
document.writeln("#footerNav li{ float:left;}");
document.writeln("#footerNav a{ display:block; width:200px; text-align:center; height:54px; line-height:54px; font-size:20px; color:#dcdcdc;}");
document.writeln("#footerNav .active{ background:#0064b4; box-shadow:1px 1px 20px #fff;}");
document.writeln("/*footer*/");
document.writeln("#footer{ background:#646464; overflow:hidden;}");
document.writeln("/*footerMain*/");
document.writeln("#footerMain{ width:1000px; margin:50px auto;}");
document.writeln("#footerMain:hover .img{ transform:rotate(360deg); -webkit-transform:rotate(360deg);}");
document.writeln("#footerMain #footerLogo{ width:350px; text-align:center; color:#dcdcdc;}");
document.writeln("#footerMain #footerLogo .img{ margin-bottom:18px; transition:0.4s;}");
document.writeln("#footerMain #footerLogo h2{ font-size:34px;}");
document.writeln("#footerMain #footerLogo p{ font-size:12px;}");
document.writeln("#footerMain #footerCont{ width:468px; border-left:1px solid #505050; border-right:1px solid #505050; padding:10px 20px;}");
document.writeln("#footerMain #footerCont p{ font-size:16px; color:#dcdcdc; line-height:33px;}");
document.writeln("#footerMain #footerCont em{ width:80px; line-height:33px;}");
document.writeln("#footerMain #footerCode{ width:140px; text-align:center; color:#dcdcdc;}");
document.writeln("#footerMain #footerCode .img{ margin-bottom:18px; transition:0.4s;}");
document.writeln("#footerMain #footerCode p{ font-size:16px;}");
document.writeln("/*footerCopy*/");
document.writeln("#footerCopy{ background:#4b4b4b; padding:10px;}");
document.writeln("#footerCopy p{ font-size:16px; color:#dcdcdc; text-align:center; line-height:24px;}");
document.writeln("</style>");
document.writeln("<!--footerSlide-->");
document.writeln("<div id=\"footerSlide\" class=\"w1000\">");
document.writeln("	<ol class=\"clearFix\">");
document.writeln("        	<li class=\"active\">康复案例<em></em></li>");
document.writeln("        	<li>先进设备<em></em></li>");
document.writeln("        	<li>就医环境<em></em></li>");
document.writeln("        </ol>");
document.writeln("        <div class=\"active\">");
document.writeln("                <ul>");
document.writeln("                        <li><a href=\"javascript:void(0);return false;\" onclick=\"openZoosUrl();return false;\" target=\"_blank\"><img src=\"images/footerSlide1_1.jpg\" /></a></li>");
document.writeln("                        <li><a href=\"javascript:void(0);return false;\" onclick=\"openZoosUrl();return false;\" target=\"_blank\"><img src=\"images/footerSlide1_2.jpg\" /></a></li>");
document.writeln("                        <li><a href=\"javascript:void(0);return false;\" onclick=\"openZoosUrl();return false;\" target=\"_blank\"><img src=\"images/footerSlide1_3.jpg\" /></a></li>");
document.writeln("                        <li><a href=\"javascript:void(0);return false;\" onclick=\"openZoosUrl();return false;\" target=\"_blank\"><img src=\"images/footerSlide1_4.jpg\" /></a></li>");
document.writeln("                </ul>");
document.writeln("        </div>");
document.writeln("        <div>");
document.writeln("                <ul>");
document.writeln("                        <li><a href=\"javascript:void(0);return false;\" onclick=\"openZoosUrl();return false;\" target=\"_blank\"><img src=\"images/footerSlide2_1.jpg\" /></a></li>");
document.writeln("                        <li><a href=\"javascript:void(0);return false;\" onclick=\"openZoosUrl();return false;\" target=\"_blank\"><img src=\"images/footerSlide2_2.jpg\" /></a></li>");
document.writeln("                        <li><a href=\"javascript:void(0);return false;\" onclick=\"openZoosUrl();return false;\" target=\"_blank\"><img src=\"images/footerSlide2_3.jpg\" /></a></li>");
document.writeln("                        <li><a href=\"javascript:void(0);return false;\" onclick=\"openZoosUrl();return false;\" target=\"_blank\"><img src=\"images/footerSlide2_4.jpg\" /></a></li>");
document.writeln("                </ul>");
document.writeln("        </div>");
document.writeln("        <div>    ");
document.writeln("                <ul>");
document.writeln("                        <li><a href=\"javascript:void(0);return false;\" onclick=\"openZoosUrl();return false;\" target=\"_blank\"><img src=\"images/footerSlide3_1.jpg\" /></a></li>");
document.writeln("                        <li><a href=\"javascript:void(0);return false;\" onclick=\"openZoosUrl();return false;\" target=\"_blank\"><img src=\"images/footerSlide3_2.jpg\" /></a></li>");
document.writeln("                        <li><a href=\"javascript:void(0);return false;\" onclick=\"openZoosUrl();return false;\" target=\"_blank\"><img src=\"images/footerSlide3_3.jpg\" /></a></li>");
document.writeln("                        <li><a href=\"javascript:void(0);return false;\" onclick=\"openZoosUrl();return false;\" target=\"_blank\"><img src=\"images/footerSlide3_4.jpg\" /></a></li>");
document.writeln("                </ul>");
document.writeln("        </div>");
document.writeln("</div>");
document.writeln("<!--footerTab-->");
document.writeln("<div id=\"footerTab\" class=\"w1000\">	");
document.writeln("	<ol class=\"clearFix\">");
document.writeln("        	<li class=\"active\">监督单位<em></em></li>");
document.writeln("        	<li>合作机构<em></em></li>");
document.writeln("        </ol>");
document.writeln("        <div>");
document.writeln("                <ul class=\"active\">");
document.writeln("                        <li class=\"active\"><em class=\"footerEm1_1\"></em></li>");
document.writeln("                        <li><em class=\"footerEm1_2\"></em></li>");
document.writeln("                        <li><em class=\"footerEm1_3\"></em></li>");
document.writeln("                        <li><em class=\"footerEm1_4\"></em></li>");
document.writeln("                        <li><em class=\"footerEm1_5\"></em></li>");
document.writeln("                        <li><em class=\"footerEm1_6\"></em></li>");
document.writeln("                        <li style=\"margin-right:0;\"><em class=\"footerEm1_7\"></em></li>");
document.writeln("                </ul>");
document.writeln("                <ul>");
document.writeln("                        <li class=\"active\"><em class=\"footerEm2_1\"></em></li>");
document.writeln("                        <li><em class=\"footerEm2_2\"></em></li>");
document.writeln("                        <li><em class=\"footerEm2_3\"></em></li>");
document.writeln("                        <li><em class=\"footerEm2_4\"></em></li>");
document.writeln("                        <li><em class=\"footerEm2_5\"></em></li>");
document.writeln("                        <li><em class=\"footerEm2_6\"></em></li>");
document.writeln("                        <li style=\"margin-right:0;\"><em class=\"footerEm2_7\"></em></li>");
document.writeln("                </ul>");
document.writeln("        </div>");
document.writeln("</div>");
document.writeln("<!--footerNav-->");
document.writeln("<div id=\"footerNav\">");
document.writeln("	<ul class=\"clearFix\">");
document.writeln("        	<li class=\"active\"><a href=\"javascript:void(0);return false;\" onclick=\"openZoosUrl();return false;\" target=\"_blank\">寻常型银屑病</a></li>");
document.writeln("        	<li><a href=\"javascript:void(0);return false;\" onclick=\"openZoosUrl();return false;\" target=\"_blank\">关节型银屑病</a></li>");
document.writeln("        	<li><a href=\"javascript:void(0);return false;\" onclick=\"openZoosUrl();return false;\" target=\"_blank\">脓疱型银屑病</a></li>");
document.writeln("        	<li><a href=\"javascript:void(0);return false;\" onclick=\"openZoosUrl();return false;\" target=\"_blank\">红皮型银屑病</a></li>");
document.writeln("        	<li><a href=\"javascript:void(0);return false;\" onclick=\"openZoosUrl();return false;\" target=\"_blank\">掌趾银屑病</a></li>");
document.writeln("        </ul>");
document.writeln("</div>");
document.writeln("<!--footer-->");
document.writeln("<div id=\"footer\">");
document.writeln("	<div id=\"footerMain\" class=\"clearFix\">");
document.writeln("                <div id=\"footerLogo\" class=\"fl\">");
document.writeln("                        <div class=\"img\"><img src=\"images/footer_logo.png\"></div>");
document.writeln("                        <h2>上海江城皮肤病医院</h2>");
document.writeln("                        <p>Shanghai Jiangcheng Dermatology Hospital</p>                       	");
document.writeln("                </div>");
document.writeln("                <div id=\"footerCont\" class=\"fl\">");
document.writeln("                        <p><em>医院地址：</em>上海市杨浦区黄兴路286号</p>");
document.writeln("                        <p><em>植发电话：</em>021-6519  1999</p>");
document.writeln("                        <p><em>温馨提示：</em>任何建议都不能替代执业医师当面诊断，所有门诊时间</p>");
document.writeln("                        <p><em></em>仅供参考，最终以医院当日公布为准。</p>");
document.writeln("                        <p>网友 、医生言论仅代表其个人观点，不代表本站同意其说法。</p>");
document.writeln("                </div>");
document.writeln("                <div id=\"footerCode\" class=\"fr\">");
document.writeln("                        <div class=\"img\"><img src=\"images/footer_twoCode.png\"></div>");
document.writeln("                        <p>扫描最新优惠</p>");
document.writeln("                        <p>手机随时咨询</p>");
document.writeln("                </div>");
document.writeln("        </div>");
document.writeln("        <div id=\"footerCopy\">");
document.writeln("        	<p>沪卫（中医）网复审[2014]第10125号 沪ICP备13034821号</p>");
document.writeln("        	<p>Copyright (C) 2009 Jiangcheng Dermatology Hospital shanghai.</p>");
document.writeln("        </div>");
document.writeln("</div>");
document.writeln("<script>");
document.writeln("/*footerSlide*/");
document.writeln("$(function(){");
document.writeln("	var aBtn=$(\'#footerSlide ol li\');");
document.writeln("	var aCut=$(\'#footerSlide div\');");
document.writeln("	tabSwitch(aBtn,aCut);	");
document.writeln("})");
document.writeln("/*footerTab ol li*/");
document.writeln("$(function(){");
document.writeln("	var aBtn=$(\'#footerTab ol li\');");
document.writeln("	var aCut=$(\'#footerTab ul\');");
document.writeln("	tabSwitch(aBtn,aCut);	");
document.writeln("})");
document.writeln("/*footerTab ul[0] li*/");
document.writeln("$(function(){");
document.writeln("	var aBtn=$(\'#footerTab ul\')[0].getElementsByTagName(\'li\');");
document.writeln("	tabSwitch(aBtn);	");
document.writeln("})");
document.writeln("/*footerTab ul[1] li*/");
document.writeln("$(function(){");
document.writeln("	var aBtn=$(\'#footerTab ul\')[1].getElementsByTagName(\'li\');");
document.writeln("	tabSwitch(aBtn);	");
document.writeln("})");
document.writeln("/*footerNav*/");
document.writeln("$(function(){");
document.writeln("	var aBtn=$(\'#footerNav li\');");
document.writeln("	tabSwitch(aBtn);	");
document.writeln("})");
document.writeln("</script>");