// JavaScript Document
//评价打印
//2014年1月14日 10:35:33
document.writeln("<style>.fl{ float:left}");
document.writeln("/*弹出*/");
document.writeln(".box_163css{ width: 480px;margin:20px auto; height: 30px;}");
document.writeln(".s_name{ float:left; display: block; width: 80px; padding-top: 4px; text-align: right;}");
document.writeln(".s_result_square{padding: 4px 0 0 9px;  }");
document.writeln(".star_ul{background: url(http://www.skinjc.com/pingjia/star.png) no-repeat 0 -150px; width: 132px; z-index: 10; position: relative; height: 25px;}");
document.writeln(".star_ul li{ float: left;  margin-right:1px;width: 25px; height: 25px; }");
document.writeln(".star_ul li a{ display: block; height: 25px; position: absolute; left: 0; top: 0; text-indent: -999em;}");
document.writeln(".star_ul li .active-star{background: url(http://www.skinjc.comhttp://www.skinjc.com/pingjia/star.png) no-repeat;}");
document.writeln(".star_ul li .one-star{width: 25px;background-position:0 -120px; z-index: 50;}");
document.writeln(".star_ul li .two-star{width: 51px;background-position:0 -90px;z-index: 40;}");
document.writeln(".star_ul li .three-star{width:79px; background-position:0 -60px;z-index: 30;}");
document.writeln(".star_ul li .four-star{width:105px; background-position:0 -30px;z-index: 20;}");
document.writeln(".star_ul li .five-star{width:129px; margin-right: 0; background-position:0 0;z-index: 10;}");
document.writeln(".s_result{ padding: 6px 0 0 5px; }");
document.writeln("");
document.writeln(".square_ul{background: url(http://www.skinjc.com/pingjia/star.png) no-repeat 0 -151px; width: 146px; z-index: 10; position: relative; height: 26px;}");
document.writeln(".square_ul li{ float: left;  margin-right:1px;width: 25px; height: 26px; }");
document.writeln(".square_ul li a{ display: block; height: 26px; position: absolute; left: 0; top: 0; text-indent: -999em;}");
document.writeln(".square_ul li .active-square{background: url(http://www.skinjc.com/pingjia/star.png) no-repeat;}");
document.writeln(".square_ul li .square-1{width: 25px;background-position:0 -120px; z-index: 50;}");
document.writeln(".square_ul li .square-2{width: 51px;background-position:0 -90px;z-index: 40;}");
document.writeln(".square_ul li .square-3{width:76px; background-position:0 -60px;z-index: 30;}");
document.writeln(".square_ul li .square-4{width:104px; background-position:0 -30px;z-index: 20;}");
document.writeln(".square_ul li .square-5{width:130px; margin-right: 0; background-position:0 0;z-index: 10;}");
document.writeln("");
document.writeln(".square_ul1{background: url(http://www.skinjc.com/pingjia/star.png) no-repeat 0 -151px; width: 146px; z-index: 10; position: relative; height: 26px;}");
document.writeln(".square_u1l li{ float: left;  margin-right:1px;width: 25px; height: 26px; }");
document.writeln(".square_ul1 li a{ display: block; height: 26px; position: absolute; left: 0; top: 0; text-indent: -999em;}");
document.writeln(".square_ul1 li .active-square{background: url(http://www.skinjc.com/pingjia/star.png) no-repeat;}");
document.writeln(".square_ul1 li .square-1{width: 25px;background-position:0 -120px; z-index: 50;}");
document.writeln(".square_ul1 li .square-2{width: 51px;background-position:0 -90px;z-index: 40;}");
document.writeln(".square_ul1 li .square-3{width:76px; background-position:0 -60px;z-index: 30;}");
document.writeln(".square_ul1 li .square-4{width:104px; background-position:0 -30px;z-index: 20;}");
document.writeln(".square_ul1 li .square-5{width:130px; margin-right: 0; background-position:0 0;z-index: 10;}");
document.writeln("");
document.writeln("");
document.writeln(".square_ul2{background: url(http://www.skinjc.com/pingjia/star.png) no-repeat 0 -151px; width: 146px; z-index: 10; position: relative; height: 26px;}");
document.writeln(".square_ul2 li{ float: left;  margin-right:1px;width: 25px; height: 26px; }");
document.writeln(".square_ul2 li a{ display: block; height: 26px; position: absolute; left: 0; top: 0; text-indent: -999em;}");
document.writeln(".square_ul2 li .active-square{background: url(http://www.skinjc.com/pingjia/star.png) no-repeat;}");
document.writeln(".square_ul2 li .square-1{width: 25px;background-position:0 -120px; z-index: 50;}");
document.writeln(".square_ul2 li .square-2{width: 51px;background-position:0 -90px;z-index: 40;}");
document.writeln(".square_ul2 li .square-3{width:76px; background-position:0 -60px;z-index: 30;}");
document.writeln(".square_ul2 li .square-4{width:104px; background-position:0 -30px;z-index: 20;}");
document.writeln(".square_ul2 li .square-5{width:130px; margin-right: 0; background-position:0 0;z-index: 10;}");
document.writeln("");
document.writeln(" .black_overlay{  display: none;   position:fixed; top: 0%;  left: 0%; _position:fixed; _top: 0%;   _left: 0%;  width: 100%;  height: 100%;  background-color: black;   z-index:1001;  -moz-opacity: 0.8;  opacity:.80;  filter: alpha(opacity=88);   } ");
document.writeln(" .white_content {  display: none; _position:fixed;  _top: 10%;   _left: 25%;  position:fixed;  top: 10%;  left: 25%;   width: 547px;  height:445px;  padding: 20px;  background-color: white;  z-index:1002;  overflow: auto;   } ");
document.writeln(" .white_content  p{ line-height:200% }");
document.writeln("");
document.writeln("/* 评论*/");
document.writeln("");
document.writeln("#hospital-evaluate-summary {  color: #666666; padding: 0 24px 20px;}");
document.writeln("#hospital-evaluate-summary dd {display: inline-block;margin-right: 10px;}");
document.writeln("#hospital-evaluate-summary span, #hospital-evaluate-summary label {  display: inline-block; height: 20px;line-height: 20px;}");
document.writeln("");
document.writeln("#hospital-evaluate-summary .zx-num { font-size: 18px;}");
document.writeln("#hospital-evaluate-summary span, #hospital-evaluate-summary label { display: inline-block;height: 20px;line-height: 20px;}");
document.writeln(".zx-num {  color: #FDAE22;font-family: arial; font-weight: 700;}");
document.writeln("#hospital-evaluate-summary .comment { background: none repeat scroll 0 0 #42B3E5;   color: #FFFFFF;display: inline-block;height: 26px; line-height: 26px;margin-left: 10px;                                 text-align: center; text-decoration: none; width: 72px;}");
document.writeln("#hospital-evaluate-summary .comment:hover {background: none repeat scroll 0 0 #7AD6FF;}");
document.writeln("");
document.writeln("");
document.writeln(".box07_bg { float: left;}");
document.writeln(".box07_bglf_kj { float: left; margin-right: 15px; overflow: hidden;}");
document.writeln(".box07_bglf { border-bottom: 1px dashed #000000; float: left; font-size: 12px; margin-left: 10px;  padding-bottom: 10px; }");
document.writeln(".box07_bglf p { float: left;  margin: 20px 0 10px; width: 100%;}");
document.writeln(".box07_bglf p i {  float: left; line-height: 23px;}");
document.writeln(".box07_bglf span i { float: left; line-height: 2em; padding-right: 20px;}");
document.writeln(".box07_bglf span em {  display: block; float: left; font-size: 12px;line-height: 2em; width: 540px;}");
document.writeln(".box07_bgrg {   background: none repeat scroll 0 0 #EEEEEE;  float: right;   height: 599px; margin: 1px; text-align: center;}");
document.writeln(".box07_bgrg p {  color: #3C3C3C; font-weight: bolder; line-height: 3em;}");
document.writeln(".box07_bgrg p em { color: #FFA902; font-size: 18px;}");
document.writeln(".box07_bgrg span { display: block; padding-top: 30px;}");
document.writeln("/*鍒嗛〉*/");
document.writeln("#page_navigation, #page_navigation1 { clear: both;padding: 20px 0 ;text-align:center;margin: 0 auto;}");
document.writeln(".page_link, .page_link1 { background: none repeat scroll 0 0 #F4F4F4; border: 1px solid #999999;cursor: pointer; display: inline;  float: left;height: 30px;");
document.writeln("    line-height: 30px; margin: 0 5px;  text-align: center; width: 30px;}");
document.writeln(".previous_link, .next_link, .previous_link1, .next_link1 { background: none repeat scroll 0 0 #F4F4F4;border: 1px solid #999999; cursor: pointer; display: block;  float: left;  height: 30px;line-height: 32px; text-align: center; width: 90px;}");
document.writeln("#page_navigation a{  border: 1px solid #CCCCCC; margin-left: 5px; padding: 10px;font-size: 14px}");
document.writeln(".active_page, .active_page1 {  background: none repeat scroll 0 0 #3399FF;}");
document.writeln("/*分页*/");
document.writeln("#page_navigation, #page_navigation1 { clear: both;padding: 20px 0 ;text-align:center;margin: 0 auto;}");
document.writeln(".page_link, .page_link1 { background: none repeat scroll 0 0 #F4F4F4; border: 1px solid #999999;cursor: pointer; display: inline;  float: left;height: 30px;");
document.writeln("    line-height: 30px; margin: 0 5px;  text-align: center; width: 30px;}");
document.writeln(".previous_link, .next_link, .previous_link1, .next_link1 { background: none repeat scroll 0 0 #F4F4F4;border: 1px solid #999999; cursor: pointer; display: block;  float: left;  height: 30px;line-height: 32px; text-align: center; width: 90px;}");
document.writeln("#page_navigation a{  border: 1px solid #CCCCCC; margin-left: 5px; padding: 10px;font-size: 14px}");
document.writeln(".active_page, .active_page1 {  background: none repeat scroll 0 0 #3399FF;}");
document.writeln("");
document.writeln("</style>");
document.writeln("<script type=\"text/javascript\">");
document.writeln("	$(function(){");
document.writeln("		//$(\'.star_ul a\').click(function(){$(\'.star_ul a\').removeClass(\"active-star\");$(this).addClass(\'active-star\');$(\'.s_result\').css(\'color\',\'#c00\').html($(this).attr(\'title\'))},function(){$(this).removeClass(\'active-star\');$(\'.s_result\').css(\'color\',\'#333\').html(\'请打分\')});");
document.writeln("		$(\'.square_ul a\').click(function(){");
document.writeln("			$(\'.square_ul a\').removeClass(\"active-square\");");
document.writeln("			$(this).addClass(\'active-square\');");
document.writeln("			$(this).parents(\'.box_163css\').find(\'.s_result_square\').css(\'color\',\'#c00\').html($(this).attr(\'title\'));");
document.writeln("			");
document.writeln("			}");
document.writeln("		);");
document.writeln("		$(\'.square_ul1 a\').click(function(){");
document.writeln("			$(\'.square_ul1 a\').removeClass(\"active-square\");");
document.writeln("			$(this).addClass(\'active-square\');");
document.writeln("			$(this).parents(\'.box_163css\').find(\'.s_result_square\').css(\'color\',\'#c00\').html($(this).attr(\'title\'))");
document.writeln("		");
document.writeln("			}");
document.writeln("		);");
document.writeln("		$(\'.square_ul2 a\').click(function(){");
document.writeln("			$(\'.square_ul2 a\').removeClass(\"active-square\");");
document.writeln("			$(this).addClass(\'active-square\');");
document.writeln("			$(this).parents(\'.box_163css\').find(\'.s_result_square\').css(\'color\',\'#c00\').html($(this).attr(\'title\'))");
document.writeln("		");
document.writeln("			}");
document.writeln("		);");
document.writeln("		");
document.writeln("	})");
document.writeln("	function dian(){");
document.writeln("		$(\'#light\').show(); $(\'#fade\').show();");
document.writeln("		}");
document.writeln("	function guan(){	");
document.writeln("		$(\'#wenben\').val(\"\");		 $(\'#light\').hide();		 $(\'#fade\').hide();		 $(\'.square_ul a\').removeClass(\"active-square\");		 $(\'.square_ul1 a\').removeClass(\"active-square\");		 $(\'.square_ul2 a\').removeClass(\"active-square\");	");
document.writeln("			}");
document.writeln("	function guan2(){	");
document.writeln("		  alert(\"评论正在审核中...\");		  $(\'#wenben\').val(\"\");		  $(\'#light\').hide();		  $(\'#fade\').hide();		  $(\'.square_ul a\').removeClass(\"active-square\");		  $(\'.square_ul1 a\').removeClass(\"active-square\");		  $(\'.square_ul2 a\').removeClass(\"active-square\");	");
document.writeln("		  	}");
document.writeln("</script>");
document.writeln("<script>");
document.writeln("$().ready(function () {");
document.writeln("");
document.writeln("      var result = eval(\'(\'+dd_array+\')\');");
document.writeln("	  var html = \"\";");
document.writeln("	  var num = 0;");
document.writeln("	  for (var key in result)");
document.writeln("	  {");
document.writeln("		  ");
document.writeln("			html += \'<div class=\"box07_bglf\"><p>用户:\'+result[key][\'name\']+\'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;评分：<img src=\"http://www.skinjc.com/pingjia/wujx.png\" width=\"114\" height=\"20\" /><span style=\"float:right\">(<span style=\"margin-top:3px;\" id=\"ajax_\'+num+\'\">\'+result[key][\'num\']+\'</span>)<img style=\"cursor:pointer\" src=\"images/dmz.jpg\" width=\"23\" height=\"19\" onclick=\"ajax_num(\'+result[key][\'id\']+\', \'+num+\')\"/></span></p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style=\"width:900px;float:left;\">\'+result[key][\'content\']+\'</span></div>\';");
document.writeln("			num = num + 1;");
document.writeln("	  }");
document.writeln("	  $(\"#content\").html(html);");
document.writeln("");
document.writeln("});");
document.writeln("/* ");
document.writeln("  循环显示评论内容");
document.writeln("*/");
document.writeln("</script>");
document.writeln("<div class=\"scroll_top\" style=\"width:980px; margin:0 auto\">");
document.writeln("      ");
document.writeln("		<dl id=\"hospital-evaluate-summary\">");
document.writeln("                    <dd class=\"fl\">");
document.writeln("                        <label>总评：</label>");
document.writeln("                        <span class=\"zx-num\">★★★★★</span>");
document.writeln("                    </dd>");
document.writeln("                    <dd class=\"fl\">");
document.writeln("                        <label>服务满意度：</label><span class=\"zx-num\">4.9</span>");
document.writeln("                    </dd>");
document.writeln("                    <dd class=\"fl\">");
document.writeln("                        <label>环境满意度：</label><span class=\"zx-num\">4.9</span>");
document.writeln("                    </dd>");
document.writeln("                    <dd class=\"fl\">");
document.writeln("                        <label>疗效满意度：</label><span class=\"zx-num\">4.9</span>");
document.writeln("                    </dd>");
document.writeln("                    <dd class=\"fl\">");
document.writeln("                        <a class=\"comment\" href=\"javascript:void(0);\"  id=\"pinglun\" onclick=\"dian()\">我要评论</a>");
document.writeln("                       ");
document.writeln("                    </dd>");
document.writeln("         </dl>");
document.writeln("		 <input type=\'hidden\' id=\'current_page\' /> ");
document.writeln("                    <input type=\'hidden\' id=\'show_per_page\' /> ");
document.writeln("                    <div id=\"content\"></div>");
document.writeln("                    <div id=\'page_navigation\'></div>");
document.writeln("              <div id=\"pp_num\" style=\"display:none\"></div> ");
document.writeln("                    ");
document.writeln("                  <div style=\"clear:both\"></div>");
document.writeln("		 ");
document.writeln("			");
document.writeln("	</div>");
document.writeln("<div style=\" position:fixed; z-index:2147483647\">");
document.writeln("<div id=\"light\" class=\"white_content\">");
document.writeln("    <div style=\"border-bottom:1px #999 solid; height:25px\"> ");
document.writeln("                <b style=\"float:left\">发表评论</b>");
document.writeln("                 <span style=\" color:#F00; float:right; border:1px solid #F00; padding:0 5px; cursor:pointer;\"  onclick = \"guan()\" >X</span>");
document.writeln("  </div>             ");
document.writeln("    <form id=\"form1\" name=\"form1\" method=\"post\" action=\"\" title=\"\">");
document.writeln("                    ");
document.writeln("      <p>");
document.writeln("                       总体评价：");
document.writeln("        <label>");
document.writeln("                          <input type=\"radio\" name=\"RadioGroup1\" value=\"好评\" id=\"RadioGroup1_0\" checked=\"checked\" />");
document.writeln("                          好评</label>");
document.writeln("                       ");
document.writeln("                        <label>");
document.writeln("                          <input type=\"radio\" name=\"RadioGroup1\" value=\" 中评\" id=\"RadioGroup1_1\" />");
document.writeln("                          中评</label>");
document.writeln("                        ");
document.writeln("                        <label>");
document.writeln("                          <input type=\"radio\" name=\"RadioGroup1\" value=\"差评\" id=\"RadioGroup1_2\" />");
document.writeln("                         差评</label>");
document.writeln("                      ");
document.writeln("      </p>");
document.writeln("    </form> ");
document.writeln("    <div class=\"box_163css\">");
document.writeln("        <span class=\"s_name\">服务满意度：</span>");
document.writeln("        <ul class=\"square_ul fl\">");
document.writeln("            <li><a class=\"square-1\" title=\"差\" href=\"javascript:void(0);\"></a></li>");
document.writeln("            <li><a class=\"square-2\" title=\"一般\" href=\"javascript:void(0);\"></a></li>");
document.writeln("            <li><a class=\"square-3\" title=\"好\" href=\"javascript:void(0);\"></a></li>");
document.writeln("            <li><a class=\"square-4\" title=\"很好\" href=\"javascript:void(0);\"></a></li>");
document.writeln("            <li><a class=\"square-5\" title=\"非常好\" href=\"javascript:void(0);\"></a></li>");
document.writeln("        </ul>");
document.writeln("        <span class=\"s_result_square fl\">请打分</span>");
document.writeln("    </div>");
document.writeln("    <div class=\"box_163css\">");
document.writeln("        <span class=\"s_name\">环境满意度：</span>");
document.writeln("        <ul class=\"square_ul1 fl\">");
document.writeln("            <li><a class=\"square-1\" title=\"差\" href=\"javascript:void(0);\"></a></li>");
document.writeln("            <li><a class=\"square-2\" title=\"一般\" href=\"javascript:void(0);\"></a></li>");
document.writeln("            <li><a class=\"square-3\" title=\"好\" href=\"javascript:void(0);\"></a></li>");
document.writeln("            <li><a class=\"square-4\" title=\"很好\" href=\"javascript:void(0);\"></a></li>");
document.writeln("            <li><a class=\"square-5\" title=\"非常好\" href=\"javascript:void(0);\"></a></li>");
document.writeln("        </ul>");
document.writeln("        <span class=\"s_result_square fl\">请打分</span>");
document.writeln("    </div>");
document.writeln("    <div class=\"box_163css\">");
document.writeln("        <span class=\"s_name\">医生满意度：</span>");
document.writeln("        <ul class=\"square_ul2 fl\">");
document.writeln("            <li><a class=\"square-1\" title=\"差\" href=\"javascript:void(0);\"></a></li>");
document.writeln("            <li><a class=\"square-2\" title=\"一般\" href=\"javascript:void(0);\"></a></li>");
document.writeln("            <li><a class=\"square-3\" title=\"好\" href=\"javascript:void(0);\"></a></li>");
document.writeln("            <li><a class=\"square-4\" title=\"很好\" href=\"javascript:void(0);\"></a></li>");
document.writeln("            <li><a class=\"square-5\" title=\"非常好\" href=\"javascript:void(0);\"></a></li>");
document.writeln("        </ul>");
document.writeln("        <span class=\"s_result_square fl\">请打分</span>");
document.writeln("    </div>           ");
document.writeln("    <div> <textarea id=\"wenben\" style=\"border: 1px solid rgb(153, 153, 153); width: 547px; height: 151px;\" name=\"\" ></textarea></div>");
document.writeln("        <div style=\"float:right; width:150px; height:25px; margin:10px 0 0 0 \" >");
document.writeln("            <input style=\"width:75px; height:30px; background:#d01c00; cursor:pointer; color:#fff\" name=\"\" type=\"button\" value=\"提交评论\" onclick=\"guan2()\" /> ");
document.writeln("            <input style=\"background:#fff; cursor:pointer;\"  name=\"\" type=\"button\"  value=\"取消\" onclick=\"guan()\"/>");
document.writeln("          </div>");
document.writeln("</div> ");
document.writeln("  <div id=\"fade\" class=\"black_overlay\"></div> ");
document.writeln("</div>");