// JavaScript Document
document.writeln("<style type=\"text/css\">");
document.writeln("/* focusindex */");
document.writeln("#focusindex{height:500px; overflow: hidden; position: relative; }");
document.writeln("#focusindex li{ height: 500px; overflow: hidden; position: absolute; width: 100%; }");
document.writeln("#focusindex .btn{position:absolute;width:200px;height:30px;bottom:0;text-align:center;z-index:9;left:600px;}");
document.writeln("#focusindex .btn span{display:inline-block;_display:inline;_zoom:1;width:14px;height:14px;_font-size:0;margin:5px 10px;cursor:pointer;background:#dfdfdf;z-index:9; border-radius:50%}");
document.writeln("#focusindex .btn span.on{background:#3399ff;z-index:9}");
document.writeln("#focusindex .preNext{width:44px;height:44px;position:absolute;top:230px;background:url(http://www.skinjc.com/img_new/sprite.png) no-repeat left bottom;cursor:pointer;z-index:9; opacity:0;transition: all 0.3s linear 0s;}");
document.writeln("#focusindex .pre{left:0%; z-index:9}");
document.writeln("#focusindex .next{right:0%;background-position:right bottom;z-index:9}");
document.writeln("#focusindex:hover .preNext{opacity:0.5;} ");
document.writeln("#focusindex:hover .pre{left:10%; } ");
document.writeln("#focusindex:hover .next{right:10%;} ");
document.writeln("#focusindex .pre:hover,#focusindex .next:hover{opacity:1;}");
document.writeln("#focusindex div{ height:100%;} ");
document.writeln("#focusindex a { display:block; width:100%; height:100%;}");
document.writeln(".banner1{ background: url(images/banner1.jpg) no-repeat center;z-index: 1;}");
document.writeln(".banner2{ background: url(images/banner2.jpg) no-repeat center;z-index: 1;}");
document.writeln(".banner3{ background: url(images/banner3.jpg) no-repeat center;z-index: 1;}");
document.writeln("</style>");
document.writeln("<div id=\"focusindex\">");
document.writeln("");
document.writeln("      <ul class=\"index_banner_box\">");
document.writeln("");
document.writeln("        <li class=\"banner1\"><div class=\"w995\" style=\"position:relative;\"><a target=\"_blank\" href=\"javascript:void(0);return false;\" onclick=\"openZoosUrl();return false;\"></a></div></li>");
document.writeln("        <li class=\"banner2\"><div class=\"w995\" style=\"position:relative;\"><a target=\"_blank\" href=\"/yiyuanjians/201209241637.html\"></a></div></li>");
document.writeln("        <li class=\"banner3\"><div class=\"w995\" style=\"position:relative;\"><a target=\"_blank\" href=\"/yiyuanjians/201409302770.html\"></a></div></li>");
document.writeln("      </ul>");
document.writeln("");
document.writeln("    </div>");
document.writeln("<script>");
document.writeln("");
document.writeln(" $(function() {");
document.writeln("");
document.writeln("	//var sWidth = $(\"#focusindex\").width(); //获取焦点图的宽度（显示面积）");
document.writeln("");
document.writeln("	var len = $(\"#focusindex ul li\").length; //获取焦点图个数");
document.writeln("");
document.writeln("	var index = 0;");
document.writeln("");
document.writeln("	var picTimer;");
document.writeln("");
document.writeln("	");
document.writeln("");
document.writeln("	//以下代码添加数字按钮和按钮后的半透明条，还有上一页、下一页两个按钮");
document.writeln("");
document.writeln("	var btn = \"<div class=\'btn\'>\";");
document.writeln("");
document.writeln("	for(var i=0; i < len; i++) {");
document.writeln("");
document.writeln("		btn += \"<span></span>\";");
document.writeln("");
document.writeln("	}");
document.writeln("");
document.writeln("	btn += \"</div><div class=\'preNext pre\'></div><div class=\'preNext next\'></div>\";");
document.writeln("");
document.writeln("	$(\"#focusindex\").append(btn);");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("	//为小按钮添加鼠标滑入事件，以显示相应的内容");
document.writeln("");
document.writeln("	$(\"#focusindex .btn span\").css(\"opacity\",1).mouseover(function() {");
document.writeln("");
document.writeln("		index = $(\"#focusindex .btn span\").index(this);");
document.writeln("");
document.writeln("		showPics(index);");
document.writeln("");
document.writeln("	}).eq(0).trigger(\"mouseover\");");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("	//上一页、下一页按钮透明度处理");
document.writeln("");
document.writeln("/*	$(\"#focusindex\").hover(function() {");
document.writeln("");
document.writeln("		$(\"#focusindex .pre\").animate({\"left\":\"10%\",\"opacity\":\"1\"},300);");
document.writeln("");
document.writeln("		$(\"#focusindex .next\").animate({\"right\":\"10%\",\"opacity\":\"1\"},300);");
document.writeln("");
document.writeln("	},function() {");
document.writeln("");
document.writeln("		$(\"#focusindex .pre\").animate({\"left\":\"0%\",\"opacity\":\"0\"},300);");
document.writeln("");
document.writeln("		$(\"#focusindex .next\").animate({\"right\":\"0%\",\"opacity\":\"0\"},300);");
document.writeln("");
document.writeln("	});*/");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("	//上一页按钮");
document.writeln("");
document.writeln("	$(\"#focusindex .pre\").click(function() {");
document.writeln("");
document.writeln("		index -= 1;");
document.writeln("");
document.writeln("		if(index == -1) {index = len - 1;}");
document.writeln("");
document.writeln("		showPics(index);");
document.writeln("");
document.writeln("	});");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("	//下一页按钮");
document.writeln("");
document.writeln("	$(\"#focusindex .next\").click(function() {");
document.writeln("");
document.writeln("		index += 1;");
document.writeln("");
document.writeln("		if(index == len) {index = 0;}");
document.writeln("");
document.writeln("		showPics(index);");
document.writeln("");
document.writeln("	});");
document.writeln("");
document.writeln("	");
document.writeln("");
document.writeln("	//IPAI");
document.writeln("");
document.writeln("	$(\"#focusindex\").on(\"swipeleft\",function(){");
document.writeln("");
document.writeln("		index -= 1;");
document.writeln("");
document.writeln("		if(index == -1) {index = len - 1;}");
document.writeln("");
document.writeln("		showPics(index);");
document.writeln("");
document.writeln("	});");
document.writeln("");
document.writeln("$(\"#focusindex\").on(\"swiperight\",function(){");
document.writeln("");
document.writeln("		index += 1;");
document.writeln("");
document.writeln("		if(index == len) {index = 0;}");
document.writeln("");
document.writeln("		showPics(index);");
document.writeln("");
document.writeln("	});");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("	//本例为左右滚动，即所有li元素都是在同一排向左浮动，所以这里需要计算出外围ul元素的宽度");
document.writeln("");
document.writeln("	//$(\"#focusindex ul\").css(\"width\",sWidth * (len));");
document.writeln("");
document.writeln("	");
document.writeln("");
document.writeln("	//鼠标滑上焦点图时停止自动播放，滑出时开始自动播放");
document.writeln("");
document.writeln("	$(\"#focusindex\").hover(function() {");
document.writeln("");
document.writeln("		clearInterval(picTimer);");
document.writeln("");
document.writeln("	},function() {");
document.writeln("");
document.writeln("		picTimer = setInterval(function() {");
document.writeln("");
document.writeln("			showPics(index);");
document.writeln("");
document.writeln("			index++;");
document.writeln("");
document.writeln("			if(index == len) {index = 0;}");
document.writeln("");
document.writeln("		},4000); //此4000代表自动播放的间隔，单位：毫秒");
document.writeln("");
document.writeln("	}).trigger(\"mouseleave\");");
document.writeln("");
document.writeln("	");
document.writeln("");
document.writeln("	//显示图片函数，根据接收的index值显示相应的内容");
document.writeln("");
document.writeln("	function showPics(index) { //普通切换");
document.writeln("");
document.writeln("		//var nowLeft = -index*sWidth; //根据index值计算ul元素的left值");
document.writeln("");
document.writeln("		//$(\"#focusindex ul\").stop(true,false).animate({\"left\":nowLeft},300); //通过animate()调整ul元素滚动到计算出的position");
document.writeln("");
document.writeln("		//$(\"#focusindex .btn span\").removeClass(\"on\").eq(index).addClass(\"on\"); //为当前的按钮切换到选中的效果");
document.writeln("");
document.writeln("		$(\"#focusindex .btn span\").stop(true,false).removeClass(\"on\").eq(index).stop(true,false).addClass(\"on\"); //为当前的按钮切换到选中的效果");
document.writeln("");
document.writeln("		$(\"#focusindex ul li\").stop(true,false).animate({\"opacity\":\"0\"},300).css(\"z-index\",0).removeClass(\"bannerdh\").eq(index).stop(true,false).animate({\"opacity\":\"1\"},300).addClass(\"bannerdh\").css(\"z-index\",1); //为当前的按钮切换到选中的效果");
document.writeln("");
document.writeln("	}");
document.writeln("");
document.writeln("});");
document.writeln("");
document.writeln("</script>");
/*document.writeln("<script language=\"javascript\">");
document.writeln("		banner_focus();");
document.writeln("		$(function(){");
document.writeln("			window.onscroll=banner_focus;");
document.writeln("			window.onresize=banner_focus;");
document.writeln("		});");
document.writeln("	</script>");*/