// JavaScript Document
document.writeln("<style>");
document.writeln("/*reason*/");
document.writeln(".reason ol{ padding:0 80px; border-bottom:1px solid #d8d8d8; margin-bottom:25px;}");
document.writeln(".reason ol li{ color:#333333; float:left; text-align:center; background:#d8d8d8; font-size:18px; width:120px; margin-right:24px; height:34px; line-height:34px;}");
document.writeln(".reason ol li.active{ background:#006db8; color:#fff;}");
document.writeln(".reason ul{ height:284px;}");
document.writeln(".reason ul li{ height:284px; transition:all 0s; -webkit-transition:all 0s; -moz-transition:all 0s; -o-transition:all 0s; display:none; position:relative;}");
document.writeln(".reason ul li.active{ display:block;}");
document.writeln(".reason ul li .img{ padding:2px; border:1px solid #d8d8d8; margin-left:30px;}");
document.writeln(".reason ul li .txt{ width:560px; margin-right:30px;}");
document.writeln(".reason ul li a{ position:absolute; right:0; bottom:0;}");
document.writeln(".reason ul li h2{ font-size:24px; color:#006db8; margin-bottom:10px;}");
document.writeln(".reason ul li p{ font-size:14px; color:#555555; line-height:24px;}");
document.writeln(".reason ul li em{ font-size:14px; color:#006db8;}");
document.writeln(".reason ul li h3{ line-height:30px; color:#006db8; font-size:14px; text-align:center;}");
document.writeln("</style>");
document.writeln("<div class=\"reason w1000\">");
document.writeln("        <ol class=\"hd clearFix\">");
document.writeln("                <li class=\"active\">遗传因素</li>");
document.writeln("                <li>免疫因素</li>");
document.writeln("                <li>内分泌因素</li>");
document.writeln("                <li>精神因素</li>");
document.writeln("                <li>遗传因素</li>");
document.writeln("                <li style=\"margin-right:0;\">环境因素</li>");
document.writeln("        </ol>");
document.writeln("        <ul class=\"bd\">");
document.writeln("        	<li class=\"active clearFix\">");
document.writeln("                	<div class=\"img fl\"><img src=\"/zt/xcxyxb/images/reason1.jpg\" /></div>");
document.writeln("                	<div class=\"txt fr\">");
document.writeln("                        	<h2>遗传因素</h2>");
document.writeln("                                <p><em>引发原因：</em>是遗传因素与环境因素等多种因素相互作用的多基因遗传病。一般认为有家族史者约占30%</p>");
document.writeln("                                <p><em>是否传染：</em>遗传性因素引起的牛皮癣不会传染</p>");
document.writeln("                        </div>");
document.writeln("                        <a href=\"javascript:void(0);return false;\" onclick=\"openZoosUrl();return false;\">");
document.writeln("                        	<h3>遗传性牛皮癣该怎么治疗?</h3>");
document.writeln("                        	<img src=\"/zt/xcxyxb/images/reason_btn.jpg\">");
document.writeln("                        </a>");
document.writeln("                </li>");
document.writeln("        	<li class=\"clearFix\">");
document.writeln("                	<div class=\"img fl\"><img src=\"/zt/xcxyxb/images/reason2.jpg\" /></div>");
document.writeln("                	<div class=\"txt fr\">");
document.writeln("                        	<h2>免疫因素</h2>");
document.writeln("                                <p><em>引发原因：</em>大量研究证明银屑病是免疫介导的炎症性皮肤病，其发病与炎症细胞浸润和炎症因子有关.</p>");
document.writeln("                                <p><em>是否传染：</em>免疫因素引起的牛皮癣不会传染</p>");
document.writeln("                        </div>");
document.writeln("                        <a href=\"javascript:void(0);return false;\" onclick=\"openZoosUrl();return false;\">");
document.writeln("                        	<h3>遗传性牛皮癣该怎么治疗?</h3>");
document.writeln("                        	<img src=\"/zt/xcxyxb/images/reason_btn.jpg\">");
document.writeln("                        </a>");
document.writeln("                </li>");
document.writeln("        	<li class=\"clearFix\">");
document.writeln("                	<div class=\"img fl\"><img src=\"/zt/xcxyxb/images/reason3.jpg\" /></div>");
document.writeln("                	<div class=\"txt fr\">");
document.writeln("                        	<h2>内分泌因素</h2>");
document.writeln("                                <p><em>引发原因：</em>妊娠可使皮损消失或减轻，也可使皮损加重。甲状腺疾病、糖尿病等内分泌疾病对该病的影响不明显。</p>");
document.writeln("                                <p><em>是否传染：</em>内分泌因素引起的牛皮癣不会传染</p>");
document.writeln("                        </div>");
document.writeln("                        <a href=\"javascript:void(0);return false;\" onclick=\"openZoosUrl();return false;\">");
document.writeln("                        	<h3>遗传性牛皮癣该怎么治疗?</h3>");
document.writeln("                        	<img src=\"/zt/xcxyxb/images/reason_btn.jpg\">");
document.writeln("                        </a>");
document.writeln("                </li>");
document.writeln("        	<li class=\"clearFix\">");
document.writeln("                	<div class=\"img fl\"><img src=\"/zt/xcxyxb/images/reason4.jpg\" /></div>");
document.writeln("                	<div class=\"txt fr\">");
document.writeln("                        	<h2>精神因素</h2>");
document.writeln("                                <p><em>引发原因：</em>患者可以出现神经精神改变，且这些改变可以加重已有皮损。</p>");
document.writeln("                                <p><em>是否传染：</em>精神因素引起的牛皮癣不会传染</p>");
document.writeln("                        </div>");
document.writeln("                        <a href=\"javascript:void(0);return false;\" onclick=\"openZoosUrl();return false;\">");
document.writeln("                        	<h3>遗传性牛皮癣该怎么治疗?</h3>");
document.writeln("                        	<img src=\"/zt/xcxyxb/images/reason_btn.jpg\">");
document.writeln("                        </a>");
document.writeln("                </li>");
document.writeln("        	<li class=\"clearFix\">");
document.writeln("                	<div class=\"img fl\"><img src=\"/zt/xcxyxb/images/reason5.jpg\" /></div>");
document.writeln("                	<div class=\"txt fr\">");
document.writeln("                        	<h2>感染因素</h2>");
document.writeln("                                <p><em>引发原因：</em>研究证实链球菌感染、金黄色葡萄球菌感染、真菌感染与银屑病的发病有关，病毒感染与银屑病发病是否相关尚未明确。</p>");
document.writeln("                                <p><em>是否传染：</em>感染因素引起的牛皮癣不会传染</p>");
document.writeln("                        </div>");
document.writeln("                        <a href=\"javascript:void(0);return false;\" onclick=\"openZoosUrl();return false;\">");
document.writeln("                        	<h3>遗传性牛皮癣该怎么治疗?</h3>");
document.writeln("                        	<img src=\"/zt/xcxyxb/images/reason_btn.jpg\">");
document.writeln("                        </a>");
document.writeln("                </li>");
document.writeln("        	<li class=\"clearFix\">");
document.writeln("                	<div class=\"img fl\"><img src=\"/zt/xcxyxb/images/reason6.jpg\" /></div>");
document.writeln("                	<div class=\"txt fr\">");
document.writeln("                        	<h2>生活习惯、药物因素、环境因素</h2>");
document.writeln("                                <p><em>引发原因：</em>研究发现受潮、感染、饮酒、服药及精神紧张是诱发银屑病的主要危险因素。可能诱发或加重银屑病的药物有β1受体阻滞剂、非甾体抗炎药、锂盐、抗疟药、四环素、钙通道阻滞剂、二甲双胍、干扰素α等。环境因素与发病年龄有关，且季节、气候在银屑病的发病和复发方面有影响。</p>");
document.writeln("                                <p><em>是否传染：</em>生活环境因素引起的牛皮癣不会传染</p>");
document.writeln("                        </div>");
document.writeln("                        <a href=\"javascript:void(0);return false;\" onclick=\"openZoosUrl();return false;\">");
document.writeln("                        	<h3>遗传性牛皮癣该怎么治疗?</h3>");
document.writeln("                        	<img src=\"/zt/xcxyxb/images/reason_btn.jpg\">");
document.writeln("                        </a>");
document.writeln("                </li>");
document.writeln("        </ul>");
document.writeln("</div>");
document.writeln("<script>");
document.writeln("/*reason*/");
document.writeln("$(function(){");
document.writeln("	var aBtn=$(\'.reason ol li\');");
document.writeln("	var aCut=$(\'.reason ul li\');");
document.writeln("	tabSwitch(aBtn,aCut);");
document.writeln("})");
document.writeln("</script>");