// JavaScript Document
document.writeln("<style>");
document.writeln("/*report*/");
document.writeln(".report ol{ padding:0 105px; border-bottom:1px solid #d8d8d8; margin-bottom:25px;}");
document.writeln(".report ol li{ color:#333333; float:left; text-align:center; background:#d8d8d8; font-size:18px; padding:0 10px; margin-right:24px; height:34px; line-height:34px;}");
document.writeln(".report ol li.active{ background:#006db8; color:#fff;}");
document.writeln(".report ul li{ transition:all 0s; -webkit-transition:all 0s; -moz-transition:all 0s; -o-transition:all 0s; display:none; position:relative;}");
document.writeln(".report ul li.active{ display:block;}");
document.writeln(".report ul li .vedio{ width:330px; height:270px; margin-left:40px; background:#000;}");
document.writeln(".report ul li .txt{ width:580px; height:270px; margin-right:40px; position:relative;}");
document.writeln(".report ul li .txt img{ position:absolute; left:0; bottom:0;}");
document.writeln(".report ul li .txt p{ font-size:12px; color:#555555; text-indent:28px; line-height:24px;}");
document.writeln("</style>");
document.writeln("<div class=\"report w1000\">");
document.writeln("	<ol class=\"clearFix hd\">");
document.writeln("        	<li class=\"active\">穿山甲宝宝</li>");
document.writeln("        	<li>东方明珠成果展</li>");
document.writeln("        	<li>东方明珠第二届成果展</li>");
document.writeln("        	<li>世界银屑病日</li>");
document.writeln("        	<li style=\"margin-right:0;\">腾讯网专访 </li>");
document.writeln("        </ol>");
document.writeln("        <ul class=\"bd\">");
document.writeln("        	<li class=\"active clearFix\">");
document.writeln("                	<div class=\"vedio fl\"><script language=\'javascript\' src=\'http://www.5etv.com/video/v2_player_html5.jsp?vid=146224450&s=www.5etv.com&width=330&height=270&soValue=100&playMode=0&toolzt=yes&startzt=no\'></script></div>");
document.writeln("                	<div class=\"txt fr\">");
document.writeln("                        	<p>怪病男孩全身麟 爱心救助得康复</p>");
document.writeln("                        	<p>银屑病不知道大家听说过没有，这个呢应该是医学上的学名，这要说牛皮癣大家就都知道了。牛皮癣啊，很顽固很痛苦，但这还算一般的，某些特殊的类型，就更严重了。最近啊，网上大家在转发一个穿山甲宝宝求医治病的事，小男孩呢叫荀绍一，为什么说穿山甲呢？身上像是黑色的鳞片。</p>");
document.writeln("                                <img src=\"/zt/xcxyxb/images/report_s1.jpg\" />");
document.writeln("                        </div>");
document.writeln("                </li>");
document.writeln("        	<li class=\"clearFix\">");
document.writeln("                	<div class=\"vedio fl\"><script language=\'javascript\' src=\'http://www.5etv.com/video/v2_player_html5.jsp?vid=74305603&s=www.5etv.com&width=330&height=270&soValue=100&playMode=0&toolzt=yes&startzt=no\'></script></div>");
document.writeln("                	<div class=\"txt fr\">");
document.writeln("                        	<p> 据不完全估计，全世界约有1.25亿人受到银屑病的困扰，并且发病率以每年 5% 幅度增长，成为 10 年来发病率增速最快的疾病。这种疾病是一种严重的遗传疾病，虽然没有传染性，但对于该病的患者却造成了身心双重负担，成为严重威胁人们健康的疾病。</p>");
document.writeln("                                <p>今年10月29日的\"世界银屑病日\"， 国际联合会银屑病协会，及各个支援团体进行的活动在世界各地举行，以提高人们对银屑病及其患者的正确认识，给予银屑病患者应有的重视和尊重。</p>");
document.writeln("                                <img src=\"/zt/xcxyxb/images/report_s2.jpg\" />");
document.writeln("                        </div>");
document.writeln("                </li>");
document.writeln("        	<li class=\"clearFix\">");
document.writeln("                	<div class=\"vedio fl\"><script language=\'javascript\' src=\'http://www.5etv.com/video/v2_player_html5.jsp?vid=156804292&s=www.5etv.com&width=330&height=270&soValue=100&playMode=0&toolzt=yes&startzt=no\'></script></div>");
document.writeln("                	<div class=\"txt fr\">");
document.writeln("                        	<p>新闻坊：第二届东方明珠皮肤病治疗成果展成功召开</p>");
document.writeln("                                <p>医者仁心，为了帮助患有重症皮肤病的困难家庭，上海江城皮肤病医院联合杨浦和泰爱心服务社定向捐赠200万元善款成立爱心援助基金，减轻重症皮肤病患者的生活负担帮助这些患者完成治疗和康复，近日首批20万元援助经费已经交到杨浦和泰爱心服务社手中</p>");
document.writeln("                                <img src=\"/zt/xcxyxb/images/report_s3.jpg\" />");
document.writeln("                        </div>");
document.writeln("                </li>");
document.writeln("        	<li class=\"clearFix\">");
document.writeln("                	<div class=\"vedio fl\"><script language=\'javascript\' src=\'http://www.5etv.com/video/v2_player_html5.jsp?vid=134330113&s=www.5etv.com&width=330&height=270&soValue=100&playMode=0&toolzt=yes&startzt=no\'></script></div>");
document.writeln("                	<div class=\"txt fr\">");
document.writeln("                                <p>以上海江城为代表的多家皮肤病专科医院意识到这一社会问题，首先面向全社会倡导拒绝歧视皮肤病人，并成立以顾昌林教授为带头人的专家组，专项研究、探索一 套完善的\"皮肤病患者社会干预体系\"。据相关负责人介绍，即日起将向全社会皮肤病患者开通社会干预热线400-699-1515，届时将有多家医疗、心理 咨询、慈善和公益志愿者机构联合为皮肤病患者提供医疗技术援助和社会帮助，在力求治愈生理疾病的同时，消除强加于他们身上的歧视和不公，帮助他们树立治疗 的信心和生活的勇气。</p>");
document.writeln("                                <img src=\"/zt/xcxyxb/images/report_s4.jpg\" />");
document.writeln("                        </div>");
document.writeln("                </li>");
document.writeln("        	<li class=\"clearFix\">");
document.writeln("                	<div class=\"vedio fl\"><script language=\'javascript\' src=\'http://www.5etv.com/video/v2_player_html5.jsp?vid=78322798&s=www.5etv.com&width=330&height=270&soValue=100&playMode=0&toolzt=yes&startzt=no\'></script></div>");
document.writeln("                	<div class=\"txt fr\">");
document.writeln("                        	<p>2010年10月15日，中国最大的中文门户网站--腾讯网，对上海江城皮肤病医院专家进行了采访。</p>");
document.writeln("                                <p>多年来，上海江城皮肤病医院发扬创新精神，大力挖掘祖国医学成就，并充分利用现代科技成果，形成了独特特色的中西医结合治疗皮肤病的有效疗法，在皮肤科专业建设上，以一流的专业水平、一流的医德医风、一流的医疗服务，打造了品牌、形成了特色，其影响辐射力已遍及全国及海外，在社会上获得了众多荣誉和良好的口碑。</p>");
document.writeln("                                <img src=\"/zt/xcxyxb/images/report_s5.jpg\" />");
document.writeln("                        </div>");
document.writeln("                </li>");
document.writeln("        </ul>");
document.writeln("</div>");
document.writeln("<script>");
document.writeln("/*team*/");
document.writeln("$(function(){");
document.writeln("	var aBtn=$(\'.report ol li\');");
document.writeln("	var aCut=$(\'.report ul li\');");
document.writeln("	tabSwitch(aBtn,aCut);");
document.writeln("})");
document.writeln("</script>");