// JavaScript Document
document.writeln("<style>");
document.writeln("/*about*/");
document.writeln(".about{ position:relative; background:#f4f4f4; padding:24px 0;}");
document.writeln(".about span{ position:absolute; top:52px;}");
document.writeln(".about .prev{ left:5px;}");
document.writeln(".about .next{ right:5px;}");
document.writeln(".about div{ height:108px; position:relative; width:938px; margin:0 auto; overflow:hidden;}");
document.writeln(".about ul{ position:absolute; left:0; top:0; width:3000px;}");
document.writeln(".about li{ float:left; margin-right:6px; padding:2px; border:1px solid #f8f8f8; background:#fff;}");
document.writeln(".about li img{ width:224px; height:102px; vertical-align:middle;}");
document.writeln("</style>");
document.writeln("<div class=\"about w1000\">");
document.writeln("	<span class=\"prev\"><img src=\"/zt/xcxyxb/images/prev.png\" /></span>");
document.writeln("	<span class=\"next\"><img src=\"/zt/xcxyxb/images/next.png\" /></span>");
document.writeln("        <div class=\"bd\">");
document.writeln("        	<ul class=\"clearFix\">");
document.writeln("                	<li><a href=\"/zt/guchanglin/\" target=\"_blank\"><img src=\"/zt/xcxyxb/images/about1.jpg\" /></a></li>");
document.writeln("                	<li><a href=\"/zt/Psoriasisday/\" target=\"_blank\"><img src=\"/zt/xcxyxb/images/about2.jpg\" /></a></li>");
document.writeln("                	<li><a href=\"/zt/guchanglin/\" target=\"_blank\"><img src=\"/zt/xcxyxb/images/about3.jpg\" /></a></li>");
document.writeln("                	<li><a href=\"/zt/Psoriasisday/\" target=\"_blank\"><img src=\"/zt/xcxyxb/images/about4.jpg\" /></a></li>");
document.writeln("                	<li><a href=\"/zt/Psoriasisday/\" target=\"_blank\"><img src=\"/zt/xcxyxb/images/about4.jpg\" /></a></li>");
document.writeln("                	<li><a href=\"/zt/Psoriasisday/\" target=\"_blank\"><img src=\"/zt/xcxyxb/images/about4.jpg\" /></a></li>");
document.writeln("                </ul>");
document.writeln("        </div>");
document.writeln("</div>");
document.writeln("<script>");
document.writeln("$(function(){");
document.writeln("	jQuery(\".about\").slide({titCell:\".hd ul\",mainCell:\".bd ul\",autoPage:true,effect:\"leftLoop\",autoPlay:true,vis:4});");
document.writeln("})");
document.writeln("</script>");