// JavaScript Document
document.writeln("<style>");
document.writeln("/*team*/");
document.writeln("#teamMain ul li{ height:520px; overflow:hidden; display:none;}");
document.writeln("#teamMain ul .active{ display:block;}");
document.writeln("#teamMain ul .img{ width:314px; height:510px; overflow:hidden; position:relative; text-align:center;}");
document.writeln("#teamMain ul .img a{ width:170px; text-align:center; height:40px; line-height:40px; font-size:16px; color:#fff; background:#0064b4; position:absolute; left:50%; bottom:0; margin-left:-85px;}");
document.writeln("#teamMain ul .img em{ vertical-align:middle; margin-right:5px; border:1px solid #0064b4;}");
document.writeln("#teamMain ul .img a:hover em{ transform:rotatey(360deg); -webkit-transform:rotatey(360deg);}");
document.writeln("#teamMain ul .word{ width:390px; color:#4b4b4b; margin-left:10px;}");
document.writeln("#teamMain ul .word h2{ color:#0064b4; font-size:48px; margin-bottom:24px;}");
document.writeln("#teamMain ul .word small{ font-size:22px; color:#4b4b4b;}");
document.writeln("#teamMain ul .word p{ font-size:18px; height:34px; line-height:34px;}");
document.writeln("#teamMain ul .word p:hover em{ transform:rotatey(360deg); -webkit-transform:rotatey(360deg);}");
document.writeln("#teamMain ul .word em{ width:23px; height:22px; background:url(/zt/yyjs/images/team_icon.png) center center no-repeat; vertical-align:middle; margin-right:10px;}");
document.writeln("#teamMain ul .word strong{ font-size:20px; color:#0064b4; margin:40px 0 10px;}");
document.writeln("#teamMain ul .word h4{ font-size:16px; line-height:30px;}");
document.writeln("#teamMain ol li{ width:246px; height:146px; padding:2px; border:1px solid #aaaaaa; margin-bottom:8px;}");
document.writeln("#teamMain ol .active{ border:1px solid #0064b4;}");
document.writeln("</style>");
document.writeln("<div id=\"team\" class=\"w1000\">");
document.writeln("        <div id=\"teamMain\" class=\"clearFix\">");
document.writeln("                <ul class=\"fl\">");
document.writeln("                        <li class=\"active\">");
document.writeln("                                <div class=\"img fl\"> <img src=\"/zt/yyjs/images/team1.jpg\" /> <a href=\"javascript:void(0);return false;\" onclick=\"openZoosUrl();return false;\" target=\"_blank\"><em><img src=\"/zt/yyjs/images/bespeak.png\" /></em>预约顾昌林医生</a> </div>");
document.writeln("                                <div class=\"word fl\">");
document.writeln("                                        <h2>顾昌林<small>主任医师</small></h2>");
document.writeln("                                        <p><em></em>国务院特殊津贴获得者</p>");
document.writeln("                                        <p><em></em>国家科技进步奖获得者</p>");
document.writeln("                                        <p><em></em>上海江城皮肤病医院主任及学术带头人</p>");
document.writeln("                                        <p><em></em>DFMZ-中医生物活化疗法创始人</p>");
document.writeln("                                        <strong>擅长领域:</strong>");
document.writeln("                                        <h4>从事皮肤病临床医疗、科研工作40余年,擅长运用中西医结合治疗各种皮肤病疑难杂症,在攻克皮肤病世界难题--银屑病,他破除西医治疗牛皮癣依赖激素和抗癌药的弊端,努力开发祖国医学传统,试验出13种天然中草药的配方,研发\"DFMZ308-牛皮癣中医活化疗法\",在2002年全国科技大会上获\"国家科技成果二等奖\".获得了很多患者的一致认可与称赞。</h4>");
document.writeln("                                </div>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                                <div class=\"img fl\"> <img src=\"/zt/yyjs/images/team2.jpg\" /> <a href=\"javascript:void(0);return false;\" onclick=\"openZoosUrl();return false;\" target=\"_blank\"><em><img src=\"/zt/yyjs/images/bespeak.png\" /></em>预约陶家喜医生</a> </div>");
document.writeln("                                <div class=\"word fl\">");
document.writeln("                                        <h2>陶家喜<small>副主任医师</small></h2>");
document.writeln("                                        <p><em></em>曾多次被评为军队优秀医务工作者</p>");
document.writeln("                                        <p><em></em>荣获三等功2次</p>");
document.writeln("                                        <p><em></em>军队科技进步二等奖2项</p>");
document.writeln("                                        <p><em></em>军队科技进步三等奖5项</p>");
document.writeln("                                        <strong>擅长领域:</strong>");
document.writeln("                                        <h4>从事皮肤科临床诊疗工作已逾30年，尤其在军队三甲综合大医院\"高标准、严要求\"下的历练，在理论修养与临床诊疗上，均有独到研究与见解。擅长治疗各种类型银屑病（牛皮癣），对鱼鳞病、湿疹、荨麻疹等其他顽固性皮肤病也有丰富诊治经验。医德高尚，妙手回春，赢得了国内外广大患者的信赖与好评。</h4>");
document.writeln("                                </div>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                                <div class=\"img fl\"> <img src=\"/zt/yyjs/images/team3.jpg\" /> <a href=\"javascript:void(0);return false;\" onclick=\"openZoosUrl();return false;\" target=\"_blank\"><em><img src=\"/zt/yyjs/images/bespeak.png\" /></em>预约罗兰珍医生</a> </div>");
document.writeln("                                <div class=\"word fl\">");
document.writeln("                                        <h2>罗兰珍<small>特聘专家</small></h2>");
document.writeln("                                        <p><em></em>上海江城皮肤病医院专家组成员</p>");
document.writeln("                                        <p><em></em>拥有丰富的临床诊疗经验</p>");
document.writeln("                                        <p><em></em>擅长中西医结合治疗银屑病</p>");
document.writeln("                                        <strong>擅长领域:</strong>");
document.writeln("                                        <h4>毕业于福建中医学院（现福建中医药大学），曾在福建省人民医院、福建省厦门市中医院（均为三甲医院）皮肤科进修深造，拥有丰富的临床诊疗经验。多次应邀参与银屑病、白癜风等中医皮肤科重点科研课题攻关，应邀参加全国大型皮肤病学术研讨会。注重中医理论与临床实践相结合，以中医内调外治为总则，达到标本兼治的效果，赢得广大患者的信任和好评。</h4>");
document.writeln("                                </div>");
document.writeln("                        </li>");
document.writeln("                </ul>");
document.writeln("                <ol class=\"fr\">");
document.writeln("                        <li class=\"active\"><img src=\"/zt/yyjs/images/team_btn1.jpg\" /></li>");
document.writeln("                        <li><img src=\"/zt/yyjs/images/team_btn2.jpg\" /></li>");
document.writeln("                        <li><img src=\"/zt/yyjs/images/team_btn3.jpg\" /></li>");
document.writeln("                </ol>");
document.writeln("        </div>");
document.writeln("</div>");
document.writeln("<script>");
document.writeln("/*team*/");
document.writeln("$(function(){");
document.writeln("	var aBtn=$(\'#team ol li\');");
document.writeln("	var aCut=$(\'#team ul li\');");
document.writeln("	tabSwitch(aBtn,aCut);");
document.writeln("})");
document.writeln("</script>");