document.writeln("<!--周华飞制作 QQ:1123486116-->");
document.writeln("<style>");
document.writeln("/*---------------------------------style_nav---------------------------------------*/");
document.writeln(".style_nav{ height:80px; margin:20px 0;}");
document.writeln(".style_nav ul{ height:100%; overflow:hidden; width:1000px; margin:0 auto; position:relative;}");
document.writeln(".style_nav #move{ position:absolute; left:130px; top:0; z-index:3; transition:0.3s; width:115px; height:80px;}");
document.writeln(".style_nav li{ float:left; margin:0 5px; width:115px; height:80px;}");
document.writeln("</style>");
document.writeln("<!----------------------------------style_nav--------------------------------------->");
document.writeln("<div class=\"style_nav\" id=\"style_nav\">");
document.writeln("	<ul>");
document.writeln("        	<div id=\"move\"><a href=\"/\"><img src=\"images/style2_2.png\" /></a></div>");
document.writeln("        	<li title=\"/\"><a href=\"/\"><img src=\"images/style1.png\" /></a></li>");
document.writeln("        	<li title=\"/\"><a href=\"/\"><img src=\"images/style2.png\" /></a></li>");
document.writeln("        	<li title=\"/\"><a href=\"/\"><img src=\"images/style3.png\" /></a></li>");
document.writeln("        	<li title=\"/\"><a href=\"/\"><img src=\"images/style4.png\" /></a></li>");
document.writeln("        	<li title=\"/\"><a href=\"/\"><img src=\"images/style5.png\" /></a></li>");
document.writeln("        	<li title=\"/\"><a href=\"/\"><img src=\"images/style6.png\" /></a></li>");
document.writeln("        	<li title=\"/\"><a href=\"/\"><img src=\"images/style7.png\" /></a></li>");
document.writeln("        	<li title=\"/\"><a href=\"/\"><img src=\"images/style8.png\" /></a></li>");
document.writeln("        </ul>");
document.writeln("</div>");
document.writeln("<script>");
document.writeln("eventBind(window,\'load\',function()");
document.writeln("{");
document.writeln("	/*style_nav*/");
document.writeln("	var oStyle_nav=document.getElementById(\'style_nav\');");
document.writeln("	var aStyle_li=oStyle_nav.getElementsByTagName(\'li\');");
document.writeln("	var oStyle_move=document.getElementById(\'move\');");
document.writeln("	var oStyle_move_a=oStyle_move.getElementsByTagName(\'a\')[0];");
document.writeln("	var oStyle_move_img=oStyle_move.getElementsByTagName(\'img\')[0];");
document.writeln("	var arrStyleOldImg=[\'images/style1.png\',\'images/style2.png\',\'images/style3.png\',\'images/style4.png\',\'images/style5.png\',\'images/style6.png\',\'images/style7.png\',\'images/style8.png\']");
document.writeln("	var arrStyleNewImg=[\'images/style1_1.png\',\'images/style2_2.png\',\'images/style3_3.png\',\'images/style4_4.png\',\'images/style5_5.png\',\'images/style6_6.png\',\'images/style7_7.png\',\'images/style8_8.png\']");
//document.writeln("	var roll=0;");
document.writeln("	for(var i=0; i<aStyle_li.length; i++)");
document.writeln("	{");
document.writeln("		aStyle_li[i].index=i;");
document.writeln("		aStyle_li[i].onmouseover=function()");
document.writeln("		{");
document.writeln("			for(var i=0; i<aStyle_li.length; i++)");
document.writeln("			{");
document.writeln("				aStyle_li[i].src=arrStyleOldImg[i];	");
document.writeln("			}");
document.writeln("			oStyle_move_img.src=arrStyleNewImg[this.index];");
document.writeln("			oStyle_move_a.href=aStyle_li[this.index].title;");
document.writeln("			oStyle_move.style.left=aStyle_li[this.index].offsetLeft+\'px\';");
//document.writeln("			roll=360*this.index;");
//document.writeln("			oStyle_move.style.transform=\'rotate(\'+roll+\'deg)\';");
document.writeln("		}	");
document.writeln("	}");
document.writeln("})");
document.writeln("function eventBind(obj,ev,fn)");
document.writeln("{");
document.writeln("	if(obj.attachEvent)");
document.writeln("	{");
document.writeln("		obj.attachEvent(\'on\'+ev,fn);");
document.writeln("	}");
document.writeln("	else");
document.writeln("	{");
document.writeln("		obj.addEventListener(ev,fn,false);");
document.writeln("	}	");
document.writeln("}");
document.writeln("</script>");
document.writeln("<!--周华飞制作 QQ:1123486116-->");