// JavaScript Document
document.writeln("<style>");
document.writeln("#footer{ background:#2d2d2d; line-height:1;}");
document.writeln("#footer .footerMain{ width:1200px; margin:0 auto;}");
document.writeln("#footer ul{ padding:37px 0 125px 31px; color:#cecece;}");
document.writeln("#footer h2{ font-size:16px; color:#fff; margin-bottom:18px;}");
document.writeln("#footer p{ font-size:14px; margin-bottom:16px;}");
document.writeln("#footer p.last{ margin-bottom:25px;}");
document.writeln("#footer h3{ font-size:16px; color:#fff; margin-bottom:12px;}");
document.writeln("#footer small{ font-size:12px; margin-left:10px;}");
document.writeln("#footer a{ display:inline-block;}");
document.writeln("#footer li{ float:left;}");
document.writeln("#footer li.one{ width:360px;}");
document.writeln("#footer li.one a{ margin:0 25px 17px 0; font-size:14px; color:#cecece;}");
document.writeln("#footer li.two{ width:330px; padding:0 40px; position:relative;}");
document.writeln("#footer li.two:before,#footer li.two:after{ content:\"\"; display:block; width:1px; height:100%; background:#202020; border-right:1px solid #363636; position:absolute; top:0;}");
document.writeln("#footer li.two:before{ left:0;}");
document.writeln("#footer li.two:after{ right:0;}");
document.writeln("#footer li.two div{ width:4px; height:4px; background:#fff; animation:topToBottom 6s linear infinite; -webkit-animation:topToBottom 6s linear infinite; position:absolute; top:0; z-index:2; filter:alpha(opacity:0);}");
document.writeln("#footer li.two div.one{ left:-1px;}");
document.writeln("#footer li.two div.two{ right:-1px;}");
document.writeln("#footer li.two a{ color:#cecece;}");
document.writeln("#footer li a:hover{ color:#0aa0b4;}");
document.writeln("#footer li.thr{ width:260px; padding-left:40px;}");
document.writeln("#footer li.thr dl{ margin-bottom:26px;}");
document.writeln("#footer li dd{ width:100px; padding-left:25px; line-height:30px; font-size:12px;}");
document.writeln("</style>");
document.writeln("<div id=\"footer\">");
document.writeln("	<div class=\"footerMain\">");
document.writeln("                <ul class=\"clearFix\">");
document.writeln("                        <li class=\"one\">");
document.writeln("                                <h2>精品项目</h2>");
document.writeln("                                <div class=\"clearFix\">");
document.writeln("                                        <a href=\"#\" target=\"_blank\">光学祛斑</a>");
document.writeln("                                        <a href=\"#\" target=\"_blank\">红血丝</a>");
document.writeln("                                        <a href=\"#\" target=\"_blank\">疤痕修复</a>");
document.writeln("                                        <a href=\"#\" target=\"_blank\">酒糟鼻</a>");
document.writeln("                                        <a href=\"#\" target=\"_blank\">冰点脱毛</a>");
document.writeln("                                        <a href=\"#\" target=\"_blank\">胎记</a>");
document.writeln("                                        <a href=\"#\" target=\"_blank\">美白</a>");
document.writeln("                                        <a href=\"#\" target=\"_blank\">瘦脸针</a>");
document.writeln("                                        <a href=\"#\" target=\"_blank\">玻尿酸</a>");
document.writeln("                                        <a href=\"#\" target=\"_blank\">botox</a>");
document.writeln("                                        <a href=\"#\" target=\"_blank\">除皱</a>");
document.writeln("                                        <a href=\"#\" target=\"_blank\">溶脂紧肤</a>");
document.writeln("                                </div>");
document.writeln("                        </li>");
document.writeln("                        <li class=\"two\">");
document.writeln("                        	<div class=\"one\"></div>");
document.writeln("                        	<div class=\"two\"></div>");
document.writeln("                        	<h2>来院路线</h2>");
document.writeln("                                <p>上海市杨浦区黄兴路286号</p>");
document.writeln("                                <p><a href=\"#\" target=\"_blank\">[查看交通路线图]</a></p>");
document.writeln("                                <p>沪医广【2011】第11-12-G168号</p>");
document.writeln("                                <p>沪ICP备09044608号</p>");
document.writeln("                                <p class=\"last\">沪ICP备09008778号</p>");
document.writeln("                                <h3>美丽热线<small>Beautiful hotline</small></h3>");
document.writeln("                                <img src=\"/images/footer1.png\">");
document.writeln("                        </li>");
document.writeln("                        <li class=\"thr\">");
document.writeln("                        	<dl class=\"clearFix\">");
document.writeln("                                	<dt class=\"fl\"><img src=\"/images/er.jpg\"></dt>");
document.writeln("                                        <dd class=\"fl\">扫描最新优惠<br>手机随时咨询<br>整形实时资讯<br>微信搜索上海江城</dd>");
document.writeln("                                </dl>");
document.writeln("                                <img src=\"/images/footer2.png\">");
document.writeln("                        </li>");
document.writeln("                </ul>");
document.writeln("        </div>");
document.writeln("</div>");