// JavaScript Document
document.writeln("<!--safe-->");
document.writeln("<style>");
document.writeln("/*safe*/");
document.writeln("#safe{ color:#656565; margin-bottom:44px; line-height:1;}");
document.writeln("#safe ol li{ width:270px; height:72px; overflow:hidden; line-height:72px; background:#dcdcdc; margin-bottom:1px; font-size:18px; color:#585858; color:#585858; position:relative;}");
document.writeln("#safe ol li.active{ background:#0aa0b4; color:#fff;}");
document.writeln("#safe ol li:before{ content:\"\"; display:inline-block; vertical-align:middle; width:29px; height:28px; background:url(images/safe.png) no-repeat; margin:0 8px 0 22px; transition:0.4s;}");
document.writeln("#safe ol li.one:before{ background-position:left top;}");
document.writeln("#safe ol li.two:before{ background-position:left -144px;}");
document.writeln("#safe ol li.thr:before{ background-position:left -286px;}");
document.writeln("#safe ol li.fou:before{ background-position:left -430px;}");
document.writeln("#safe ol li.fiv:before{ background-position:left -576px;}");
document.writeln("#safe ol li.six:before{ background-position:left -720px;}");
document.writeln("#safe ol li.active.one:before{ background-position:left -72px;}");
document.writeln("#safe ol li.active.two:before{ background-position:left -216px;}");
document.writeln("#safe ol li.active.thr:before{ background-position:left -358px;}");
document.writeln("#safe ol li.active.fou:before{ background-position:left -502px;}");
document.writeln("#safe ol li.active.fiv:before{ background-position:left -648px;}");
document.writeln("#safe ol li.active.six:before{ background-position:left -792px;}");
document.writeln("#safe ol li:after{ content:\"\"; display:inline-block; width:13px; height:17px; background:url(images/safe.png) left -864px no-repeat; position:absolute; right:-13px; top:50%; margin-top:-9px; transition:0.4s;}");
document.writeln("#safe ol li.active:after{ right:0;}");
document.writeln("#safe ul{ width:930px; height:437px; background:#f8f8f8; position:relative;}");
document.writeln("#safe ul li{ padding:29px 0 0 24px; background:#f8f8f8; position:absolute; left:0; top:0; opacity:0; filter:alpha(opacity:0);}");
document.writeln("#safe ul li.active{ opacity:1; filter:alpha(opacity:100); z-index:2;}");
document.writeln("#safe ul dt{ width:471px; height:379px;}");
document.writeln("#safe ul dd{ width:370px; height:379px; padding-left:31px; position:relative;}");
document.writeln("#safe ul dd .btns{ bottom:0; right:0;}");
document.writeln("#safe ul dd h3{ margin:34px 0 12px; font-size:18px; color:#585858; text-align:right;}");
document.writeln("#safe ul dd p{ line-height:30px; font-size:16px;}");
document.writeln("/*common*/");
document.writeln(".btns{ position:absolute; right:8px; bottom:32px;}");
document.writeln(".btns a{ width:38px; height:38px; float:left; background:url(images/technology.png) left -612px no-repeat;}");
document.writeln(".btns a:hover{ background-position:left -684px;}");
document.writeln(".btns a.mr3{ margin-right:2px; background-position:left -468px;}");
document.writeln(".btns a.mr3:hover{ background-position:left -540px;}");
document.writeln("</style>");
document.writeln("<!--safe-->");
document.writeln("<div id=\"safe\" class=\"w1200\">");
document.writeln("        <div class=\"clearFix\">");
document.writeln("        	<ol class=\"fl\">");
document.writeln("                	<li class=\"one active\">术前检查系统</li>");
document.writeln("                	<li class=\"two\">材料安全管理中心</li>");
document.writeln("                	<li class=\"thr\">术中麻醉监测系统</li>");
document.writeln("                	<li class=\"fou\">术后安全管理系统</li>");
document.writeln("                	<li class=\"fiv\">应急电力保障系统</li>");
document.writeln("                	<li class=\"six noMb\">德国千层流无菌手术室</li>");
document.writeln("                </ol>");
document.writeln("                <ul class=\"fl\">");
document.writeln("                	<li class=\"active\">");
document.writeln("                        	<dl class=\"clearFix\">");
document.writeln("                                	<dt class=\"fl\"><img src=\"images/safe1.jpg\" /></dt>");
document.writeln("                                        <dd class=\"fl\">");
document.writeln("                                        	<h3>术前检查系统</h3>");
document.writeln("                                                <p>手术前，江城的求美者除了做好皮肤检测等诊断检查 还需要做多项安全相关检查，如高血压、促脉、结核、心脏病等，江城专家将综合分析求美者的身体状况，决定其是否适合进行特定项目。</p>");
document.writeln("                                                <div class=\"btns\">");
document.writeln("                                                        <a href=\"#\" target=\"_blank\" class=\"mr3\"></a>");
document.writeln("                                                        <a href=\"#\" target=\"_blank\"></a>");
document.writeln("                                                </div>");
document.writeln("                                        </dd>");
document.writeln("                                </dl>");
document.writeln("                        </li>");
document.writeln("                	<li>");
document.writeln("                        	<dl class=\"clearFix\">");
document.writeln("                                	<dt class=\"fl\"><img src=\"images/safe2.jpg\" /></dt>");
document.writeln("                                        <dd class=\"fl\">");
document.writeln("                                        	<h3>材料安全管理中心</h3>");
document.writeln("                                                <p>在江城的每一个成功塑美案例都离不开优质材料，我院有着严格严谨的选材流程。只选择权威机构生产的优质材料，从采购物流仓储下发一套流程都由材料保障中心严格执行与监管。</p>");
document.writeln("                                                <div class=\"btns\">");
document.writeln("                                                        <a href=\"#\" target=\"_blank\" class=\"mr3\"></a>");
document.writeln("                                                        <a href=\"#\" target=\"_blank\"></a>");
document.writeln("                                                </div>");
document.writeln("                                        </dd>");
document.writeln("                                </dl>");
document.writeln("                        </li>");
document.writeln("                	<li>");
document.writeln("                        	<dl class=\"clearFix\">");
document.writeln("                                	<dt class=\"fl\"><img src=\"images/safe3.jpg\" /></dt>");
document.writeln("                                        <dd class=\"fl\">");
document.writeln("                                        	<h3>术中麻醉监测系统</h3>");
document.writeln("                                                <p>手术中，每一项无痛麻醉都是由江城安全麻醉中心的专家亲自操作。麻醉中心麻醉专家均由至少10年经验的麻醉师担当，麻醉不但影响手术的安全进行更关系到求美者的安全；在江城必须严格管控。</p>");
document.writeln("                                                <div class=\"btns\">");
document.writeln("                                                        <a href=\"#\" target=\"_blank\" class=\"mr3\"></a>");
document.writeln("                                                        <a href=\"#\" target=\"_blank\"></a>");
document.writeln("                                                </div>");
document.writeln("                                        </dd>");
document.writeln("                                </dl>");
document.writeln("                        </li>");
document.writeln("                	<li>");
document.writeln("                        	<dl class=\"clearFix\">");
document.writeln("                                	<dt class=\"fl\"><img src=\"images/safe4.jpg\" /></dt>");
document.writeln("                                        <dd class=\"fl\">");
document.writeln("                                        	<h3>术后安全管理系统</h3>");
document.writeln("                                                <p>所有技术服务均实现先进理念同步，包括器械、药物、膳食管理、精细的护理、按摩等细节，均全盘引进韩国正统服务模式，令爱美者术后恢复期革命性提速，对于爱美者关心的术后效果问题，江城提供了\"效果全景预见\"服务，保证爱美者对未来整形预期效果有着更直观的判断。</p>");
document.writeln("                                                <div class=\"btns\">");
document.writeln("                                                        <a href=\"#\" target=\"_blank\" class=\"mr3\"></a>");
document.writeln("                                                        <a href=\"#\" target=\"_blank\"></a>");
document.writeln("                                                </div>");
document.writeln("                                        </dd>");
document.writeln("                                </dl>");
document.writeln("                        </li>");
document.writeln("                	<li>");
document.writeln("                        	<dl class=\"clearFix\">");
document.writeln("                                	<dt class=\"fl\"><img src=\"images/safe5.jpg\" /></dt>");
document.writeln("                                        <dd class=\"fl\">");
document.writeln("                                        	<h3>应急电力保障系统</h3>");
document.writeln("                                                <p>江城以患者的安全为重要使命，在综合考虑和模拟各种情况后，我院斥巨资建造了独立应急发电系统，以应对突发的紧急停电状况。保证不给治疗，使用中的仪器尤其手术因突发停电而带来不必要的损害。</p>");
document.writeln("                                                <div class=\"btns\">");
document.writeln("                                                        <a href=\"#\" target=\"_blank\" class=\"mr3\"></a>");
document.writeln("                                                        <a href=\"#\" target=\"_blank\"></a>");
document.writeln("                                                </div>");
document.writeln("                                        </dd>");
document.writeln("                                </dl>");
document.writeln("                        </li>");
document.writeln("                	<li>");
document.writeln("                        	<dl class=\"clearFix\">");
document.writeln("                                	<dt class=\"fl\"><img src=\"images/safe6.jpg\" /></dt>");
document.writeln("                                        <dd class=\"fl\">");
document.writeln("                                        	<h3>德国千层流无菌手术室</h3>");
document.writeln("                                                <p>江城采用德国千层流无菌手术室，独特的空气洁净技术对微生物污染采取程度不同的控制，并提供适宜的温、湿度；手术区内空气压力将根据不同区域的需求调整变化，每升空气中≥0.5μm的尘粒数不超过35颗；空气洁净度可以到达99.98%，可做三级以上整形项目。</p>");
document.writeln("                                                <div class=\"btns\">");
document.writeln("                                                        <a href=\"#\" target=\"_blank\" class=\"mr3\"></a>");
document.writeln("                                                        <a href=\"#\" target=\"_blank\"></a>");
document.writeln("                                                </div>");
document.writeln("                                        </dd>");
document.writeln("                                </dl>");
document.writeln("                        </li>");
document.writeln("                </ul>");
document.writeln("        </div>");
document.writeln("</div>");
document.writeln("<script>");
document.writeln("var r=new Rookie();");
document.writeln("r.version();");
document.writeln("r.addEvent(window,\'load\',function(){	");
document.writeln("	/*safe*/	");
document.writeln("	r.tabSwitch({aBtn:\"#safe ol li\",aCut:\"#safe ul li\"});");
document.writeln("})");
document.writeln("</script>");