// JavaScript Document
document.writeln("        <!--aside-->");
document.writeln("        <style>");
document.writeln("	  /*aside*/");
document.writeln("        .aside{ width:299px; border-left:1px solid #dcdcdc; border-top:1px solid #dcdcdc; padding-top:25px;}");
document.writeln("	  .aside h2.acTil{ font-size:18px; color:#656565; margin-bottom:12px;}");
document.writeln("	  .aside ol{ position:absolute; right:10px; top:3px;}");
document.writeln("	  .aside ol li{ width:13px; height:13px; margin:0 3px; float:left; background:#dcdcdc; border-radius:50%;}");
document.writeln("	  .aside ol li.active{ background:#0aa0b4;}");
document.writeln("	  .aside ul{ width:274px; position:relative;}");
document.writeln("	  .aside ul li{ width:100%; height:100%; opacity:0; filter:alpha(opacity:0); position:absolute; left:0; top:0; z-index:1;}");
document.writeln("	  .aside ul li.active{ opacity:1; filter:alpha(opacity:100); z-index:2;}");
document.writeln("	  .aside .actives{ position:relative; padding-left:25px; border-bottom:1px solid #dcdcdc; margin-bottom:25px;}");
document.writeln("	  .aside .actives ul{ height:322px;}");
document.writeln("	  .aside .actives span{ width:100%; height:160px; background:#0aa0b4; margin-bottom:17px;}");
document.writeln("	  .aside .actives p{ font-size:14px; color:#656565; margin-bottom:11px;}");
document.writeln("	  .aside .actives div{ margin:3px 0 23px 0;}");
document.writeln("	  .aside .actives a{ width:66px; text-align:center; height:20px; line-height:20px; color:#d80000; border:1px solid #d80000; font-size:14px; border-radius:4px; float:left; margin-right:20px;}");
document.writeln("	  .aside .experts{ padding-left:25px; margin-bottom:25px; position:relative; border-bottom:1px solid #dcdcdc;}");
document.writeln("	  .aside .experts ul{ height:196px;}");
document.writeln("	  .aside .experts div.img{ padding:7px 0; margin:12px 0; border-top:1px dashed #dcdcdc; border-bottom:1px dashed #dcdcdc;}");
document.writeln("	  .aside .experts div.img a{ height:32px; display:block; background:url(images/list.png) left -216px;}");
document.writeln("	  .aside .experts div.exBtn{ margin-bottom:25px;}");
document.writeln("	  .aside .experts div.exBtn a{ width:132px; background:#0aa0b4; text-align:center; height:40px; line-height:40px; font-size:16px; color:#fff;}");
document.writeln("	  .aside .experts div.exBtn a:before{ content:\"\"; transition:0.4s; vertical-align:middle; margin-right:5px; display:inline-block; width:21px; height:21px; background:url(images/list.png) left -108px no-repeat;}");
document.writeln("	  .aside .experts div.exBtn a.last:before{ background-position:left -144px;}");
document.writeln("	  .aside .experts div.exBtn a:hover:before{ transform:rotate(360deg); -webkit-transform:rotate(360deg);}");
document.writeln("	  .aside .recommend{ padding-left:25px; margin-bottom:25px; border-bottom:1px solid #dcdcdc;}");
document.writeln("	  .aside .recommend h2{ position:relative;}");
document.writeln("	  .aside .recommend h2 a{ width:72px; height:20px; text-align:center; line-height:20px; background:#0aa0b4; color:#fff; font-size:12px; border-radius:5px; position:absolute; right:10px; top:0;}");
document.writeln("	  .aside .recommend dd{ margin-bottom:4px;}");
document.writeln("	  .aside .recommend dd.last{ margin-bottom:25px;}");
document.writeln("	  .aside .trouble{ padding-left:25px; margin-bottom:50px;}");
document.writeln("	  .aside .trouble dt{ width:72px; height:52px; text-align:center; line-height:52px; background:#5db6e7; margin-right:2px;}");
document.writeln("	  .aside .trouble dd{ height:25px; text-align:center; line-height:25px; float:left; margin-right:2px; margin:0 2px 2px 0;}");
document.writeln("	  .aside .trouble dd.one{ width:58px; background:#f66d5f;}");
document.writeln("	  .aside .trouble dd.two{ width:68px; background:#eba24c;}");
document.writeln("	  .aside .trouble dd.thr{ width:70px; background:#27b3ae; margin-right:0;}");
document.writeln("	  .aside .trouble dd.fou{ width:50px; background:#8f2deb; margin-bottom:0;}");
document.writeln("	  .aside .trouble dd.fiv{ width:68px; background:#be5908; margin-bottom:0;}");
document.writeln("	  .aside .trouble dd.six{ width:78px; background:#5db6e7; margin:0;}");
document.writeln("	  .aside .trouble a{ display:block; font-size:12px; color:#fff;}");
document.writeln("	  .aside .trouble a:hover{ text-decoration:underline;}");
document.writeln("        </style>");
document.writeln("        <!--aside-->");
document.writeln("        <div class=\"aside fr\">");
document.writeln("        	<div class=\"actives\">");
document.writeln("                	<h2 class=\"acTil\">塑美活动</h2>");
document.writeln("                	<ol class=\"clearFix\">");
document.writeln("                        	<li class=\"active\"></li>");
document.writeln("                        	<li></li>");
document.writeln("                        	<li></li>");
document.writeln("                        </ol>");
document.writeln("                        <ul>");
document.writeln("                        	<li class=\"active\">");
document.writeln("                                	<span>1</span>");
document.writeln("                                        <p>牙贴面新品发布1</p>");
document.writeln("                                        <p>活动时间：3月31号</p>");
document.writeln("                                        <p>活动摘要：德国超薄瓷贴面超值秒杀</p>");
document.writeln("                                        <p>活动地点：上海江城皮肤病医院</p>");
document.writeln("                                        <div class=\"clearFix\">");
document.writeln("                                        	<a href=\"#\" target=\"_blank\">详情 →</a>");
document.writeln("                                        	<a href=\"#\" target=\"_blank\">报名 →</a>");
document.writeln("                                        </div>");
document.writeln("                                </li>");
document.writeln("                        	<li>");
document.writeln("                                	<span>2</span>");
document.writeln("                                        <p>牙贴面新品发布2</p>");
document.writeln("                                        <p>活动时间：3月31号</p>");
document.writeln("                                        <p>活动摘要：德国超薄瓷贴面超值秒杀</p>");
document.writeln("                                        <p>活动地点：上海江城皮肤病医院</p>");
document.writeln("                                        <div class=\"clearFix\">");
document.writeln("                                        	<a href=\"#\" target=\"_blank\">详情 →</a>");
document.writeln("                                        	<a href=\"#\" target=\"_blank\">报名 →</a>");
document.writeln("                                        </div>");
document.writeln("                                </li>");
document.writeln("                        	<li>");
document.writeln("                                	<span>3</span>");
document.writeln("                                        <p>牙贴面新品发布3</p>");
document.writeln("                                        <p>活动时间：3月31号</p>");
document.writeln("                                        <p>活动摘要：德国超薄瓷贴面超值秒杀</p>");
document.writeln("                                        <p>活动地点：上海江城皮肤病医院</p>");
document.writeln("                                        <div class=\"clearFix\">");
document.writeln("                                        	<a href=\"#\" target=\"_blank\">详情 →</a>");
document.writeln("                                        	<a href=\"#\" target=\"_blank\">报名 →</a>");
document.writeln("                                        </div>");
document.writeln("                                </li>");
document.writeln("                        </ul>");
document.writeln("              </div>");
document.writeln("        	<div class=\"experts\">");
document.writeln("                	<h2 class=\"acTil\">推荐专家</h2>");
document.writeln("                	<ol class=\"clearFix\">");
document.writeln("                        	<li class=\"active\"></li>");
document.writeln("                        	<li></li>");
document.writeln("                        	<li></li>");
document.writeln("                        	<li></li>");
document.writeln("                        	<li></li>");
document.writeln("                        </ol>");
document.writeln("                	<ul>");
document.writeln("                        	<li class=\"active\"><img src=\"images/asideExperts1.jpg\" /></li>");
document.writeln("                        	<li><img src=\"images/asideExperts2.jpg\" /></li>");
document.writeln("                        	<li><img src=\"images/asideExperts3.jpg\" /></li>");
document.writeln("                        	<li><img src=\"images/asideExperts4.jpg\" /></li>");
document.writeln("                        	<li><img src=\"images/asideExperts5.jpg\" /></li>");
document.writeln("                        </ul>");
document.writeln("                        <div class=\"img\"><a href=\"#\" target=\"_blank\"></a></div>");
document.writeln("                        <div class=\"clearFix exBtn\">");
document.writeln("                        	<a href=\"#\" target=\"_blank\" class=\"fl\">在线咨询</a>");
document.writeln("                        	<a href=\"#\" target=\"_blank\" class=\"last fr\">来院路线</a>");
document.writeln("                        </div>");
document.writeln("              </div>");
document.writeln("        	<div class=\"recommend\">");
document.writeln("                	<h2 class=\"acTil\">推荐专题<a href=\"#\" target=\"_blank\">更多专题 +</a></h2>");
document.writeln("                        <dl>");
document.writeln("                        	<dd><a href=\"#\" target=\"_blank\"><img src=\"images/recommend1.jpg\" /></a></dd>");
document.writeln("                        	<dd><a href=\"#\" target=\"_blank\"><img src=\"images/recommend2.jpg\" /></a></dd>");
document.writeln("                        	<dd><a href=\"#\" target=\"_blank\"><img src=\"images/recommend3.jpg\" /></a></dd>");
document.writeln("                        	<dd><a href=\"#\" target=\"_blank\"><img src=\"images/recommend4.jpg\" /></a></dd>");
document.writeln("                        	<dd><a href=\"#\" target=\"_blank\"><img src=\"images/recommend5.jpg\" /></a></dd>");
document.writeln("                        	<dd class=\"last\"><a href=\"#\" target=\"_blank\"><img src=\"images/recommend6.jpg\" /></a></dd>");
document.writeln("                        </dl>");
document.writeln("              </div>");
document.writeln("        	<div class=\"trouble\">");
document.writeln("                	<h2 class=\"acTil\">你还在烦恼这些？</h2>");
document.writeln("                        <dl class=\"clearFix\">");
document.writeln("                        	<dt class=\"fl\"><a href=\"#\" target=\"_blank\">痘痘多</a></dt>");
document.writeln("                                <dd class=\"one\"><a href=\"#\" target=\"_blank\">单眼皮</a></dd>");
document.writeln("                                <dd class=\"two\"><a href=\"#\" target=\"_blank\">水桶腰</a></dd>");
document.writeln("                                <dd class=\"thr\"><a href=\"#\" target=\"_blank\">汗毛多</a></dd>");
document.writeln("                                <dd class=\"fou\"><a href=\"#\" target=\"_blank\">皱纹</a></dd>");
document.writeln("                                <dd class=\"fiv\"><a href=\"#\" target=\"_blank\">长色斑</a></dd>");
document.writeln("                                <dd class=\"six\"><a href=\"#\" target=\"_blank\">皮肤老化</a></dd>");
document.writeln("                        </dl>                	");
document.writeln("              </div>");
document.writeln("        </div>");
document.writeln("        <script>");
document.writeln("	  var r=new Rookie();");
document.writeln("	  r.version();");
document.writeln("	  r.addEvent(window,\'load\',function(){");
document.writeln("		/*aside==>actives*/");
document.writeln("		r.tabSwitch({aBtn:\".aside .actives ol li\",aCut:\".aside .actives ul li\",bAutoPlay:true});");
document.writeln("		/*aside==>experts*/");
document.writeln("		r.tabSwitch({aBtn:\".aside .experts ol li\",aCut:\".aside .experts ul li\",bAutoPlay:true});");
document.writeln("	  })");
document.writeln("        </script>");