// JavaScript Document
document.writeln("<!--menu-->");
document.writeln("<style>");
document.writeln("/*menu*/");
document.writeln("#menu{ background:#f2f2f2; height:87px; margin-bottom:44px; line-height:1;}");
document.writeln("#menu ul{ height:100%; width:1200px; margin:0 auto;}");
document.writeln("#menu li{ width:79px; height:100%; float:left; position:relative; border-left:1px solid #e0e0e0;}");
document.writeln("#menu li.bg8{ width:78px;}");
document.writeln("#menu li.bg15{ border-right:1px solid #e0e0e0;}");
document.writeln("#menu li a{ width:100%; text-align:center; height:100%; color:6a6a6a; font-size:12px; position:absolute; left:0; top:0; z-index:5;}");
document.writeln("#menu li a:before,#menu li a:after{ content:\"\"; display:block; width:100%; height:100%; position:absolute; left:0; top:0;}");
document.writeln("#menu li a:before{ background:#0aa0b4; animation:fadeOut 0.4s; -webkit-animation:fadeOut 0.4s; opacity:0; filter:alpha(opacity:0); display:none\\0;}");
document.writeln("#menu li a:after{ background:url(images/menu.png) no-repeat;}");
document.writeln("#menu li p{ width:100%; position:absolute; left:0; bottom:12px;}");
document.writeln("#menu li.bg1 a:after{ background-position:left -58px;}");
document.writeln("#menu li.bg2 a:after{ background-position:left -275px;}");
document.writeln("#menu li.bg3 a:after{ background-position:left -485px;}");
document.writeln("#menu li.bg4 a:after{ background-position:left -700px;}");
document.writeln("#menu li.bg5 a:after{ background-position:left -922px;}");
document.writeln("#menu li.bg6 a:after{ background-position:left -1133px;}");
document.writeln("#menu li.bg7 a:after{ background-position:left -1354px;}");
document.writeln("#menu li.bg8 a:after{ background-position:left -1572px;}");
document.writeln("#menu li.bg9 a:after{ background-position:left -1789px;}");
document.writeln("#menu li.bg10 a:after{ background-position:left -2002px;}");
document.writeln("#menu li.bg11 a:after{ background-position:left -2218px;}");
document.writeln("#menu li.bg12 a:after{ background-position:left -2434px;}");
document.writeln("#menu li.bg13 a:after{ background-position:left -2640px;}");
document.writeln("#menu li.bg14 a:after{ background-position:left -2867px;}");
document.writeln("#menu li.bg15 a:after{ background-position:left -3077px;}");
document.writeln("#menu li:hover a{ color:#fff;}");
document.writeln("#menu li:hover a:before{ animation:fadeIn 0.4s; -webkit-animation:fadeIn 0.4s; opacity:1; filter:alpha(opacity:100); display:block\\0;}");
document.writeln("#menu li.bg1:hover a:after{ background-position:left -169px;}");
document.writeln("#menu li.bg2:hover a:after{ background-position:left -382px;}");
document.writeln("#menu li.bg3:hover a:after{ background-position:left -593px;}");
document.writeln("#menu li.bg4:hover a:after{ background-position:left -809px;}");
document.writeln("#menu li.bg5:hover a:after{ background-position:left -1030px;}");
document.writeln("#menu li.bg6:hover a:after{ background-position:left -1241px;}");
document.writeln("#menu li.bg7:hover a:after{ background-position:left -1464px;}");
document.writeln("#menu li.bg8:hover a:after{ background-position:left -1680px;}");
document.writeln("#menu li.bg9:hover a:after{ background-position:left -1897px;}");
document.writeln("#menu li.bg10:hover a:after{ background-position:left -2110px;}");
document.writeln("#menu li.bg11:hover a:after{ background-position:left -2326px;}");
document.writeln("#menu li.bg12:hover a:after{ background-position:left -2542px;}");
document.writeln("#menu li.bg13:hover a:after{ background-position:left -2748px;}");
document.writeln("#menu li.bg14:hover a:after{ background-position:left -2975px;}");
document.writeln("#menu li.bg15:hover a:after{ background-position:left -3185px;}");
document.writeln("</style>");
document.writeln("<!--menu-->");
document.writeln("<div id=\"menu\">");
document.writeln("	<ul class=\"clearFix\">");
document.writeln("        	<li class=\"bg1\"><a href=\"#\" target=\"_blank\"><p>¹âÑ§ìî°ß</p></a></li>");
document.writeln("        	<li class=\"bg2\"><a href=\"#\" target=\"_blank\"><p>ºìÑªË¿</p></a></li>");
document.writeln("        	<li class=\"bg3\"><a href=\"#\" target=\"_blank\"><p>°ÌºÛÐÞ¸´</p></a></li>");
document.writeln("        	<li class=\"bg4\"><a href=\"#\" target=\"_blank\"><p>¾ÆÔã±Ç</p></a></li>");
document.writeln("        	<li class=\"bg5\"><a href=\"#\" target=\"_blank\"><p>±ùµãÍÑÃ«</p></a></li>");
document.writeln("        	<li class=\"bg6\"><a href=\"#\" target=\"_blank\"><p>Ì¥¼Ç</p></a></li>");
document.writeln("        	<li class=\"bg7\"><a href=\"#\" target=\"_blank\"><p>ÃÀ°×</p></a></li>");
document.writeln("        	<li class=\"bg8\"><a href=\"#\" target=\"_blank\"><p>ÊÝÁ³Õë</p></a></li>");
document.writeln("        	<li class=\"bg9\"><a href=\"#\" target=\"_blank\"><p>²£ÄòËá</p></a></li>");
document.writeln("        	<li class=\"bg10\"><a href=\"#\" target=\"_blank\"><p>botox</p></a></li>");
document.writeln("        	<li class=\"bg11\"><a href=\"#\" target=\"_blank\"><p>³ýÖå</p></a></li>");
document.writeln("        	<li class=\"bg12\"><a href=\"#\" target=\"_blank\"><p>Ö¬·¾ÒÆÖ²</p></a></li>");
document.writeln("        	<li class=\"bg13\"><a href=\"#\" target=\"_blank\"><p>Ë«ÑÛÆ¤</p></a></li>");
document.writeln("        	<li class=\"bg14\"><a href=\"#\" target=\"_blank\"><p>Â¡±Ç</p></a></li>");
document.writeln("        	<li class=\"bg15\"><a href=\"#\" target=\"_blank\"><p>¡¾¾­µäÏîÄ¿¡¿</p></a></li>");
document.writeln("        </ul>");
document.writeln("</div>");