//JavaScript Document
/*********************************
 *rookie QQ:1123486116
 *rookie making
 *rookie Copyright
 **********************************/
document.writeln("		<style>");
document.writeln("                /*zero*/");
document.writeln("                body,div,menu,ol,ul,li,dl,dd,dt,h1,h2,h3,h4,h5,h6,input,p,form,header,nav,article,section,aside,footer,video,audio,figure,textarea { padding: 0; margin: 0; }");
document.writeln("                input,select,textarea,img,area { outline: none; border: none; }");
document.writeln("                input,select,textarea { background: #FFF; }");
document.writeln("                mark { background: none; }");
document.writeln("                img { vertical-align: middle; }");
document.writeln("                textarea { resize: none; }");
document.writeln("                li { list-style-type: none; }");
document.writeln("                body { font: 14px/1 \"Microsoft YaHei\"; }");
document.writeln("                em,i,strong,b,small,h1,h2,h3,h4,h5,h6,address,cite { font-style: normal; font-weight: normal; font-size: 100%; }");
document.writeln("                span,b,em,i,strong,small,label,a,mark { display: inline-block; }");
document.writeln("                em,i,strong,b,small,span,li,a,mark { transition: all 0.4s; }");
document.writeln("                ul li { transition: 0s; }");
document.writeln("                a { text-decoration: none; outline: none; color: inherit; }");
document.writeln("                /*clear-fix*/");
document.writeln("                .clear-fix { clear: both; *zoom: 1;}");
document.writeln("                .clear-fix:after { clear: both; display: block; visibility: hidden; height: 0; line-height: 0; content: \"\"; font-size: 0; }");
document.writeln("                /*common*/");
document.writeln("                .fl { float: left; }");
document.writeln("                .fr { float: right; }");
document.writeln("                .w996 { width: 996px; margin: 0 auto; }");
document.writeln("                /*noSpacing*/");
document.writeln("                .no-mt { margin-top: 0; }");
document.writeln("                .no-mr { margin-right: 0; }");
document.writeln("                .no-mb { margin-bottom: 0; }");
document.writeln("                .no-ml { margin-left: 0; }");
document.writeln("                .no-pt { padding-top: 0; }");
document.writeln("                .no-pr { padding-right: 0; }");
document.writeln("                .no-pb { padding-bottom: 0; }");
document.writeln("                .no-pl { padding-left: 0; }");
document.writeln("                .no-bt { border-top: none; }");
document.writeln("                .no-br { border-right: none; }");
document.writeln("                .no-bb { border-bottom: none; }");
document.writeln("                .no-bl { border-left: none; }");
document.writeln("                .no-ti { text-indent: 0; color: #c80101; }");
document.writeln("                /*top*/");
document.writeln("                #top { font-size: 12px; color: #7f7f7f; padding: 9px 0; border-bottom: 1px solid #bcbcbc; clear: both; *zoom: 1;}");
document.writeln("                #top:after { clear: both; display: block; visibility: hidden; height: 0; line-height: 0; content: \"\"; font-size: 0; }");
document.writeln("                #top div { width: 996px; margin: 0 auto; }");
document.writeln("                #top ol { float: left; }");
document.writeln("                #top li { padding-right: 12px; margin-right: 12px; float: left; border-right: 1px solid #bcbcbc; }");
document.writeln("                #top li.top-last-li { border-right: none; }");
document.writeln("                #top em { width: 9px; height: 12px; background: url(\"images/top-phone.jpg\") center no-repeat; vertical-align: middle; margin-right: 6px; }");
document.writeln("                #top span { float: right; word-spacing: 10px; }");
document.writeln("                /*header*/");
document.writeln("                #header { width: 996px; margin: 0 auto; height: 100px; background: url(\"images/header.jpg\") center no-repeat; }");
document.writeln("                /*nav*/");
document.writeln("                #nav { background: url(\"images/nav-bg.jpg\"); color: #ffffff; text-align: center; }");
document.writeln("                #nav > ul { clear: both; *zoom: 1;");
document.writeln("                display: inline-block; }");
document.writeln("                #nav > ul:after { clear: both; display: block; visibility: hidden; height: 0; line-height: 0; content: \"\"; font-size: 0; }");
document.writeln("                #nav > ul > li { float: left; position: relative; }");
document.writeln("                #nav > ul > li > a,#nav > ul > li > span { padding: 0 16px; font-size: 16px; line-height: 48px; }");
document.writeln("                #nav > ul > li:hover { background: #005895; }");
document.writeln("                #nav > ul > li:hover div { display: block; }");
document.writeln("                #nav > ul > li.active a { color: #ffeb0b; background: url(\"images/nav-hot.gif\") right top no-repeat; }");
document.writeln("                #nav > ul div { position: absolute; display: none; padding: 30px; width: 240px; background: #05548a; text-align: left; z-index: 10; clear: both; *zoom: 1;}");
document.writeln("                #nav > ul div:after { clear: both; display: block; visibility: hidden; height: 0; line-height: 0; content: \"\"; font-size: 0; }");
document.writeln("                #nav > ul div em { width: 8px; height: 8px; vertical-align: middle; background: #ffffff; margin: 0 6px; }");
document.writeln("                #nav > ul div ol { float: left; }");
document.writeln("                #nav > ul div ul { float: right; }");
document.writeln("                #nav > ul div a { line-height: 30px; font-size: 14px; }");
document.writeln("                </style>");


document.writeln("                <!--top-->");
document.writeln("                <div id=\"top\">");
document.writeln("                        <div>");
document.writeln("                                <ol>");
document.writeln("                                        <li><a href=\"/\" target=\"_blank\">网站首页</a></li>");
document.writeln("                                        <li><a href=\"http://wap.skinjc.com\" target=\"_blank\"><em></em>手机版</a></li>");
document.writeln("                                        <li><a href=\"/special/zjzt/\" target=\"_blank\">医生介绍</a></li>");
document.writeln("                                        <li class=\"top-last-li\"><a href=\"/special/map/\" target=\"_blank\">来院路线</a></li>");
document.writeln("                                </ol>");
document.writeln("                                <span>门诊时间：08:00-17:00 上海市黄兴路286号</span>");
document.writeln("                        </div>");
document.writeln("                </div>");
document.writeln("                <!--header-->");
document.writeln("                <div id=\"header\"></div>");
document.writeln("                <!--nav-->");
document.writeln("                <div id=\"nav\">");
document.writeln("                        <ul>");
document.writeln("                                <li><a href=\"/\" target=\"_blank\">首页</a></li>");
document.writeln("                                <li><a href=\"/special/yyjs/\" target=\"_blank\">医院简介</a></li>");
document.writeln("                                <li>");
document.writeln("                                        <span>重点科室</span>");
document.writeln("                                        <div>");
document.writeln("                                                <ol>");
document.writeln("                                                        <li><em></em><a href=\"http://mr.skinjc.com/\" target=\"_blank\">医疗美容科</a></li>");
document.writeln("                                                        <li><em></em><a href=\"http://zhifa.skinjc.com/\" target=\"_blank\">植发科</a></li>");
document.writeln("                                                        <li><em></em><a href=\"http://npx.skinjc.com/\" target=\"_blank\">银屑病门诊</a></li>");
document.writeln("                                                        <li><em></em><a href=\"http://jcbdf.skinjc.com/\" target=\"_blank\">白癜风门诊</a></li>");
document.writeln("                                                        <li><em></em><a href=\"http://xb.skinjc.com/\" target=\"_blank\">皮肤性病科</a></li>");
document.writeln("                                                </ol>");
document.writeln("                                                <ul>");
document.writeln("                                                        <li><em></em><a href=\"http://qcd.skinjc.com/\" target=\"_blank\">青春痘门诊</a></li>");
document.writeln("                                                        <li><em></em><a href=\"http://tf.skinjc.com/\" target=\"_blank\">脱发门诊</a></li>");
document.writeln("                                                        <li><em></em><a href=\"http://yc.skinjc.com/\" target=\"_blank\">腋臭门诊</a></li>");
document.writeln("                                                        <li><em></em><a href=\"http://hzj.skinjc.com/\" target=\"_blank\">灰指甲门诊</a></li>");
document.writeln("                                                        <li><em></em><a href=\"/zt/tj/\" target=\"_blank\">胎记门诊</a></li>");
document.writeln("                                                </ul>");
document.writeln("                                        </div>");
document.writeln("                                </li>");
document.writeln("                                <li><a href=\"/special/zjzt/index.html\" target=\"_blank\">医生介绍</a></li>");
document.writeln("                                <li><a href=\"/special/yysb/\" target=\"_blank\">设备介绍</a></li>");
document.writeln("                                <li class=\"active\"><a href=\"/bingyoujiaoliu/yxb/\" target=\"_blank\">病友交流</a></li>");
document.writeln("                                <li><a href=\"/special/kbjl/\" target=\"_blank\">看病经历</a></li>");
document.writeln("                                <li class=\"active\"><a href=\"/zt/shgy/npxbb/\" target=\"_blank\"> 社会公益</a></li>");
document.writeln("                                <li><a href=\"/special/jcgk/\" target=\"_blank\">科研教育</a></li>");
document.writeln("                                <li><a href=\"/guahao/\" target=\"_blank\">自助挂号</a></li>");
document.writeln("                                <li><a href=\"/special/map/\" target=\"_blank\">来院路线</a></li>");
document.writeln("                        </ul>");
document.writeln("                </div>");