//JavaScript Document
/*********************************
 *rookie QQ:1123486116
 *rookie making
 *rookie Copyright
 **********************************/
document.writeln("		<style>");
document.writeln("                #lesson { padding: 20px 0 30px; background: #f3f3f3; border-top: 4px solid #006db8; }");
document.writeln("		#lesson .hd { border-bottom: 1px solid #d3d3d3; margin-bottom: 30px; }");
document.writeln("		#lesson .hd ul { clear: both;  *zoom: 1;width: 958px; margin: 0 auto; position: relative; }");
document.writeln("		#lesson .hd ul:after { clear: both; display: block; visibility: hidden; height: 0; line-height: 0; content: \"\"; font-size: 0; }");
document.writeln("		#lesson .hd li { float: left; margin-right: 30px; border-bottom: 2px solid transparent; margin-bottom: -1px; padding-bottom: 10px; font-size: 14px; color: #454545; font-weight: bold; }");
document.writeln("		#lesson .hd li.on { color: #ff7800; border-bottom-color: #ff7800; }");
document.writeln("		#lesson .hd a { width: 90px; height: 28px; background: #ff7800; color: #ffffff; text-align: center; line-height: 28px; border-radius: 100px; position: absolute; right: 0; bottom: 5px; }");
document.writeln("		#lesson .bd { width: 958px; height: 350px; overflow: hidden; margin: 0 auto; background: #ffffff; }");
document.writeln("		#lesson .bd li { height: 350px; overflow: hidden; position: relative; background: #ffffff; }");
document.writeln("		#lesson .bd li.lesson-two-li.on { background: url(\"images/lesson-public-nav.jpg\") center no-repeat; background-size: 100% 100%; }");
document.writeln("		#lesson .bd li.lesson-two-li a { height: 100%; position: absolute; top: 0; }");
document.writeln("		#lesson .bd li.lesson-two-li a.lesson-public-a1 { width: 135px; left: 0; }");
document.writeln("		#lesson .bd li.lesson-two-li a.lesson-public-a2 { width: 202px; left: 139px; }");
document.writeln("		#lesson .bd li.lesson-two-li a.lesson-public-a3 { width: 202px; left: 345px; }");
document.writeln("		#lesson .bd li.lesson-two-li a.lesson-public-a4 { width: 202px; left: 551px; }");
document.writeln("		#lesson .bd li.lesson-two-li a.lesson-public-a5 { width: 201px; left: 757px; }");
document.writeln("		#lesson .bd li.lesson-thr-li div.lesson-thr-li-div { border-left: 1px solid #d6d5da; margin: 2px 0 0 26px; padding-top: 30px; height: 332px; }");
document.writeln("		#lesson .bd li.lesson-thr-li div.lesson-thr-li-div h2 { height: 24px; line-height: 24px; position: relative; }");
document.writeln("		#lesson .bd li.lesson-thr-li div.lesson-thr-li-div h2 em { font-size: 12px; color: #ffffff; position: absolute; height: 18px; width: 18px; left: -9px; top: 1px; text-align: center; line-height: 18px; font-weight: bold; }");
document.writeln("		#lesson .bd li.lesson-thr-li div.lesson-thr-li-div h2 em:after { content: \"\"; display: block; position: absolute; width: 0; height: 0; border: 9px solid transparent; }");
document.writeln("		#lesson .bd li.lesson-thr-li div.lesson-thr-li-div h2 strong { color: #ffffff; font-weight: bold; background: #035ea2; padding: 0 8px; margin-left: 15px; }");
document.writeln("		#lesson .bd li.lesson-thr-li div.lesson-thr-li-div h2 b { margin-left: 10px; background: #cccccc; border-radius: 5px; padding: 0 10px; }");
document.writeln("		#lesson .bd li.lesson-thr-li div.lesson-thr-li-div h2.lesson-thr-li-one-h2 em { background: #9b0000; }");
document.writeln("		#lesson .bd li.lesson-thr-li div.lesson-thr-li-div h2.lesson-thr-li-one-h2 em:after { border-top: 4px solid #9b0000; }");
document.writeln("		#lesson .bd li.lesson-thr-li div.lesson-thr-li-div h2.lesson-thr-li-two-h2 { margin-top: 20px; }");
document.writeln("		#lesson .bd li.lesson-thr-li div.lesson-thr-li-div h2.lesson-thr-li-two-h2 em { background: #cb6500; }");
document.writeln("		#lesson .bd li.lesson-thr-li div.lesson-thr-li-div h2.lesson-thr-li-two-h2 em:after { border-top: 4px solid #cb6500; }");
document.writeln("		#lesson .bd li.lesson-thr-li div.lesson-thr-li-div h2.lesson-thr-li-thr-h2 { margin-top: 20px; }");
document.writeln("		#lesson .bd li.lesson-thr-li div.lesson-thr-li-div h2.lesson-thr-li-thr-h2 em { background: #035ea2; }");
document.writeln("		#lesson .bd li.lesson-thr-li div.lesson-thr-li-div h2.lesson-thr-li-thr-h2 em:after { border-top: 4px solid #035ea2; }");
document.writeln("		#lesson .bd li.lesson-thr-li div.lesson-thr-li-div div { padding-left: 15px; }");
document.writeln("		#lesson .bd li.lesson-thr-li div.lesson-thr-li-div div span { font-size:12px; padding-right: 6px; border-right: 1px solid #000; margin: 8px 6px 0 0; }");
document.writeln("		#lesson .bd li.lesson-thr-li div.lesson-thr-li-div div span.lesson-thr-li-last-span { padding-right: 0; border-right: none; margin-right: 0; }");
document.writeln("		#lesson .bd li.lesson-thr-li div.lesson-thr-li-div div small { color: #035ea2; font-weight: bold; }");
document.writeln("		#lesson .bd li.lesson-thr-li div.lesson-thr-li-div div a.active { color: #ff0000; }");
document.writeln("		#lesson .bd li.lesson-fou-li div.lesson-thr-li-div h2.lesson-thr-li-one-h2 em { background: #9b0302; }");
document.writeln("		#lesson .bd li.lesson-fou-li div.lesson-thr-li-div h2.lesson-thr-li-one-h2 em:after { border-top: 4px solid #9b0302; }");
document.writeln("		#lesson .bd li.lesson-fou-li div.lesson-thr-li-div h2.lesson-thr-li-two-h2 { margin-top: 10px; }");
document.writeln("		#lesson .bd li.lesson-fou-li div.lesson-thr-li-div h2.lesson-thr-li-two-h2 em { background: #cb6501; }");
document.writeln("		#lesson .bd li.lesson-fou-li div.lesson-thr-li-div h2.lesson-thr-li-two-h2 em:after { border-top: 4px solid #cb6501; }");
document.writeln("		#lesson .bd li.lesson-fou-li div.lesson-thr-li-div h2.lesson-thr-li-thr-h2 { margin-top: 10px; }");
document.writeln("		#lesson .bd li.lesson-fou-li div.lesson-thr-li-div h2.lesson-thr-li-thr-h2 em { background: #006697; }");
document.writeln("		#lesson .bd li.lesson-fou-li div.lesson-thr-li-div h2.lesson-thr-li-thr-h2 em:after { border-top: 4px solid #006697; }");
document.writeln("		#lesson .bd li.lesson-fou-li div.lesson-thr-li-div h2.lesson-thr-li-fou-h2 { margin-top: 10px; }");
document.writeln("		#lesson .bd li.lesson-fou-li div.lesson-thr-li-div h2.lesson-thr-li-fou-h2 em { background: #990068; }");
document.writeln("		#lesson .bd li.lesson-fou-li div.lesson-thr-li-div h2.lesson-thr-li-fou-h2 em:after { border-top: 4px solid #990068; }");
document.writeln("		#lesson .bd li.lesson-fou-li div.lesson-thr-li-div h2.lesson-thr-li-fiv-h2 { margin-top: 10px; }");
document.writeln("		#lesson .bd li.lesson-fou-li div.lesson-thr-li-div h2.lesson-thr-li-fiv-h2 em { background: #006602; }");
document.writeln("		#lesson .bd li.lesson-fou-li div.lesson-thr-li-div h2.lesson-thr-li-fiv-h2 em:after { border-top: 4px solid #006602; }");
document.writeln("		#lesson .bd li.lesson-fiv-li span { position: absolute; top: 50%; margin-top: -41px; width: 29px; height: 83px; z-index: 8; cursor: pointer; }");
document.writeln("		#lesson .bd li.lesson-fiv-li span.lesson-fiv-prev { background: url(\"images/expert-prev.jpg\") center no-repeat; left: 0; }");
document.writeln("		#lesson .bd li.lesson-fiv-li span.lesson-fiv-next { background: url(\"images/expert-next.jpg\") center no-repeat; right: 0; }");
document.writeln("		#lesson .bd li.lesson-fiv-li .lesson-fiv-main { position: relative; width: 878px; margin: 0 auto; overflow: hidden; }");
document.writeln("		#lesson .bd li.lesson-fiv-li .lesson-fiv-main ol { clear: both;  *zoom: 1;width: 2000px; }");
document.writeln("		#lesson .bd li.lesson-fiv-li .lesson-fiv-main ol:after { clear: both; display: block; visibility: hidden; height: 0; line-height: 0; content: \"\"; font-size: 0; }");
document.writeln("		#lesson .bd li.lesson-fiv-li .lesson-fiv-main li { margin-right: 16px; width: 133px; float: left; }");
document.writeln("		#lesson .bd li.lesson-fiv-li .lesson-fiv-main li div { margin-top: 12px; }");
document.writeln("		#lesson .bd li.lesson-fiv-li .lesson-fiv-main p { font-size: 12px; padding-top: 4px; text-align: center; }");
document.writeln("		#lesson .bd li.lesson-fiv-li .lesson-fiv-main img { width: 133px; height: 143px; }");
document.writeln("		#lesson .bd li.lesson-six-li { clear: both;  *zoom: 1;}");
document.writeln("		#lesson .bd li.lesson-six-li:after { clear: both; display: block; visibility: hidden; height: 0; line-height: 0; content: \"\"; font-size: 0; }");
document.writeln("		#lesson .bd li.lesson-six-li a { float: left; margin: 21px 0 0 20px; }");
document.writeln("		#lesson .bd li.lesson-sev-li.on { background: url(\"images/lesson-sev-li-bg.jpg\") center no-repeat; background-size: 100% 100%; }");
document.writeln("                </style>");


document.writeln("                <div id=\"lesson\">");
document.writeln("                        <div class=\"hd\">");
document.writeln("                                <ul>");
document.writeln("                                        <li class=\"on\">自助挂号</li>");
document.writeln("                                        <li>公益导航</li>");
document.writeln("                                        <li>疾病导航</li>");
document.writeln("                                        <li>技术设备</li>");
document.writeln("                                        <li>医生导航</li>");
document.writeln("                                        <li>媒体关注</li>");
document.writeln("                                        <li>授权宣传同意书</li>");
document.writeln("                                        <a href=\"\" target=\"/special/jcgk/\">公开课</a>");
document.writeln("                                </ul>");
document.writeln("                        </div>");
document.writeln("                        <div class=\"bd\">");
document.writeln("                                <ul>");
document.writeln("                                        <!--自助挂号-->");
document.writeln("                                        <li><script type=\"text/javascript\" src=\"js/guahao.js\"></script></li>");
document.writeln("                                        <!--公益导航-->");
document.writeln("                                        <li class=\"lesson-two-li\">");
document.writeln("                                                <a class=\"lesson-public-a1\" href=\"/zt/shgy/cgz1/\" target=\"_blank\"></a>");
document.writeln("                                                <a class=\"lesson-public-a2\" href=\"/zt/shgy/xmny/\" target=\"_blank\"></a>");
document.writeln("                                                <a class=\"lesson-public-a3\" href=\"/zt/shgy/yuyao/\" target=\"_blank\"></a>");
document.writeln("                                                <a class=\"lesson-public-a4\" href=\"/zt/shgy/shequ/\" target=\"_blank\"></a>");
document.writeln("                                                <a class=\"lesson-public-a5\" href=\"/zt/shgy/yxbr/\" target=\"_blank\"></a>");
document.writeln("                                        </li>");
document.writeln("                                        <!--疾病导航-->");
document.writeln("                                        <li class=\"lesson-thr-li\">");
document.writeln("                                                <div class=\"lesson-thr-li-div\">");
document.writeln("                                                        <h2 class=\"lesson-thr-li-one-h2\"><em>病</em><strong>皮肤病</strong><b>二楼</b></h2>");
document.writeln("                                                        <div>");
document.writeln("                                                                <span><a href=\"http://jcbdf.skinjc.com\" target=\"_blank\">白癜风</a></span>");
document.writeln("                                                                <span><a class=\"active\" href=\"/special/npxzt/\" target=\"_blank\">牛皮癣</a></span>");
document.writeln("                                                                <span><a href=\"/special/pyxzt/\" target=\"_blank\">皮炎</a></span>");
document.writeln("                                                                <span><a href=\"/special/szzt/\" target=\"_blank\">湿疹</a></span>");
document.writeln("                                                                <span><a href=\"/special/xmz/\" target=\"_blank\">荨麻疹</a></span>");
document.writeln("                                                                <span><a href=\"/special/ylb_zwj/\" target=\"_blank\">鱼鳞病</a></span>");
document.writeln("                                                                <span><a class=\"active\" href=\"/special/hzjxzt_01/\" target=\"_blank\">灰指甲</a></span>");
document.writeln("                                                                <span><a href=\"/special/yczt/\" target=\"_blank\">腋臭</a></span>");
document.writeln("                                                                <span><a href=\"/hongbanlangcuang/\" target=\"_blank\">红斑狼疮</a></span>");
document.writeln("                                                                <span><a href=\"/dianxinganli/201109071427.html\" target=\"_blank\">毛囊炎</a></span>");
document.writeln("                                                                <span><a href=\"/jiechuang/\" target=\"_blank\">疥疮</a></span>");
document.writeln("                                                                <span><a href=\"/special/bpy/\" target=\"_blank\">扁平疣</a></span>");
document.writeln("                                                                <span><a href=\"/jiaoqi/\" target=\"_blank\">脚气</a></span>");
document.writeln("                                                                <span><a href=\"/pifuxianb/\" target=\"_blank\">皮肤癣</a></span>");
document.writeln("                                                                <span class=\"lesson-thr-li-last-span\"><a class=\"active\" href=\"/special/gmxzd/\" target=\"_blank\">过敏性紫癜</a></span>");
document.writeln("                                                        </div>");
document.writeln("                                                        <h2 class=\"lesson-thr-li-two-h2\"><em>美</em><strong>美容整形</strong><b>一楼</b></h2>");
document.writeln("                                                        <div>");
document.writeln("                                                                <p>");
document.writeln("                                                                        <small>疤痕中心：</small>");
document.writeln("                                                                        <span><a href=\"/special/bhzt/\" target=\"_blank\">烧伤性疤痕(美观改良，恢复功能)</a></span>");
document.writeln("                                                                        <span><a href=\"/special/bhzt/\" target=\"_blank\">破腹产疤痕</a></span>");
document.writeln("                                                                        <span><a href=\"/special/bhzt/\" target=\"_blank\">外伤疤痕</a></span>");
document.writeln("                                                                        <span><a href=\"/special/bhzt/\" target=\"_blank\">萎缩性疤痕</a></span>");
document.writeln("                                                                        <span><a href=\"/special/bhzt/\" target=\"_blank\">增生性疤痕</a></span>");
document.writeln("                                                                        <span class=\"lesson-thr-li-last-span\"><a href=\"/special/bhzt/\" target=\"_blank\">疤痕疙瘩</a></span>");
document.writeln("                                                                </p>");
document.writeln("                                                                <p>");
document.writeln("                                                                        <small>微整形中心：</small>");
document.writeln("                                                                        <span><a href=\"http://mr.skinjc.com/zt/chuzhou/\" target=\"_blank\">除皱</a></span>");
document.writeln("                                                                        <span><a href=\"http://mr.skinjc.com/zt/mbzt/\" target=\"_blank\">美白</a></span>");
document.writeln("                                                                        <span><a href=\"http://mr.skinjc.com/zt/bns/\" target=\"_blank\">玻尿酸</a></span>");
document.writeln("                                                                        <span><a href=\"http://mr.skinjc.com/zt/slz/\" target=\"_blank\">肉毒素</a></span>");
document.writeln("                                                                        <span><a href=\"http://mr.skinjc.com/zt/slz/\" target=\"_blank\">瘦脸针</a></span>");
document.writeln("                                                                        <span><a href=\"http://mr.skinjc.com/zt/mbzt/\" target=\"_blank\">美白针</a></span>");
document.writeln("                                                                        <span><a href=\"http://mr.skinjc.com/zt/syp/\" target=\"_blank\">双眼皮</a></span>");
document.writeln("                                                                        <span><a href=\"http://mr.skinjc.com/zt/lb/\" target=\"_blank\">隆鼻</a></span>");
document.writeln("                                                                        <span class=\"lesson-thr-li-last-span\"><a class=\"active\" href=\"/special/bjzx/\" target=\"_blank\">包皮整形</a></span>");
document.writeln("");
document.writeln("                                                                </p>");
document.writeln("                                                                <p>");
document.writeln("                                                                        <small>手足畸形：</small>");
document.writeln("                                                                        <span><a href=\"/special/szqx/\" target=\"_blank\">多指</a></span>");
document.writeln("                                                                        <span><a href=\"/special/szqx/\" target=\"_blank\">并指</a></span>");
document.writeln("                                                                        <span><a href=\"/special/szqx/\" target=\"_blank\">短指</a></span>");
document.writeln("                                                                        <span class=\"lesson-thr-li-last-span\"><a href=\"/special/szqx/\" target=\"_blank\">手指弯曲</a></span>");
document.writeln("                                                                </p>");
document.writeln("                                                                <p>");
document.writeln("                                                                        <small>毛发中心：</small>");
document.writeln("                                                                        <span><a href=\"/special/tfxzt/\" target=\"_blank\">脱发</a></span>");
document.writeln("                                                                        <span><a class=\"active\" href=\"http://zhifa.skinjc.com/\" target=\"_blank\">植发</a></span>");
document.writeln("                                                                        <span class=\"lesson-thr-li-last-span\"><a href=\"http://mr.skinjc.com/zt/tuomao/\" target=\"_blank\">脱毛</a></span>");
document.writeln("                                                                </p>");
document.writeln("                                                                <p>");
document.writeln("                                                                        <small>祛红中心：</small>");
document.writeln("                                                                        <span><a class=\"active\" href=\"/zt/xglzt/\" target=\"_blank\">血管瘤</a></span>");
document.writeln("                                                                        <span><a class=\"active\" href=\"/special/hxs/\" target=\"_blank\">红血丝</a></span>");
document.writeln("                                                                        <span><a href=\"/zt/tj/\" target=\"_blank\">胎记</a></span>");
document.writeln("                                                                        <span class=\"lesson-thr-li-last-span\"><a href=\"/special/jzb/\" target=\"_blank\">酒糟鼻</a></span>");
document.writeln("                                                                </p>");
document.writeln("                                                                <p>");
document.writeln("                                                                        <small>青春期皮肤门诊：</small>");
document.writeln("                                                                        <span><a class=\"active\" href=\"/zt/wyq\" target=\"_blank\">青春痘</a></span>");
document.writeln("                                                                        <span><a href=\"/special/dyzt/\" target=\"_blank\">痘印</a></span>");
document.writeln("                                                                        <span><a href=\"/special/queban/\" target=\"_blank\">雀斑</a></span>");
document.writeln("                                                                        <span class=\"lesson-thr-li-last-span\"><a href=\"http://mr.skinjc.com/zt/hyq/\" target=\"_blank\">黑眼圈</a></span>");
document.writeln("                                                                </p>");
document.writeln("                                                                <p>");
document.writeln("                                                                        <small>类更年期皮肤门诊：</small>");
document.writeln("                                                                        <span><a href=\"http://mr.skinjc.com/zt/chuzhou/\" target=\"_blank\">皱纹(抬头纹、鱼尾纹)</a></span>");
document.writeln("                                                                        <span><a href=\"http://mr.skinjc.com/zt/qbzt/\" target=\"_blank\">黄褐斑</a></span>");
document.writeln("                                                                        <span class=\"lesson-thr-li-last-span\"><a href=\"http://mr.skinjc.com/zt/qbzt/\" target=\"_blank\">色斑</a></span>");
document.writeln("                                                                </p>");
document.writeln("                                                        </div>");
document.writeln("                                                        <h2 class=\"lesson-thr-li-thr-h2\"><em>性</em><strong>皮肤性病</strong><b>三楼</b></h2>");
document.writeln("                                                        <div>");
document.writeln("                                                                <span><a class=\"active\" href=\"http://xb.skinjc.com/zt/jysy/\" target=\"_blank\">尖锐湿疣</a></span>");
document.writeln("                                                                <span><a href=\"http://xb.skinjc.com/zt/szbz/\" target=\"_blank\">生殖器疱疹</a></span>");
document.writeln("                                                                <span><a href=\"http://xb.skinjc.com/\" target=\"_blank\">软下疳</a></span>");
document.writeln("                                                                <span><a href=\"http://xb.skinjc.com/\" target=\"_blank\">非淋</a></span>");
document.writeln("                                                                <span><a href=\"http://xb.skinjc.com/\" target=\"_blank\">梅毒</a></span>");
document.writeln("                                                                <span><a href=\"http://xb.skinjc.com/\" target=\"_blank\">淋病</a></span>");
document.writeln("                                                                <span><a href=\"http://xb.skinjc.com/\" target=\"_blank\">阴虱</a></span>");
document.writeln("                                                                <span class=\"lesson-thr-li-last-span\"><a href=\"http://xb.skinjc.com/\" target=\"_blank\">性淋巴肉芽肿</a></span>");
document.writeln("                                                        </div>");
document.writeln("                                                </div>");
document.writeln("                                        </li>");
document.writeln("                                        <!--技术设备-->");
document.writeln("                                        <li class=\"lesson-thr-li lesson-fou-li\">");
document.writeln("                                                <div class=\"lesson-thr-li-div\">");
document.writeln("                                                        <h2 class=\"lesson-thr-li-one-h2\"><em>皮</em><strong>皮肤病技术设备</strong></h2>");
document.writeln("                                                        <div>");
document.writeln("                                                                <span><a href=\"/spec/uvbzt/\" target=\"_blank\">311窄谱UVB皮肤病治疗仪</a></span>");
document.writeln("                                                                <span><a href=\"/spec/ylqx/\" target=\"_blank\">308nm准分子激光</a></span>");
document.writeln("                                                                <span><a href=\"/special/equipment/\" target=\"_blank\">过敏原检测仪</a></span>");
document.writeln("                                                                <span><a href=\"/xianjinsheb/201306282028.html\" target=\"_blank\">BY-Ⅱ型表皮移植白癜风治疗仪</a></span>");
document.writeln("                                                                <span><a href=\"/xianjinsheb/08929103017715.shtml\" target=\"_blank\">中药熏蒸机</a></span>");
document.writeln("                                                                <span><a href=\"/tesezhiliao/098311539586048.shtml\" target=\"_blank\">中药倒膜</a></span>");
document.writeln("                                                                <span><a href=\"/xianjinsheb/201306082018.html\" target=\"_blank\">中药汤剂包装机</a></span>");
document.writeln("                                                                <span class=\"lesson-thr-li-last-span\"><a href=\"/xianjinsheb/201305271965.html\" target=\"_blank\">中药自动煎药机</a></span>");
document.writeln("                                                        </div>");
document.writeln("                                                        <h2 class=\"lesson-thr-li-two-h2\"><em>发</em><strong>毛发技术设备</strong></h2>");
document.writeln("                                                        <div>");
document.writeln("                                                                <span><a href=\"/xianjinsheb/201104111379.html\" target=\"_blank\">毛发显微检测仪</a></span>");
document.writeln("                                                                <span><a href=\"/xianjinsheb/201210301674.html\" target=\"_blank\">毛发智能分析系统</a></span>");
document.writeln("                                                                <span><a href=\"/xianjinsheb/201208011561.html\" target=\"_blank\">Car-光子生发仪</a></span>");
document.writeln("                                                                <span><a href=\"/xianjinsheb/201304231765.html\" target=\"_blank\">\"龙卷风\"生发仪</a></span>");
document.writeln("                                                                <span><a href=\"/xianjinsheb/201208151588.html\" target=\"_blank\">Derma 670生发仪</a></span>");
document.writeln("                                                                <span class=\"lesson-thr-li-last-span\"><a href=\"/xianjinsheb/201304021756.html\" target=\"_blank\">FUE毛囊单位提取机</a></span>");
document.writeln("                                                        </div>");
document.writeln("                                                        <h2 class=\"lesson-thr-li-thr-h2\"><em>美</em><strong>皮肤美容技术设备</strong></h2>");
document.writeln("                                                        <div>");
document.writeln("                                                                <span><a href=\"/xianjinsheb/201304291770.html\" target=\"_blank\">激光脱毛机</a></span>");
document.writeln("                                                                <span><a href=\"/xianjinsheb/201209281639.html\" target=\"_blank\">人脸检测系统</a></span>");
document.writeln("                                                                <span><a href=\"/xianjinsheb/105921222636.shtml\" target=\"_blank\">微晶磨皮术</a></span>");
document.writeln("                                                                <span><a href=\"/xianjinsheb/201308172362.html\" target=\"_blank\">动力蓝光</a></span>");
document.writeln("                                                                <span><a href=\"/xianjinsheb/089291035198294.shtml\" target=\"_blank\">JH－100型氦氖激光治疗机</a></span>");
document.writeln("                                                                <span><a href=\"/xianjinsheb/08927131124531.shtml\" target=\"_blank\">QK全科治疗仪</a></span>");
document.writeln("                                                                <span><a href=\"/xianjinsheb/201111111439.html\" target=\"_blank\">点阵激光</a></span>");
document.writeln("                                                                <span><a href=\"/dianbuolapi/105171117527118.shtml\" target=\"_blank\">电波拉皮</a></span>");
document.writeln("                                                                <span><a href=\"/xianjinsheb/10592110255634.shtml\" target=\"_blank\">无针美塑治疗仪</a></span>");
document.writeln("                                                                <span><a href=\"/xianjinsheb/201204191480.html\" target=\"_blank\">595脉冲染料激光仪</a></span>");
document.writeln("                                                                <span><a href=\"/special/hlww/\" target=\"_blank\">黑脸娃娃治疗仪</a></span>");
document.writeln("                                                                <span><a href=\"/pifumeirong/1055163579836.shtml\" target=\"_blank\">雅光射频除皱</a></span>");
document.writeln("                                                                <span><a href=\"/xianjinsheb/1059204032492.shtml\" target=\"_blank\">彩光嫩肤治疗仪</a></span>");
document.writeln("                                                                <span><a href=\"/pifumeirong/105282058103372.shtml\" target=\"_blank\">玻尿酸</a></span>");
document.writeln("                                                                <span class=\"lesson-thr-li-last-span\"><a href=\"http://mr.skinjc.com/zt/slz/\" target=\"_blank\">肉毒素注射</a></span>");
document.writeln("                                                        </div>");
document.writeln("                                                        <h2 class=\"lesson-thr-li-fou-h2\"><em>性</em><strong>皮肤性病技术设备</strong></h2>");
document.writeln("                                                        <div>");
document.writeln("                                                                <span><a href=\"/xianjinsheb/201309052424.html\" target=\"_blank\">ALA-PDT艾拉光动力治疗仪</a></span>");
document.writeln("                                                                <span><a href=\"/xianjinsheb/201309042423.html\" target=\"_blank\">WM-III型推车式微米光治疗仪</a></span>");
document.writeln("                                                                <span class=\"lesson-thr-li-last-span\"><a href=\"/xianjinsheb/201309042422.html\" target=\"_blank\">OKW-IC型奥克微柜式微波治疗机</a></span>");
document.writeln("                                                        </div>");
document.writeln("                                                        <h2 class=\"lesson-thr-li-fiv-h2\"><em>甲</em><strong>灰指甲技术设备</strong></h2>");
document.writeln("                                                        <div>");
document.writeln("                                                                <span><a href=\"/tesezhiliao/089181550552022.shtml\" target=\"_blank\">软化渗透疗法</a></span>");
document.writeln("                                                                <span class=\"lesson-thr-li-last-span\"><a href=\"/xianjinsheb/201308062340.html\" target=\"_blank\">CoolTouch点阵激光</a></span>");
document.writeln("                                                        </div>");
document.writeln("                                                </div>");
document.writeln("                                        </li>");
document.writeln("                                        <!--医生导航-->");
document.writeln("                                        <li class=\"lesson-fiv-li\">");
document.writeln("                                                <span class=\"lesson-fiv-prev\"></span>");
document.writeln("                                                <span class=\"lesson-fiv-next\"></span>");
document.writeln("                                                <div class=\"lesson-fiv-main\">");
document.writeln("                                                        <ol>");
document.writeln("                                                                <li>");
document.writeln("                                                                        <div>");
document.writeln("                                                                                <a href=\"/special/zjzt/index2.html\" target=\"_blank\"><img src=\"images/lesson-fiv-expert1-1.jpg\" alt=\"\"/></a>");
document.writeln("                                                                                <p>顾昌林 主任医师</p>");
document.writeln("                                                                        </div>");
document.writeln("                                                                        <div>");
document.writeln("                                                                                <a href=\"/special/zjzt/index11.html\" target=\"_blank\"><img src=\"images/lesson-fiv-expert1-2.jpg\" alt=\"\"/></a>");
document.writeln("                                                                                <p>林柳益 主治医师</p>");
document.writeln("                                                                        </div>");
document.writeln("                                                                </li>");
document.writeln("                                                                <li>");
document.writeln("                                                                        <div>");
document.writeln("                                                                                <a href=\"/special/zjzt/index.html\" target=\"_blank\"><img src=\"images/lesson-fiv-expert2-1.jpg\" alt=\"\"/></a>");
document.writeln("                                                                                <p>吴玉琴 皮肤科主任</p>");
document.writeln("                                                                        </div>");
document.writeln("                                                                        <div>");
document.writeln("                                                                                <a href=\"/special/zjzt/index14.html\" target=\"_blank\"><img src=\"images/lesson-fiv-expert2-2.jpg\" alt=\"\"/></a>");
document.writeln("                                                                                <p>陆辉群 特聘专家</p>");
document.writeln("                                                                        </div>");
document.writeln("                                                                </li>");
document.writeln("                                                                <li>");
document.writeln("                                                                        <div>");
document.writeln("                                                                                <a href=\"/special/zjzt/index3.html\" target=\"_blank\"><img src=\"images/lesson-fiv-expert3-1.jpg\" alt=\"\"/></a>");
document.writeln("                                                                                <p>李正森 主任</p>");
document.writeln("                                                                        </div>");
document.writeln("                                                                        <div>");
document.writeln("                                                                                <a href=\"/special/zjzt/index17.html\" target=\"_blank\"><img src=\"images/lesson-fiv-expert3-2.jpg\" alt=\"\"/></a>");
document.writeln("                                                                                <p>罗兰珍 主治医师</p>");
document.writeln("                                                                        </div>");
document.writeln("                                                                </li>");
document.writeln("                                                                <li>");
document.writeln("                                                                        <div>");
document.writeln("                                                                                <a href=\"/special/zjzt/index7.html\" target=\"_blank\"><img src=\"images/lesson-fiv-expert4-1.jpg\" alt=\"\"/></a>");
document.writeln("                                                                                <p>夏 风 主治医师</p>");
document.writeln("                                                                        </div>");
document.writeln("                                                                        <div>");
document.writeln("                                                                                <a href=\"/special/zjzt/xj/\" target=\"_blank\"><img src=\"images/lesson-fiv-expert4-2.jpg\" alt=\"\"/></a>");
document.writeln("                                                                                <p>肖军 主治医师</p>");
document.writeln("                                                                        </div>");
document.writeln("                                                                </li>");
document.writeln("                                                                <li>");
document.writeln("                                                                        <div>");
document.writeln("                                                                                <a href=\"/special/zjzt/index5.html\" target=\"_blank\"><img src=\"images/lesson-fiv-expert5-1.jpg\" alt=\"\"/></a>");
document.writeln("                                                                                <p>郭 晔 主治医师</p>");
document.writeln("                                                                        </div>");
document.writeln("                                                                        <div>");
document.writeln("                                                                                <a href=\"/special/zjzt/zyh/\" target=\"_blank\"><img src=\"images/lesson-fiv-expert5-2.jpg\" alt=\"\"/></a>");
document.writeln("                                                                                <p>赵宇辉 主任医师</p>");
document.writeln("                                                                        </div>");
document.writeln("                                                                </li>");
document.writeln("                                                                <li>");
document.writeln("                                                                        <div>");
document.writeln("                                                                                <a href=\"/special/zjzt/index4.html\" target=\"_blank\"><img src=\"images/lesson-fiv-expert6-1.jpg\" alt=\"\"/></a>");
document.writeln("                                                                                <p>李衡华 植发科主任</p>");
document.writeln("                                                                        </div>");
document.writeln("                                                                        <div>");
document.writeln("                                                                                <a href=\"/special/zjzt/lxf/\" target=\"_blank\"><img src=\"images/lesson-fiv-expert6-2.jpg\" alt=\"\"/></a>");
document.writeln("                                                                                <p>李秀芬 主治中医师</p>");
document.writeln("                                                                        </div>");
document.writeln("                                                                </li>");
document.writeln("                                                                <li>");
document.writeln("                                                                        <div>");
document.writeln("                                                                                <a href=\"/special/zjzt/lyy/\" target=\"_blank\"><img src=\"images/lesson-fiv-expert7-1.jpg\" alt=\"\"/></a>");
document.writeln("                                                                                <p>刘毅勇 主治医师</p>");
document.writeln("                                                                        </div>");
document.writeln("                                                                        <div>");
document.writeln("                                                                                <a href=\"/special/zjzt/lll/\" target=\"_blank\"><img src=\"images/lesson-fiv-expert7-2.jpg\" alt=\"\"/></a>");
document.writeln("                                                                                <p>缪立莲 主治医师</p>");
document.writeln("                                                                        </div>");
document.writeln("                                                                </li>");
document.writeln("                                                        </ol>");
document.writeln("                                                </div>");
document.writeln("                                        </li>");
document.writeln("                                        <!--媒体关注-->");
document.writeln("                                        <li class=\"lesson-six-li\">");
document.writeln("                                                <a href=\"/meitibaodao/201012211318.shtml\" target=\"_blank\"><img src=\"images/1.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/yiyuanjians/201010161293.html\" target=\"_blank\"><img src=\"images/2.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/meitibaodao/201012211326.shtml\" target=\"_blank\"><img src=\"images/3.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/meitibaodao/201012211332.shtml\" target=\"_blank\"><img src=\"images/4.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/meitibaodao/201012211319.shtml\" target=\"_blank\"><img src=\"images/5.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/meitibaodao/201012211325.shtml\" target=\"_blank\"><img src=\"images/6.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/meitibaodao/201012211324.shtml\" target=\"_blank\"><img src=\"images/7.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/yiyuanjians/201104261389.html\" target=\"_blank\"><img src=\"images/8.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/meitibaodao/201104131382.shtml\" target=\"_blank\"><img src=\"images/9.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/yiyuanjians/201104131380.html\" target=\"_blank\"><img src=\"images/10.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/yiyuanjians/201010161293.shtml\" target=\"_blank\"><img src=\"images/11.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/meitibaodao/201012211328.shtml\" target=\"_blank\"><img src=\"images/12.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/meitibaodao/201010281298.shtml\" target=\"_blank\"><img src=\"images/13.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/meitibaodao/201012281345.shtml\" target=\"_blank\"><img src=\"images/14.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/meitibaodao/201012221337.shtml\" target=\"_blank\"><img src=\"images/15.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/meitibaodao/201102251369.shtml\" target=\"_blank\"><img src=\"images/16.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/meitibaodao/201012211330.shtml\" target=\"_blank\"><img src=\"images/17.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/meitibaodao/201101071355.shtml\" target=\"_blank\"><img src=\"images/18.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/meitibaodao/201308082353.shtml\" target=\"_blank\"><img src=\"images/19.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/meitibaodao/201012211327.shtml\" target=\"_blank\"><img src=\"images/20.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/meitibaodao/201102251370.shtml\" target=\"_blank\"><img src=\"images/21.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/meitibaodao/201012281343.shtml\" target=\"_blank\"><img src=\"images/22.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/meitibaodao/201102251368.shtml\" target=\"_blank\"><img src=\"images/23.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/meitibaodao/201012311349.shtml\" target=\"_blank\"><img src=\"images/24.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/meitibaodao/201101071353.shtml\" target=\"_blank\"><img src=\"images/25.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/meitibaodao/201012211333.shtml\" target=\"_blank\"><img src=\"images/26.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/meitibaodao/201012311346.shtml\" target=\"_blank\"><img src=\"images/27.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/meitibaodao/201012211335.shtml\" target=\"_blank\"><img src=\"images/28.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/meitibaodao/201012281344.shtml\" target=\"_blank\"><img src=\"images/29.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/meitibaodao/201101051351.shtml\" target=\"_blank\"><img src=\"images/30.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/yiyuanjians/201011091112.shtml\" target=\"_blank\"><img src=\"images/31.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/meitibaodao/201101071354.shtml\" target=\"_blank\"><img src=\"images/32.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/meitibaodao/201012251340.shtml\" target=\"_blank\"><img src=\"images/33.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/meitibaodao/201012211321.shtml\" target=\"_blank\"><img src=\"images/34.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                                <a href=\"/meitibaodao/201012221338.shtml\" target=\"_blank\"><img src=\"images/35.gif\" height=\"44\" width=\"114\" alt=\"\" /></a>");
document.writeln("                                        </li>");
document.writeln("                                        <!--授权宣传同意书-->");
document.writeln("                                        <li class=\"lesson-sev-li\"></li>");
document.writeln("                                </ul>");
document.writeln("                        </div>");
document.writeln("                </div>");


$(function(){
        /*lesson*/
        jQuery("#lesson").slide({mainCell:".bd ul",effect:"fold",autoPlay:true,interTime:3000,startFun:function(index){
                $('#lesson .bd>ul>li').eq(index).addClass('on');
        }});
        /*lesson-fiv-li*/
        jQuery(".lesson-fiv-li").slide({prevCell:".lesson-fiv-prev",nextCell:".lesson-fiv-next",mainCell:".lesson-fiv-main ol",effect:"leftLoop",autoPlay:true,interTime:3000,vis:6});
});