document.writeln("<!--周华飞制作 QQ:1123486116-->");
document.writeln("<style>");
document.writeln("/*---------------------------------supervision---------------------------------------*/");
document.writeln(".supervision{ margin-top:80px;}");
document.writeln(".supervision ol{ height:40px; border-bottom:2px solid #e1e1e1;}");
document.writeln(".supervision ol li{ cursor:pointer; width:100px; height:100%; float:left; text-align:center; font-size:18px;}");
document.writeln(".supervision ol .li_active{ color:#0064b4;}");
document.writeln(".supervision ul{ overflow:hidden; margin:40px 0; display:none;}");
document.writeln(".supervision .ul_active{ display:block;}");
document.writeln(".supervision ul li{ width:95px; height:95px; float:left; margin-right:55px;}");
document.writeln(".supervision #line_threeeee{ transition:0.3s; width:100px; height:0px; position:relative; left:0px; top:40px; border-bottom:2px solid #0064b4;}");
document.writeln(".supervision .threeeee{ position:absolute; left:45px; top:-10px; width:0px; height:0px; border:5px solid; border-color:#fff #fff #0064b4 #fff;}");
document.writeln("/*---------------------------------footer---------------------------------------*/");
document.writeln(".footer{ background:#646464;}");
document.writeln(".footer .footer_content{ width:1000px; margin:0 auto;}");
document.writeln(".footer ul{ background:#4b4b4b; height:55px;}");
document.writeln(".footer li{ float:left;}");
document.writeln(".footer li a{ cursor:pointer; height:100%; width:125px; text-align:center; line-height:55px; color:#dcdcdc; font-size:20px;}");
document.writeln(".footer .a_active{ background:#0064b4; box-shadow:1px -1px 10px #fff;}");
document.writeln(".footer .address{ margin:50px auto 60px; overflow:hidden;}");
document.writeln(".footer .address_left{ width:250px;}");
document.writeln(".footer .address_center{ width:468px; border-left:1px solid #505050; border-right:1px solid #505050; padding:10px 35px;}");
document.writeln(".footer .address_center p{ font-size:16px; color:#dcdcdc; line-height:33px;}");
document.writeln(".footer .address_center em{ width:80px; line-height:33px;}");
document.writeln(".footer .address_right{ width:210px;}");
document.writeln(".footer .copyright{ background:#4b4b4b; padding:20px 0 15px;}");
document.writeln(".footer .copyright p{ text-align:center; line-height:25px; color:#dcdcdc; font-size:16px;}");
document.writeln("</style>");
document.writeln("<!----------------------------------supervision--------------------------------------->");
document.writeln("<div class=\"supervision commonWidth_1000\" id=\"supervision\">");
document.writeln("	<ol>");
document.writeln("                <div id=\"line_threeeee\"><div class=\"threeeee\"></div></div>");
document.writeln("        	<li>监督单位</li>");
document.writeln("        	<li>合作机构</li>");
document.writeln("        </ol>");
document.writeln("        <ul class=\"ul_active\">");
document.writeln("        	<li><a href=\"#\" target=\"_blank\"><img src=\"images/supervision1_1.png\" /></a></li>");
document.writeln("        	<li><a href=\"#\" target=\"_blank\"><img src=\"images/supervision2.png\" /></a></li>");
document.writeln("        	<li><a href=\"#\" target=\"_blank\"><img src=\"images/supervision3.png\" /></a></li>");
document.writeln("        	<li><a href=\"#\" target=\"_blank\"><img src=\"images/supervision4.png\" /></a></li>");
document.writeln("        	<li><a href=\"#\" target=\"_blank\"><img src=\"images/supervision5.png\" /></a></li>");
document.writeln("        	<li><a href=\"#\" target=\"_blank\"><img src=\"images/supervision6.png\" /></a></li>");
document.writeln("        	<li style=\"margin-right:0;\"><a href=\"#\" target=\"_blank\"><img src=\"images/supervision7.png\" /></a></li>");
document.writeln("        </ul>");
document.writeln("        <ul>");
document.writeln("        	<li><a href=\"#\" target=\"_blank\"><img src=\"images/supervision1_1.png\" /></a></li>");
document.writeln("        	<li><a href=\"#\" target=\"_blank\"><img src=\"images/supervision2.png\" /></a></li>");
document.writeln("        	<li><a href=\"#\" target=\"_blank\"><img src=\"images/supervision3.png\" /></a></li>");
document.writeln("        	<li><a href=\"#\" target=\"_blank\"><img src=\"images/supervision4.png\" /></a></li>");
document.writeln("        	<li><a href=\"#\" target=\"_blank\"><img src=\"images/supervision5.png\" /></a></li>");
document.writeln("        	<li><a href=\"#\" target=\"_blank\"><img src=\"images/supervision6.png\" /></a></li>");
document.writeln("        	<li style=\"margin-right:0;\"><a href=\"#\" target=\"_blank\"><img src=\"images/supervision7.png\" /></a></li>");
document.writeln("        </ul>");
document.writeln("</div>");
document.writeln("<!-----------------------------------footer------------------------------------------>");
document.writeln("<div class=\"footer commonWidth\">");
document.writeln("        <div class=\"footer_content\">");
document.writeln("                <ul id=\"footer_nav\">");
document.writeln("                        <li><a class=\"a_active\" href=\"/\">脱发种植</a></li>");
document.writeln("                        <li><a href=\"/\">发际线调整</a></li>");
document.writeln("                        <li><a href=\"/\">眉毛种植</a></li>");
document.writeln("                        <li><a href=\"/\">睫毛种植</a></li>");
document.writeln("                        <li><a href=\"/\">胡须种植</a></li>");
document.writeln("                        <li><a href=\"/\">鬓角种植</a></li>");
document.writeln("                        <li><a href=\"/\">美人尖种植</a></li>");
document.writeln("                        <li><a href=\"/\">比基尼种植</a></li>");
document.writeln("                </ul>");
document.writeln("                <div class=\"address\">");
document.writeln("                	<div class=\"address_left fl\">");
document.writeln("                        	<img src=\"images/footer.png\" />                        	");
document.writeln("                        </div>");
document.writeln("                	<div class=\"address_center fl\">");
document.writeln("                        	<p><em>医院地址：</em>上海市杨浦区黄兴路286号</p>");
document.writeln("                        	<p><em>植发电话：</em>021-6519  1999</p>");
document.writeln("                        	<p><em>温馨提示：</em>任何建议都不能替代执业医师当面诊断，所有门诊时间</p>");
document.writeln("                        	<p><em></em>仅供参考，最终以医院当日公布为准。</p>");
document.writeln("                        	<p>网友 、医生言论仅代表其个人观点，不代表本站同意其说法。</p>");
document.writeln("                        </div>");
document.writeln("                	<div class=\"address_right fr\">");
document.writeln("                        	<img src=\"images/footer_twoCode.png\" />");
document.writeln("                        </div>");
document.writeln("                </div>                                            ");
document.writeln("        </div>");
document.writeln("	<div class=\"copyright\">");
document.writeln("        	<p>沪卫（中医）网复审[2014]第10125号 沪ICP备13034821号</p>");
document.writeln("        	<p>Copyright (C) 2009 Jiangcheng Dermatology Hospital shanghai.</p>");
document.writeln("        </div>");
document.writeln("</div>");
document.writeln("<script>");
document.writeln("eventBind(window,\'load\',function()");
document.writeln("{");
document.writeln("	function navTab(obj,attr)");
document.writeln("	{");
document.writeln("		for(var i=0; i<obj.length; i++)");
document.writeln("		{");
document.writeln("			obj[i].onmouseover=function()");
document.writeln("			{");
document.writeln("				for(var i=0; i<obj.length; i++)");
document.writeln("				{");
document.writeln("					obj[i].className=\'\';	");
document.writeln("				}");
document.writeln("				this.className=attr;");
document.writeln("			}	");
document.writeln("		}");
document.writeln("		");
document.writeln("	}");
document.writeln("	/*supervision*/");
document.writeln("	var oSupervision=document.getElementById(\'supervision\');");
document.writeln("	var oSupervision_ol=oSupervision.getElementsByTagName(\'ol\')[0];");
document.writeln("	var aSupervision_ol_li=oSupervision_ol.getElementsByTagName(\'li\');");
document.writeln("	var oLine_threeeee=document.getElementById(\'line_threeeee\');");
document.writeln("	var aSupervision_one_ul=oSupervision.getElementsByTagName(\'ul\');");
document.writeln("	var oSupervision_one_ul=oSupervision.getElementsByTagName(\'ul\')[0];");
document.writeln("	var aSupervision_one_ul_img=oSupervision_one_ul.getElementsByTagName(\'img\');");
document.writeln("	var oSupervision_two_ul=oSupervision.getElementsByTagName(\'ul\')[1];");
document.writeln("	var aSupervision_two_ul_img=oSupervision_two_ul.getElementsByTagName(\'img\');");
document.writeln("	/*监督单位图片*/");
document.writeln("	var one_OldArr=[\'images/supervision1.png\',\'images/supervision2.png\',\'images/supervision3.png\',\'images/supervision4.png\',\'images/supervision5.png\',\'images/supervision6.png\',\'images/supervision7.png\'];");
document.writeln("	var one_NewArr=[\'images/supervision1_1.png\',\'images/supervision1_1.png\',\'images/supervision1_1.png\',\'images/supervision1_1.png\',\'images/supervision1_1.png\',\'images/supervision1_1.png\',\'images/supervision1_1.png\'];");
document.writeln("	/*合作伙伴图片*/");
document.writeln("	var two_OldArr=[\'images/supervision1.png\',\'images/supervision2.png\',\'images/supervision3.png\',\'images/supervision4.png\',\'images/supervision5.png\',\'images/supervision6.png\',\'images/supervision7.png\'];;");
document.writeln("	var two_NewArr=[\'images/supervision1_1.png\',\'images/supervision1_1.png\',\'images/supervision1_1.png\',\'images/supervision1_1.png\',\'images/supervision1_1.png\',\'images/supervision1_1.png\',\'images/supervision1_1.png\'];");
document.writeln("	/*监督单位以及合作伙伴滑块切换*/");
document.writeln("	for(var i=0; i<aSupervision_ol_li.length;i++)");
document.writeln("	{");
document.writeln("		aSupervision_ol_li[i].index=i;");
document.writeln("		aSupervision_ol_li[i].onmouseover=function()");
document.writeln("		{");
document.writeln("			for(var i=0; i<aSupervision_ol_li.length;i++)");
document.writeln("			{");
document.writeln("				aSupervision_one_ul[i].className=\'\';");
document.writeln("			}");
document.writeln("			aSupervision_one_ul[this.index].className=\'ul_active\';");
document.writeln("			oLine_threeeee.style.left=aSupervision_ol_li[0].offsetWidth*this.index+\'px\'	");
document.writeln("		}	");
document.writeln("	}");
document.writeln("	/*监督单位*/");
document.writeln("	for(var i=0; i<aSupervision_one_ul_img.length;i++)");
document.writeln("	{");
document.writeln("		aSupervision_one_ul_img[i].index=i;");
document.writeln("		aSupervision_one_ul_img[i].onmouseover=function()");
document.writeln("		{");
document.writeln("			for(var i=0; i<aSupervision_one_ul_img.length;i++)");
document.writeln("			{");
document.writeln("				aSupervision_one_ul_img[i].src=one_OldArr[i];");
document.writeln("			}");
document.writeln("			this.src=one_NewArr[this.index];");
document.writeln("		}	");
document.writeln("	}");
document.writeln("	/*合作伙伴*/");
document.writeln("	for(var i=0; i<aSupervision_two_ul_img.length;i++)");
document.writeln("	{");
document.writeln("		aSupervision_two_ul_img[i].index=i;");
document.writeln("		aSupervision_two_ul_img[i].onmouseover=function()");
document.writeln("		{");
document.writeln("			for(var i=0; i<aSupervision_two_ul_img.length;i++)");
document.writeln("			{");
document.writeln("				aSupervision_two_ul_img[i].src=two_OldArr[i];");
document.writeln("			}");
document.writeln("			this.src=two_NewArr[this.index];");
document.writeln("		}	");
document.writeln("	}");
document.writeln("	");
document.writeln("	/*footer_nav*/");
document.writeln("	var oFooter_nav=document.getElementById(\'footer_nav\');");
document.writeln("	var aFooter_a=oFooter_nav.getElementsByTagName(\'a\');");
document.writeln("	navTab(aFooter_a,\'a_active\');");
document.writeln("})");
document.writeln("function eventBind(obj,ev,fn)");
document.writeln("{");
document.writeln("	if(obj.attachEvent)");
document.writeln("	{");
document.writeln("		obj.attachEvent(\'on\'+ev,fn);");
document.writeln("	}");
document.writeln("	else");
document.writeln("	{");
document.writeln("		obj.addEventListener(ev,fn,false);");
document.writeln("	}	");
document.writeln("}");
document.writeln("</script>");
document.writeln("<!--周华飞制作 QQ:1123486116-->");