// JavaScript Document
document.writeln("<style>");
document.writeln("/*nav*/");
document.writeln("#nav{ height:40px; color:#fff; font-size:18px; background:#0aa0b4; line-height:1;}");
document.writeln("#nav #navMain{ width:1200px; margin:0 auto;}");
document.writeln("#nav dl{ width:241px; position:relative; z-index:4;}");
document.writeln("#nav dt{ text-indent:18px; line-height:40px; background:#00647f; position:relative;}");
document.writeln("#nav dt:after{ content:\"\"; display:block; width:22px; height:9px; background:url(/images/nav.png) left -324px no-repeat; position:absolute; right:23px; top:17px;}");
document.writeln("#nav dl:hover dt:after{ background:url(/images/nav.png) left -288px no-repeat;}");
document.writeln("#nav dd{ height:399px; width:100%; border-bottom:1px solid #e0e0e0; display:none; background:#f4f4f4; transition:0.4s; position:absolute; left:0; top:40px;}");
document.writeln("#nav dl:hover dd{ display:block;}");
document.writeln("#nav ul{ padding:24px 0 0 12px; height:109px; position:relative;}");
document.writeln("#nav ul.ul1,#nav ul.ul2{ height:108px; border-bottom:1px solid #e0e0e0;}");
document.writeln("#nav ul h2{ height:23px; line-height:21px; padding-left:29px; font-size:16px; font-weight:bold; color:#000; margin-bottom:14px; position:relative; transition:0.4s;}");
document.writeln("#nav ul h2:before{ content:\"\"; display:block; width:23px; height:23px; background:url(/images/nav.png) no-repeat; position:absolute; left:0; top:0; transition:0.4s;}");
document.writeln("#nav ul h2.icon1:before{ background-position:left 0;}");
document.writeln("#nav ul h2.icon2:before{ background-position:left -72px;}");
document.writeln("#nav ul h2.icon3:before{ background-position:left -144px;}");
document.writeln("#nav ul h2:after{ content:\"\"; display:block; width:14px; height:17px; background:url(/images/nav.png) left -252px; display:none; position:absolute; right:0; top:34px;}");
document.writeln("#nav ul a{ color:#656565; font-size:12px; margin:0 24px 12px 0; float:left;}");
document.writeln("#nav ul li{ width:921px; height:380px; padding:20px 0 0 38px; background:#f8f8f8; display:none; position:absolute; left:241px; top:0;}");
document.writeln("#nav ul.ul2 li{ top:-133px;}");
document.writeln("#nav ul.ul3 li{ top:-266px;}");
document.writeln("#nav ul.ul3 li div{ width:630px;}");
document.writeln("#nav ul li div{ width:300px; margin-right:30px;}");
document.writeln("#nav ul li span{ float:left; width:100%; border-bottom:1px dashed #999999; margin-bottom:22px; padding-bottom:5px;}");
document.writeln("#nav ul li h3{ font-size:14px; font-weight:bold; color:#000; margin-bottom:15px; line-height:1;}");
document.writeln("#nav ul li h3.fl{ margin-right:10px;}");
document.writeln("#nav ul li a{ margin:0 6px 12px 0;}");
document.writeln("#nav ul li a.reStyle{ margin:1px 6px 0 0;}");
document.writeln("#nav ul li strong{ width:232px; text-align:center; height:366px; line-height:366px; background:#000; color:#fff; font-size:20px; position:relative;}");
document.writeln("#nav ul li strong em.abtns{ position:absolute; right:0; top:0; z-index:3;}");
document.writeln("#nav ul li strong em.abtns i{ width:10px; height:10px; float:left; margin:5px; border-radius:50%; background:#dcdcdc; transition:0s;}");
document.writeln("#nav ul li strong em.abtns i.active{ background:#0aa0b4;}");
document.writeln("#nav ul li strong em.acuts{ width:100%; height:100%; position:relative;}");
document.writeln("#nav ul li strong em.acuts i{ width:100%; height:100%; opacity:0; filter:alpha(opacity:0); position:absolute; left:0; top:0;}");
document.writeln("#nav ul li strong em.acuts i.active{ opacity:1; filter:alpha(opacity:100); z-index:2;}");
document.writeln("#nav ul:hover{ background:#0cb1c7;}");
document.writeln("#nav ul:hover a{ color:#fff;}");
document.writeln("#nav ul:hover li a{ color:#656565;}");
document.writeln("#nav ul:hover li a:hover{ color:#017d8d;}");
document.writeln("#nav ul:hover a:hover{ text-decoration:underline;}");
document.writeln("#nav ul:hover h2{ color:#fff;}");
document.writeln("#nav ul:hover h2.icon1:before{ background-position:left -36px;}");
document.writeln("#nav ul:hover h2.icon2:before{ background-position:left -108px;}");
document.writeln("#nav ul:hover h2.icon3:before{ background-position:left -180px;}");
document.writeln("#nav ul:hover h2:after{ display:block;}");
document.writeln("#nav ul:hover li{ display:block;}");
document.writeln("#nav ol li{ float:left; width:137px; line-height:40px; text-align:center; position:relative;}");
document.writeln("#nav ol li a:after{ content:\"\"; display:block; width:2px; height:18px; background:url(/images/nav.png) left -216px no-repeat; position:absolute; right:0; top:13px; animation:circle 2s linear infinite; -webkit-animation:circle 2s linear infinite; z-index:2;}");
document.writeln("#nav ol li.last a:after{ display:none;}");
document.writeln("#nav ol li:hover{ background:#00647f;}");
document.writeln("#nav ol a{ color:#fff; display:block; line-height:40px;}");
document.writeln("</style>");
document.writeln("<div id=\"nav\">");
document.writeln("        <div id=\"navMain\" class=\"clearFix\">");
document.writeln("                <dl class=\"fl\">");
document.writeln("                        <dt>江城塑美项目导航</dt>");
document.writeln("                        <dd>");
document.writeln("                                <ul class=\"ul1\">");
document.writeln("                                        <h2 class=\"icon1\">整形美容中心</h2>");
document.writeln("                                        <a href=\"/zxzx/ybjd/\" target=\"_blank\">眼部精雕</a> <a href=\"/zhengxingmeirongzhongxin/bibusuxing/\" target=\"_blank\">鼻部塑形</a> <a href=\"/zhengxingmeirongzhongxin/shentisuxing/\" target=\"_blank\">身体塑形</a> <a href=\"/zhengxingmeirongzhongxin/zitizhifangyizhi/\" target=\"_blank\">自体脂肪移植</a> <a href=\"/zhengxingmeirongzhongxin/xiongbuzhengxing/\" target=\"_blank\">胸部整形</a> <a href=\"/zhengxingmeirongzhongxin/chunbuzhengxing/\" target=\"_blank\">唇部整形</a> <a href=\"/zhengxingmeirongzhongxin/miankuozhengxing/\" target=\"_blank\">面廓整形</a> <a href=\"/zhengxingmeirongzhongxin/erbuzhengxing/\" target=\"_blank\">耳部整形</a>");
document.writeln("                                        <li class=\"clearFix\">");
document.writeln("                                                <div class=\"fl\"> <span>");
document.writeln("                                                        <h3>眼部精雕:</h3>");
document.writeln("                                                        <a href=\"/zhengxingmeirongzhongxin/yanbujingdiao/shuangyanp/\" target=\"_blank\">双眼皮</a> <a href=\"/zhengxingmeirongzhongxin/yanbujingdiao/quyandai/\" target=\"_blank\">祛眼袋</a> <a href=\"/zhengxingmeirongzhongxin/yanbujingdiao/kaiyanjiao/\" target=\"_blank\">开眼角</a> <a href=\"/zhengxingmeirongzhongxin/yanbujingdiao/shangjianx/\" target=\"_blank\">上睑下垂</a> <a href=\"/zhengxingmeirongzhongxin/yanbujingdiao/hanshiwuhe/\" target=\"_blank\">韩式无痕提眉</a> <a href=\"/zhengxingmeirongzhongxin/yanbujingdiao/timeixuand/\" target=\"_blank\">提眉悬吊</a> <a href=\"/zhengxingmeirongzhongxin/yanbujingdiao/meibushuho/\" target=\"_blank\">眉部术后修复</a> <a href=\"/zhengxingmeirongzhongxin/yanbujingdiao/yanbushous/\" target=\"_blank\">眼部手术修复</a> </span> <span>");
document.writeln("                                                        <h3>身体塑形:</h3>");
document.writeln("                                                        <a href=\"/zhengxingmeirongzhongxin/shentisuxing/360shuidong/\" target=\"_blank\">360°水动力吸脂</a> <a href=\"/zhengxingmeirongzhongxin/shentisuxing/yaofubuxizh/\" target=\"_blank\">腰腹部吸脂</a> <a href=\"/zhengxingmeirongzhongxin/shentisuxing/tuibuxizhi/\" target=\"_blank\">腿部吸脂</a> <a href=\"/zhengxingmeirongzhongxin/shentisuxing/beibuxizhi/\" target=\"_blank\">背部吸脂</a> <a href=\"/zhengxingmeirongzhongxin/shentisuxing/tunbuxizhi/\" target=\"_blank\">臀部吸脂</a> <a href=\"/zhengxingmeirongzhongxin/shentisuxing/shoubixizhi/\" target=\"_blank\">手臂吸脂</a> <a href=\"/zhengxingmeirongzhongxin/shentisuxing/mianbuxizhi/\" target=\"_blank\">面部吸脂</a> <a href=\"/zhengxingmeirongzhongxin/shentisuxing/jingbusongc/\" target=\"_blank\">颈部松弛提拉</a> </span> <span>");
document.writeln("                                                        <h3>胸部整形:</h3>");
document.writeln("                                                        <a href=\"/zhengxingmeirongzhongxin/xiongbuzhengxing/jvrusuo/\" target=\"_blank\">巨乳缩小</a> <a href=\"/zhengxingmeirongzhongxin/xiongbuzhengxing/rufangx/\" target=\"_blank\">乳房下垂</a> <a href=\"/zhengxingmeirongzhongxin/xiongbuzhengxing/rutouru/\" target=\"_blank\">乳头乳晕</a> <a href=\"/zhengxingmeirongzhongxin/xiongbuzhengxing/zhengxi/\" target=\"_blank\">整形副乳切除术</a> <a href=\"/zhengxingmeirongzhongxin/xiongbuzhengxing/fengxio/\" target=\"_blank\">丰胸</a> </span> <span>");
document.writeln("                                                        <h3>面廓整形:</h3>");
document.writeln("                                                        <a href=\"/zhengxingmeirongzhongxin/miankuozhengxing/longmei/\" target=\"_blank\">隆眉弓</a> <a href=\"/zhengxingmeirongzhongxin/miankuozhengxing/longxia/\" target=\"_blank\">隆下巴</a> <a href=\"/zhengxingmeirongzhongxin/miankuozhengxing/qujiazh/\" target=\"_blank\">去颊脂</a> <a href=\"/zhengxingmeirongzhongxin/miankuozhengxing/dianqua/\" target=\"_blank\">垫颧骨</a> <a href=\"/zhengxingmeirongzhongxin/miankuozhengxing/quangon/\" target=\"_blank\">颧弓整形</a> <a href=\"/zhengxingmeirongzhongxin/miankuozhengxing/xiaheji/\" target=\"_blank\">下颌角整形</a> </span> </div>");
document.writeln("                                                <div class=\"fl\"> <span>");
document.writeln("                                                        <h3>鼻部塑形:</h3>");
document.writeln("                                                        <a href=\"/zhengxingmeirongzhongxin/bibusuxing/zitiruangulon/\" target=\"_blank\">自体软骨隆鼻</a> <a href=\"/zhengxingmeirongzhongxin/bibusuxing/bixiaozhuzhen/\" target=\"_blank\">鼻小柱整形</a> <a href=\"/zhengxingmeirongzhongxin/bibusuxing/jiatilongbi/\" target=\"_blank\">假体隆鼻</a> <a href=\"/zhengxingmeirongzhongxin/bibusuxing/biyisuoxiao/\" target=\"_blank\">鼻翼缩小</a> <a href=\"/zhengxingmeirongzhongxin/bibusuxing/longbixiufu/\" target=\"_blank\">隆鼻修复</a> <a href=\"/zhengxingmeirongzhongxin/bibusuxing/bijianzhengxi/\" target=\"_blank\">鼻尖整形</a> <a href=\"/zhengxingmeirongzhongxin/bibusuxing/waibijiaozhen/\" target=\"_blank\">歪鼻矫正</a> <a href=\"/zhengxingmeirongzhongxin/bibusuxing/yinggoubijiao/\" target=\"_blank\">鹰钩鼻矫正</a> </span> <span>");
document.writeln("                                                        <h3 class=\"fl\">自体脂肪移植:</h3>");
document.writeln("                                                        <a href=\"/zhengxingmeirongzhongxin/zitizhifangyizhi/fpgj/\" target=\"_blank\">自体脂肪丰苹果肌</a> <a href=\"/zhengxingmeirongzhongxin/zitizhifangyizhi/fc/\" target=\"_blank\">自体脂肪丰唇</a> <a href=\"/zhengxingmeirongzhongxin/zitizhifangyizhi/fxb/\" target=\"_blank\">自体脂肪丰下巴</a> <a href=\"/zhengxingmeirongzhongxin/zitizhifangyizhi/fmj/\" target=\"_blank\">自体脂肪丰面颊</a> <a href=\"/zhengxingmeirongzhongxin/zitizhifangyizhi/ftyx/\" target=\"_blank\">自体脂肪丰太阳穴</a> <a href=\"/zhengxingmeirongzhongxin/zitizhifangyizhi/fet/\" target=\"_blank\">自体脂肪丰额头</a> <a href=\"/zhengxingmeirongzhongxin/zitizhifangyizhi/lb/\" target=\"_blank\">自体脂肪隆鼻</a> </span> <span>");
document.writeln("                                                        <h3>唇部整形:</h3>");
document.writeln("                                                        <a href=\"/zhengxingmeirongzhongxin/chunbuzhengxing/tuchunxi/\" target=\"_blank\">兔唇修复</a> <a href=\"/zhengxingmeirongzhongxin/chunbuzhengxing/houchung/\" target=\"_blank\">厚唇改薄</a> </span> <span>");
document.writeln("                                                        <h3>耳部整形:</h3>");
document.writeln("                                                        <a href=\"/zhengxingmeirongzhongxin/erbuzhengxing/erzaizao/\" target=\"_blank\">耳再造</a> <a href=\"/zhengxingmeirongzhongxin/erbuzhengxing/fuerqiechu/\" target=\"_blank\">副耳切除</a> <a href=\"/zhengxingmeirongzhongxin/erbuzhengxing/beizhuange/\" target=\"_blank\">杯状耳</a> <a href=\"/zhengxingmeirongzhongxin/erbuzhengxing/zhaofenger/\" target=\"_blank\">招风耳</a> </span> </div>");
document.writeln("                                                <strong class=\"fl\"> <em class=\"abtns clearFix\"> <i class=\"active\"></i> <i></i> </em> <em class=\"acuts\"> <i class=\"active\"><img src=\"/userpic/201505/15/20150515_164239_780.jpg\" height=\"366\" width=\"232\"></i> <i><img src=\"/userpic/201505/15/20150515_164742_809.jpg\" height=\"366\" width=\"232\"></i> </em> </strong> </li>");
document.writeln("                                </ul>");
document.writeln("                                <ul class=\"ul2\">");
document.writeln("                                        <h2 class=\"icon2\">皮肤美容中心</h2>");
document.writeln("                                        <a href=\"/pifumeirongzhongxin/chuzhoujinfu/\" target=\"_blank\">除皱紧肤</a> <a href=\"/pifumeirongzhongxin/meibainenfu/\" target=\"_blank\">美白嫩肤</a> <a href=\"/pifumeirongzhongxin/wutongtuomao/\" target=\"_blank\">无痛脱毛</a> <a href=\"/pifumeirongzhongxin/yishuwenxiu/\" target=\"_blank\">艺术纹绣</a> <a href=\"/pifumeirongzhongxin/qubanquzhi/\" target=\"_blank\">祛斑祛痣</a> <a href=\"/pifumeirongzhongxin/bahenxiufu/\" target=\"_blank\">疤痕修复</a>");
document.writeln("                                        <li class=\"clearFix\">");
document.writeln("                                                <div class=\"fl\"> <span>");
document.writeln("                                                        <h3>除皱紧肤:</h3>");
document.writeln("                                                        <a href=\"/pifumeirongzhongxin/chuzhoujinfu/shenlanshepinjin/\" target=\"_blank\">射频紧肤</a> <a href=\"/pifumeirongzhongxin/chuzhoujinfu/yaofubusuxing/\" target=\"_blank\">腰腹部塑形</a> <a href=\"/pifumeirongzhongxin/chuzhoujinfu/yanzhouxiwen/\" target=\"_blank\">眼周细纹</a> <a href=\"/pifumeirongzhongxin/chuzhoujinfu/songchixiachui/\" target=\"_blank\">松弛下垂</a> <a href=\"/pifumeirongzhongxin/chuzhoujinfu/chanhouhuifu/\" target=\"_blank\">产后恢复</a> <a href=\"/pifumeirongzhongxin/chuzhoujinfu/mianbuzhouwen/\" target=\"_blank\">面部皱纹</a> <a href=\"/pifumeirongzhongxin/chuzhoujinfu/jingwen/\" target=\"_blank\">颈纹</a> </span> <span>");
document.writeln("                                                        <h3>无痛脱毛:</h3>");
document.writeln("                                                        <a href=\"/pifumeirongzhongxin/wutongtuomao/yaobeiduomao/\" target=\"_blank\">腰背多毛</a> <a href=\"/pifumeirongzhongxin/wutongtuomao/tuibutuomao/\" target=\"_blank\">腿部脱毛</a> <a href=\"/pifumeirongzhongxin/wutongtuomao/yexiatuomao/\" target=\"_blank\">腋下脱毛</a> <a href=\"/pifumeirongzhongxin/wutongtuomao/chunbutuomao/\" target=\"_blank\">唇部脱毛</a> <a href=\"/pifumeirongzhongxin/wutongtuomao/shoubituomao/\" target=\"_blank\">手臂脱毛</a> <a href=\"/pifumeirongzhongxin/wutongtuomao/bijinituomao/\" target=\"_blank\">比基尼脱毛</a> <a href=\"/pifumeirongzhongxin/wutongtuomao/luosaihu/\" target=\"_blank\">络腮胡</a> <a href=\"/pifumeirongzhongxin/wutongtuomao/fajixianxiuzheng/\" target=\"_blank\">发际线修整</a> </span> <span>");
document.writeln("                                                        <h3>美白嫩肤:</h3>");
document.writeln("                                                        <a href=\"/pifumeirongzhongxin/meibainenfu/maokongcuda/\" target=\"_blank\">毛孔粗大</a> <a href=\"/pifumeirongzhongxin/meibainenfu/quhongxuesi/\" target=\"_blank\">祛红血丝</a> <a href=\"/pifumeirongzhongxin/meibainenfu/quheiyanquan/\" target=\"_blank\">祛黑眼圈</a> <a href=\"/pifumeirongzhongxin/meibainenfu/fusehuian/\" target=\"_blank\">肤色晦暗</a> <a href=\"/pifumeirongzhongxin/meibainenfu/mianbumeibai/\" target=\"_blank\">面部美白</a> </span> <span>");
document.writeln("                                                        <h3>净痘靓肤:</h3>");
document.writeln("                                                        <a href=\"/pifumeirongzhongxin/jingdouliangfu/baitoufenci/\" target=\"_blank\">白头粉刺</a> <a href=\"/pifumeirongzhongxin/jingdouliangfu/heitoufenci/\" target=\"_blank\">黑头粉刺</a> <a href=\"/pifumeirongzhongxin/jingdouliangfu/qudouyin/\" target=\"_blank\">祛痘印</a> <a href=\"/pifumeirongzhongxin/jingdouliangfu/quqingchundou/\" target=\"_blank\">祛青春痘</a> </span> </div>");
document.writeln("                                                <div class=\"fl\"> <span>");
document.writeln("                                                        <h3>祛斑祛痣:</h3>");
document.writeln("                                                        <a href=\"/pifumeirongzhongxin/qubanquzhi/rishaiban/\" target=\"_blank\">日晒斑</a> <a href=\"/pifumeirongzhongxin/qubanquzhi/huangheban/\" target=\"_blank\">黄褐斑</a> <a href=\"/pifumeirongzhongxin/qubanquzhi/queban/\" target=\"_blank\">雀斑</a> <a href=\"/pifumeirongzhongxin/qubanquzhi/laonianban/\" target=\"_blank\">老年斑</a> <a href=\"/pifumeirongzhongxin/qubanquzhi/kafeiban/\" target=\"_blank\">咖啡斑</a> <a href=\"/pifumeirongzhongxin/qubanquzhi/quebanyangzhi/\" target=\"_blank\">雀斑样痣</a> <a href=\"/pifumeirongzhongxin/qubanquzhi/taitianzhi/\" target=\"_blank\">太田痣</a> <a href=\"/pifumeirongzhongxin/qubanquzhi/heqingsezhi/\" target=\"_blank\">褐青色痣</a> <a href=\"/pifumeirongzhongxin/qubanquzhi/beikezhi/\" target=\"_blank\">贝克痣</a> <a href=\"/pifumeirongzhongxin/qubanquzhi/yitengzhi/\" target=\"_blank\">伊藤痣</a> <a href=\"/pifumeirongzhongxin/qubanquzhi/xianhongbanzhi/\" target=\"_blank\">鲜红斑痣</a> <a href=\"/pifumeirongzhongxin/qubanquzhi/qutaiji/\" target=\"_blank\">祛胎记</a> </span> <span>");
document.writeln("                                                        <h3>艺术纹绣:</h3>");
document.writeln("                                                        <a href=\"/pifumeirongzhongxin/yishuwenxiu/xiyanxian/\" target=\"_blank\">洗眼线</a> <a href=\"/pifumeirongzhongxin/yishuwenxiu/xiwenshen/\" target=\"_blank\">洗纹身</a> <a href=\"/pifumeirongzhongxin/yishuwenxiu/xiwenmei/\" target=\"_blank\">洗纹眉</a> <a href=\"/pifumeirongzhongxin/yishuwenxiu/xichunxian/\" target=\"_blank\">洗唇线</a> <a href=\"/pifumeirongzhongxin/yishuwenxiu/kaiyunmei/\" target=\"_blank\">开运眉</a> <a href=\"/pifumeirongzhongxin/yishuwenxiu/wenmei/\" target=\"_blank\">纹眉</a> <a href=\"/pifumeirongzhongxin/yishuwenxiu/piaochun/\" target=\"_blank\">漂唇</a> <a href=\"/pifumeirongzhongxin/yishuwenxiu/hanshiyinxingyanx/\" target=\"_blank\">韩式隐形眼线</a> <a href=\"/pifumeirongzhongxin/yishuwenxiu/ruyunpiaohong/\" target=\"_blank\">乳晕漂红</a> </span> <span>");
document.writeln("                                                        <h3>疤痕修复:</h3>");
document.writeln("                                                        <a href=\"/pifumeirongzhongxin/bahenxiufu/shoushubahenxiufu/\" target=\"_blank\">手术疤痕修复</a> <a href=\"/pifumeirongzhongxin/bahenxiufu/yiwaibahenxiufu/\" target=\"_blank\">意外疤痕修复</a> </span> </div>");
document.writeln("                                                <strong class=\"fl\"> <em class=\"abtns clearFix\"> <i class=\"active\"></i> <i></i> </em> <em class=\"acuts\"> <i class=\"active\"><img src=\"/userpic/201505/15/20150515_161028_620.jpg\" height=\"366\" width=\"232\"></i> <i><img src=\"/userpic/201504/23/20150423_161601_970.jpg\" height=\"366\" width=\"232\"></i> </em> </strong> </li>");
document.writeln("                                </ul>");
document.writeln("                                <ul class=\"ul3\">");
document.writeln("                                        <h2 class=\"icon3\">抗衰老中心</h2>");
document.writeln("                                        <a href=\"/kangshuailaozhongxin/zhushechuzhou/\" target=\"_blank\">注射除皱</a> <a href=\"/kangshuailaozhongxin/jingxisuxing/\" target=\"_blank\">精细塑形</a> <a href=\"/kangshuailaozhongxin/aoxiantianchong/\" target=\"_blank\">凹陷填充</a> <a href=\"/kangshuailaozhongxin/zhushequyechou/\" target=\"_blank\">注射祛腋臭</a>");
document.writeln("                                        <li class=\"clearFix\">");
document.writeln("                                                <div class=\"fl\"> <span>");
document.writeln("                                                        <h3>注射除皱: </h3>");
document.writeln("                                                        <a href=\"/kangshuailaozhongxin/zhushechuzhou/zuijiaowen/\" target=\"_blank\">嘴角纹</a> <a href=\"/kangshuailaozhongxin/zhushechuzhou/jingwen/\" target=\"_blank\">颈纹</a> <a href=\"/kangshuailaozhongxin/zhushechuzhou/meichuanwen/\" target=\"_blank\">眉川纹</a> <a href=\"/kangshuailaozhongxin/zhushechuzhou/yuweiwen/\" target=\"_blank\">鱼尾纹</a> <a href=\"/kangshuailaozhongxin/zhushechuzhou/taitouwen/\" target=\"_blank\">抬头纹</a> <a href=\"/kangshuailaozhongxin/zhushechuzhou/falingwen/\" target=\"_blank\">法令纹</a> </span> <span>");
document.writeln("                                                        <h3>精细塑形:</h3>");
document.writeln("                                                        <a href=\"/kangshuailaozhongxin/jingxisuxing/zhushefengpingg/\" target=\"_blank\">注射丰苹果肌</a> <a href=\"/kangshuailaozhongxin/jingxisuxing/zhushefengetou/\" target=\"_blank\">注射丰额头</a> <a href=\"/kangshuailaozhongxin/jingxisuxing/zhushefengmianj/\" target=\"_blank\">注射丰面颊</a> <a href=\"/kangshuailaozhongxin/jingxisuxing/botoxzhusheshou/\" target=\"_blank\">BOTOX注射瘦小腿</a> <a href=\"/kangshuailaozhongxin/jingxisuxing/zhushefengxiaba/\" target=\"_blank\">注射丰下巴</a> <a href=\"/kangshuailaozhongxin/jingxisuxing/zhusheshoulian/\" target=\"_blank\">注射瘦脸</a> <a href=\"/kangshuailaozhongxin/jingxisuxing/zhushefengerchu/\" target=\"_blank\">注射丰耳垂</a> <a href=\"/kangshuailaozhongxin/jingxisuxing/zhushefengchun/\" target=\"_blank\">注射丰唇</a> <a href=\"/kangshuailaozhongxin/jingxisuxing/zhushelongbi/\" target=\"_blank\">注射隆鼻</a> <a href=\"/kangshuailaozhongxin/jingxisuxing/zhushefengtaiya/\" target=\"_blank\">注射丰太阳穴</a> </span> <span>");
document.writeln("                                                        <h3>凹陷填充:</h3>");
document.writeln("                                                        <a href=\"/kangshuailaozhongxin/aoxiantianchong/doukengdouyi/\" target=\"_blank\">痘坑痘印填充</a> <a href=\"/kangshuailaozhongxin/aoxiantianchong/leigoutianch/\" target=\"_blank\">泪沟填充</a> <a href=\"/kangshuailaozhongxin/aoxiantianchong/bichungoutia/\" target=\"_blank\">鼻唇沟填充</a> </span> <span>");
document.writeln("                                                        <h3>注射祛腋臭:</h3>");
document.writeln("                                                        <a href=\"/kangshuailaozhongxin/zhushequyechou/zhushequyecho/\" target=\"_blank\">注射祛腋臭</a> </span> </div>");
document.writeln("                                                <strong class=\"fl\"> <em class=\"abtns clearFix\"> <i class=\"active\"></i> <i></i> </em> <em class=\"acuts\"> <i class=\"active\"><img src=\"/userpic/201505/15/20150515_161026_416.jpg\" height=\"366\" width=\"232\"></i> <i><img src=\"/userpic/201505/15/20150515_160659_864.jpg\" height=\"366\" width=\"232\"></i> </em> </strong> </li>");
document.writeln("                                </ul>");
document.writeln("                        </dd>");
document.writeln("                </dl>");
document.writeln("                <ol class=\"fl\">");
document.writeln("                        <li><a href=\"#\" target=\"_blank\">江城首页</a></li>");
document.writeln("                        <li><a href=\"#\" target=\"_blank\">品牌中心</a></li>");
document.writeln("                        <li><a href=\"#\" target=\"_blank\">案例中心</a></li>");
document.writeln("                        <li><a href=\"#\" target=\"_blank\">专家团队</a></li>");
document.writeln("                        <li><a href=\"#\" target=\"_blank\">塑美设备</a></li>");
document.writeln("                        <li><a href=\"/zt/lylx/\" target=\"_blank\">来院路线</a></li>");
document.writeln("                        <li class=\"last\"><a onclick=\"openZoosUrl();return false;\" href=\"javascript:void(0)\">在线咨询</a></li>");
document.writeln("                </ol>");
document.writeln("        </div>");
document.writeln("</div>");
$('#nav ul').each(function(index) {
	var index=index+1;
        navvvv('#nav .ul'+index+' em.abtns i','#nav .ul'+index+' em.acuts i');
});
function navvvv(btn,cut){
	$(btn).mouseover(function(index){
		var index=$(this).index();
		$(btn).removeClass('active');
		$(this).addClass('active');	
		$(cut).removeClass('active');
		//$(cut).fadeOut();
		$(cut).eq(index).addClass('active');
		//$(cut).eq(index).fadeIn();
	})
}