// JavaScript Document
document.writeln("<style>");
document.writeln("/*case*/");
document.writeln(".case dl{ padding:30px 36px; border-bottom:1px dashed #d8d8d8;}");
document.writeln(".case dt{ width:340px; height:250px; background:#000;}");
document.writeln(".case dd{ position:relative; width:564px; height:250px;}");
document.writeln(".case h2{ color:#333333; font-size:24px; line-height:40px;}");
document.writeln(".case h3{ color:#026eb9; font-size:14px; margin-bottom:10px;}");
document.writeln(".case p{ color:#555555; font-size:14px; line-height:24px; text-indent:24px;}");
document.writeln(".case a{ position:absolute; right:0; bottom:0;}");
document.writeln("</style>");
document.writeln("<div class=\"case w1000\">");
document.writeln("	<dl class=\"clearFix\">");
document.writeln("        	<dt class=\"fr\"><script language=\'javascript\' src=\'http://www.5etv.com/video/v2_player_html5.jsp?vid=146224450&s=www.5etv.com&width=340&height=250&soValue=100&playMode=0&toolzt=yes&startzt=no\'></script></dt>");
document.writeln("        	<dd class=\"fl\">");
document.writeln("                	<h2>广西4岁\"穿山甲宝宝\"千里求医记（初诊篇）</h2>");
document.writeln("                        <h3>姓名：小绍一 年龄：4岁 发病史：3年 来自：广西</h3>");
document.writeln("                        <p>2014年6月1日上午，在上海江城皮肤病医院二楼诊疗区，一个满头黑色鳞甲的小男孩格外引人注意，他正坐在妈妈怀里候诊，旁边是他的爸爸。这个小男孩究竟得了什么病？病得严重吗？能治好吗？这个三口之家来自哪里？夫妻俩为儿子治病又有怎样的辛酸经历？六一儿童节到了，这个小男孩上海之行，会时来运转吗？<a href=\"/zt/csjbb/\" target=\"_blank\" style=\"position:static; color:#f00;\">（详细）</a></p>");
document.writeln("                        <a href=\"javascript:void(0);return false;\" onclick=\"openZoosUrl();return false;\"><img src=\"/zt/xcxyxb/images/reason_btn.jpg\" /></a>");
document.writeln("                </dd>");
document.writeln("        </dl>");
document.writeln("	<dl class=\"clearFix noPt\">");
document.writeln("        	<dt class=\"fl\"><script language=\'javascript\' src=\'http://www.5etv.com/video/v2_player_html5.jsp?vid=127546336&s=www.5etv.com&width=340&height=250&soValue=100&playMode=0&toolzt=yes&startzt=no\'></script></dt>");
document.writeln("        	<dd class=\"fr\">");
document.writeln("                	<h2>她感慨自己得知上海江城皮肤病医院太晚了</h2>");
document.writeln("                        <h3>姓名：吴女士  年龄：45岁  发病史：22 年   来自：四川</h3>");
document.writeln("                        <p>\"我结婚今年都已经22年了，结了婚以后就有的，我已经受了二十年了，它好在不传染……\"二十年了，吴女士不知被牛皮癣折磨得吃了多少苦头，如今大病得愈，她感慨自己得知上海江城医院太晚了，她说：\"我早知道的话，十几年前我就到这里来，我早就好了！\"</p>");
document.writeln("                        <a href=\"javascript:void(0);return false;\" onclick=\"openZoosUrl();return false;\"><img src=\"/zt/xcxyxb/images/reason_btn.jpg\" /></a>");
document.writeln("                </dd>");
document.writeln("        </dl>");
document.writeln("	<dl class=\"clearFix\">");
document.writeln("        	<dt class=\"fr\"><script language=\'javascript\' src=\'http://www.5etv.com/video/v2_player_html5.jsp?vid=106909993&s=www.5etv.com&width=340&height=250&soValue=100&playMode=0&toolzt=yes&startzt=no\'></script></dt>");
document.writeln("        	<dd class=\"fl\">");
document.writeln("                	<h2>12天：从\"行走靠挪\"到\"大步流星\"的惊喜</h2>");
document.writeln("                        <h3>姓名：阿郑  年龄：25岁  发病史：2 年   来自：浙江 </h3>");
document.writeln("                        <p>\"一停药马上就发出来，是药有问题。他在江湖郎中那里看了两个月不到，看了以后变成这个样子，越治越重，原来没有这么严重的。\"在上海江城皮肤病医院UVB紫外光治疗室，说起了儿子的病情，阿郑的父亲对于当地\"江湖郎中\"的不当治疗，悔恨不已。</p>");
document.writeln("                        <a href=\"javascript:void(0);return false;\" onclick=\"openZoosUrl();return false;\"><img src=\"/zt/xcxyxb/images/reason_btn.jpg\" /></a>");
document.writeln("                </dd>");
document.writeln("        </dl>");
document.writeln("	<dl class=\"clearFix\">");
document.writeln("        	<dt class=\"fl\"><script language=\'javascript\' src=\'http://www.5etv.com/video/v2_player_html5.jsp?vid=74177839&s=www.5etv.com&width=340&height=250&soValue=100&playMode=0&toolzt=yes&startzt=no\'></script></dt>");
document.writeln("        	<dd class=\"fr\">");
document.writeln("                	<h2>治疗牛皮癣滥用激素引起\"妊娠纹\"</h2>");
document.writeln("                        <h3>姓名：陈女  年龄：22岁 发病史：5 年   来自：河南新乡</h3>");
document.writeln("                        <p>陈女士今年22岁，来自河南新乡，患牛皮癣五年，在当地及一些城市大医院治疗不愈，于2010年5月改投上海江城皮肤病医院，经顾昌林 教授用中医活血化瘀、清热解毒治疗牛皮癣专方治疗，仅用一个多月即皮损全部消退，至今效果稳定，一直没有复发。</p>");
document.writeln("                        <a href=\"javascript:void(0);return false;\" onclick=\"openZoosUrl();return false;\"><img src=\"/zt/xcxyxb/images/reason_btn.jpg\" /></a>");
document.writeln("                </dd>");
document.writeln("        </dl>");
document.writeln("	<dl class=\"clearFix\">");
document.writeln("        	<dt class=\"fr\"><script language=\'javascript\' src=\'http://www.5etv.com/video/v2_player_html5.jsp?vid=124863292&s=www.5etv.com&width=340&height=250&soValue=100&playMode=0&toolzt=yes&startzt=no\'></script></dt>");
document.writeln("        	<dd class=\"fl\">");
document.writeln("                	<h2>热心邻居介绍！老朱说：\"来对了！\"</h2>");
document.writeln("                        <h3>姓名：朱先生 年龄：56岁 发病史：10年   来自：江苏海门</h3>");
document.writeln("                        <p>这个老病号姓朱，家住江苏海门，今年56岁。他身患银屑病（俗称牛皮癣），已经有十多年了，\"全身都有，脚上头上也都有。\"这些年来，老朱大江南北多地求医，不但病没治好，还在治疗信心上\"被泼了一头冷水\"。老朱说：\"看了北京、南京，东北那个沈阳都看过的，看不好啊，那的医生讲，你这个病看不好的，没用！\"</p>");
document.writeln("                        <a href=\"javascript:void(0);return false;\" onclick=\"openZoosUrl();return false;\"><img src=\"/zt/xcxyxb/images/reason_btn.jpg\" /></a>");
document.writeln("                </dd>");
document.writeln("        </dl>");
document.writeln("	<dl class=\"clearFix\">");
document.writeln("        	<dt class=\"fl\"><script language=\'javascript\' src=\'http://www.5etv.com/video/v2_player_html5.jsp?vid=67008313&s=www.5etv.com&width=340&height=250&soValue=100&playMode=0&toolzt=yes&startzt=no\'></script></dt>");
document.writeln("        	<dd class=\"fr\">");
document.writeln("                	<h2>十八年顽癣，枯木逢春</h2>");
document.writeln("                        <h3>姓名：孔先生 年龄：45 岁 发病史：18年   来自：上海青浦</h3>");
document.writeln("                        <p>孔先生在上海一机关执业，事业有成，家庭幸福，惟有一件事美中不足----他患有顽固牛皮癣达十八年之久。十八年来，他不能到游泳池、不能到浴室，惟恐一脱衣服满身的皮损会吓着旁人，用他自己的话说是百般痛苦难以言表。</p>");
document.writeln("                        <a href=\"javascript:void(0);return false;\" onclick=\"openZoosUrl();return false;\"><img src=\"/zt/xcxyxb/images/reason_btn.jpg\" /></a>");
document.writeln("                </dd>");
document.writeln("        </dl>");
document.writeln("	<dl class=\"clearFix noBb noPb\">");
document.writeln("        	<dt class=\"fr\"><script language=\'javascript\' src=\'http://www.5etv.com/video/v2_player_html5.jsp?vid=66509542&s=www.5etv.com&width=340&height=250&soValue=100&playMode=0&toolzt=yes&startzt=no\'></script></dt>");
document.writeln("        	<dd class=\"fl\">");
document.writeln("                	<h2>陈先生半信半疑地前来\"试一试\"</h2>");
document.writeln("                        <h3>姓名：陈先生 年龄：32 岁 发病史：5年   来自：上海浦东</h3>");
document.writeln("                        <p> 陈先生得牛皮癣五年半，其中几次治好，又几次复发。最后一次是半年前，复发得特别厉害，全身红肿，卧床不起，丧失了行走能力，本人也丧失了治疗的信心。</p>");
document.writeln("                        <a href=\"javascript:void(0);return false;\" onclick=\"openZoosUrl();return false;\"><img src=\"/zt/xcxyxb/images/reason_btn.jpg\" /></a>");
document.writeln("                </dd>");
document.writeln("        </dl>");
document.writeln("</div>");