// JavaScript Document
document.writeln("        <style>");
document.writeln("        	#recovery{ width:1000px; margin:0 auto;}");
document.writeln("		#recovery li{ width:224px; height:374px; padding:4px; position:relative; float:left; background:#e6e6e6; margin:0 24px 24px 0;}");
document.writeln("		#recovery li img{ margin-bottom:10px; vertical-align:middle;}");
document.writeln("		#recovery li p{ height:20px; line-height:20px; font-size:16px; color:#4b4b4b; margin-bottom:10px;}");
document.writeln("		#recovery li em{ width:20px; height:20px; vertical-align:middle; margin-right:5px;}");
document.writeln("		#recovery li p:hover em{ transform:rotatey(360deg); -webkit-transform:rotatey(360deg);}");
document.writeln("		#recovery li a{ height:30px; line-height:30px; width:128px; text-align:center; border:1px solid #969696; color:#4b4b4b; font-size:16px; position:absolute; bottom:20px; left:50%; margin-left:-65px;}");
document.writeln("		#recovery .active{ box-shadow:1px 1px 10px #0064b4;}");
document.writeln("		#recovery .active a{ background:#0064b4; color:#fff; border:1px solid #0064b4; }");
document.writeln("        </style>");
document.writeln("        <div id=\"recovery\">");
document.writeln("                <ol class=\"clearFix\">");
document.writeln("                        <li class=\"active\"> ");
document.writeln("                        	<img src=\"/images/recovery1.jpg\">");
document.writeln("                                <p><em><img src=\"/images/recovery_icon1.png\"></em>姓名：小绍一    年龄：4岁</p>");
document.writeln("                                <p><em><img src=\"/images/recovery_icon2.png\"></em>症状：脓疱型银屑病</p>");
document.writeln("                                <p><em><img src=\"/images/recovery_icon3.png\"></em>患病时间：3年</p>");
document.writeln("                                <a href=\"/zt/csjbb/\" target=\"_blank\">点击了解该案例</a> ");
document.writeln("                        </li>");
document.writeln("                        <li> ");
document.writeln("                        	<img src=\"/images/recovery2.jpg\">");
document.writeln("                                <p><em><img src=\"/images/recovery_icon1.png\"></em>姓名：吴女士   年龄：45岁</p>");
document.writeln("                                <p><em><img src=\"/images/recovery_icon2.png\"></em>症状：混合型银屑病</p>");
document.writeln("                                <p><em><img src=\"/images/recovery_icon3.png\"></em>患病时间：22年</p>");
document.writeln("                                <a href=\"/zt/Ms-wu/\" target=\"_blank\">点击了解该案例</a> ");
document.writeln("                        </li>");
document.writeln("                        <li> ");
document.writeln("                        	<img src=\"/images/recovery3.jpg\">");
document.writeln("                                <p><em><img src=\"/images/recovery_icon1.png\"></em>姓名：汤先生    年龄：58岁</p>");
document.writeln("                                <p><em><img src=\"/images/recovery_icon2.png\"></em>症状：全身性寻常型银屑病</p>");
document.writeln("                                <p><em><img src=\"/images/recovery_icon3.png\"></em>患病时间：5年</p>");
document.writeln("                                <a href=\"/zt/Mr-tang/\" target=\"_blank\">点击了解该案例</a> ");
document.writeln("                        </li>");
document.writeln("                        <li style=\"margin-right:0;\"> ");
document.writeln("                        	<img src=\"/images/recovery4.jpg\">");
document.writeln("                                <p><em><img src=\"/images/recovery_icon1.png\"></em>姓名：小林    年龄：19岁</p>");
document.writeln("                                <p><em><img src=\"/images/recovery_icon2.png\"></em>症状：全身性寻常型银屑病</p>");
document.writeln("                                <p><em><img src=\"/images/recovery_icon3.png\"></em>患病时间：2年</p>");
document.writeln("                                <a href=\"/zt/Mr-lin/\" target=\"_blank\">点击了解该案例</a> ");
document.writeln("                        </li>");
document.writeln("                        <li style=\"margin-bottom:0;\"> ");
document.writeln("                        	<img src=\"/images/recovery5.jpg\">");
document.writeln("                                <p><em><img src=\"/images/recovery_icon1.png\"></em>姓名：阿郑  年龄：25岁</p>");
document.writeln("                                <p><em><img src=\"/images/recovery_icon2.png\"></em>症状：脓疱病型银屑病</p>");
document.writeln("                                <p><em><img src=\"/images/recovery_icon3.png\"></em>患病时间：2年</p>");
document.writeln("                                <a href=\"/zt/Mr-zheng/\" target=\"_blank\">点击了解该案例</a> ");
document.writeln("                        </li>");
document.writeln("                        <li style=\"margin-bottom:0;\"> ");
document.writeln("                        	<img src=\"/images/recovery6.jpg\">");
document.writeln("                                <p><em><img src=\"/images/recovery_icon1.png\"></em>姓名：何先生  年龄：55</p>");
document.writeln("                                <p><em><img src=\"/images/recovery_icon2.png\"></em>症状：全身性银屑病</p>");
document.writeln("                                <p><em><img src=\"/images/recovery_icon3.png\"></em>患病时间：15年</p>");
document.writeln("                                <a href=\"/zt/Mr-he/\" target=\"_blank\">点击了解该案例</a>");
document.writeln("                        </li>");
document.writeln("                        <li style=\"margin-bottom:0;\"> ");
document.writeln("                        	<img src=\"/images/recovery7.jpg\">");
document.writeln("                                <p><em><img src=\"/images/recovery_icon1.png\"></em>姓名：魏先生 年龄：30岁</p>");
document.writeln("                                <p><em><img src=\"/images/recovery_icon2.png\"></em>症状：红皮病型银屑病</p>");
document.writeln("                                <p><em><img src=\"/images/recovery_icon3.png\"></em>患病时间：10年</p>");
document.writeln("                                <a href=\"/zt/Mr-wei/\" target=\"_blank\">点击了解该案例</a> ");
document.writeln("                        </li>");
document.writeln("                        <li style=\"margin-right:0; margin-bottom:0;\"> ");
document.writeln("                        	<img src=\"/images/recovery8.jpg\">");
document.writeln("                                <p><em><img src=\"/images/recovery_icon1.png\"></em>姓名：巴图    年龄：30岁</p>");
document.writeln("                                <p><em><img src=\"/images/recovery_icon2.png\"></em>症状：全身性寻常型银屑病</p>");
document.writeln("                                <p><em><img src=\"/images/recovery_icon3.png\"></em>患病时间：12年</p>");
document.writeln("                                <a href=\"/zt/Mr-batu/\" target=\"_blank\">点击了解该案例</a> ");
document.writeln("                        </li>");
document.writeln("                </ol>");
document.writeln("        </div>");
document.writeln("	<script>");
document.writeln("		/*recovery*/");
document.writeln("		$(function(){");
document.writeln("			var aBtn=$(\'#recovery li\');");
document.writeln("			tabSwitch(aBtn);	");
document.writeln("		})");
document.writeln("        </script>");