// JavaScript Document
document.writeln("<style>");
document.writeln("/*therapy*/");
document.writeln("#therapyMain ol li{ margin-bottom:1px; padding-left:30px; width:300px; height:64px; background:#969696; color:#fff; position:relative;}");
document.writeln("#therapyMain ol .active{ background:#0064b4;}");
document.writeln("#therapyMain ol em{ float:left; width:41px; height:41px; margin:11px 16px 0 0; overflow:hidden;}");
document.writeln("#therapyMain ol .active em{ transform:rotate(360deg); -webkit-transform:rotate(360deg);}");
document.writeln("#therapyMain ol span{ float:left; height:60px;}");
document.writeln("#therapyMain ol strong{ font-size:20px; height:20px; line-height:20px; margin-top:10px;}");
document.writeln("#therapyMain ol small{ font-size:14px; height:14px; line-height:14px; margin-top:6px;}");
document.writeln("#therapyMain ol b{ background:url(/zt/yyjs/images/three.png); width:6px; height:9px; position:absolute; right:-6px; top:25px; opacity:0; filter:alpha(opacity:0); transition:0.4s;}");
document.writeln("#therapyMain ol .active b{ opacity:100; filter:alpha(opacity:100);}");
document.writeln("#therapyMain ul{ margin-top:1px;}");
document.writeln("#therapyMain ul li{ width:652px; height:452px; overflow:hidden; display:none; position:relative;}");
document.writeln("#therapyMain ul .active{ display:block;}");
document.writeln("#therapyMain ul div{ height:196px; padding-top:4px; width:100%; background:url(/zt/yyjs/images/grey_bg.png); position:absolute; left:0; bottom:0; color:#fff; transition:0.4s;}");
document.writeln("#therapyMain ul h2{ font-size:22px; color:#e97621; margin:10px 0; text-align:center; padding:0 10px;}");
document.writeln("#therapyMain ul p{ font-size:16px; color:#fff; line-height:30px; padding:0 20px;}");
document.writeln("#therapyMain ul a{ width:180px; text-align:center; height:40px; line-height:40px; color:#fff; background:#0064b4; font-size:18px; position:absolute; left:50%; margin-left:-90px; bottom:10px;}");
document.writeln("</style>");
document.writeln("<div id=\"therapy\" class=\"w1000\">");
document.writeln("        <div id=\"therapyMain\" class=\"clearFix\">");
document.writeln("                <ol class=\"fl\">");
document.writeln("                        <li class=\"active\"> <em><img src=\"/zt/yyjs/images/therapy_icon1.png\"></em> <span> <strong>特配独家中药药浴</strong><br>");
document.writeln("                                <small>Medicated bath</small> </span> <b></b> </li>");
document.writeln("                        <li> <em><img src=\"/zt/yyjs/images/therapy_icon2.png\"></em> <span> <strong>中药药离子熏蒸</strong><br>");
document.writeln("                                <small>fumigation</small> </span> <b></b> </li>");
document.writeln("                        <li> <em><img src=\"/zt/yyjs/images/therapy_icon3.png\"></em> <span> <strong>308准分子激光</strong><br>");
document.writeln("                                <small>308 excimer laser</small> </span> <b></b> </li>");
document.writeln("                        <li> <em><img src=\"/zt/yyjs/images/therapy_icon4.png\"></em> <span> <strong>311窄谱UVB治疗仪</strong><br>");
document.writeln("                                <small>UVB treatment instrument</small> </span> <b></b> </li>");
document.writeln("                        <li> <em><img src=\"/zt/yyjs/images/therapy_icon5.png\"></em> <span> <strong>蓝氧自体净血回输</strong><br>");
document.writeln("                                <small>Net of autologous blood doping</small> </span> <b></b> </li>");
document.writeln("                        <li> <em><img src=\"/zt/yyjs/images/therapy_icon6.png\"></em> <span> <strong>穴位埋线抗体疗法</strong><br>");
document.writeln("                                <small>Antibody therapy</small> </span> <b></b> </li>");
document.writeln("                        <li style=\"margin-bottom:0;\"> <em><img src=\"/zt/yyjs/images/therapy_icon7.png\"></em> <span> <strong>抗感染疗法</strong><br>");
document.writeln("                                <small>Anti-infection therapy</small> </span> <b></b> </li>");
document.writeln("                </ol>");
document.writeln("                <ul class=\"fr\">");
document.writeln("                        <li class=\"active\"> <img src=\"/zt/yyjs/images/therapy1.jpg\">");
document.writeln("                                <div>");
document.writeln("                                        <h2>独家配制传统中药    活血化瘀   疏通皮肤经络</h2>");
document.writeln("                                        <p>功效：药浴洗浴，可起到疏通经络、活血化淤、驱风散寒、清热解毒、消肿止\"邪，对因\"风、寒、湿\"邪引起的疾病，热疗能起到非常明显的</p>");
document.writeln("                                        <a href=\"javascript:void(0);return false;\" onclick=\"openZoosUrl();return false;\" target=\"_blank\">点击咨询该疗法</a> </div>");
document.writeln("                        </li>");
document.writeln("                        <li> <img src=\"/zt/yyjs/images/therapy2.jpg\">");
document.writeln("                                <div>");
document.writeln("                                        <h2>药离子通过皮肤的渗透、转运、吸收，直<br />");
document.writeln("                                                达病灶对脾胃的毒副作用小、中药熏蒸绿色纯天然。</h2>");
document.writeln("                                        <p>功效：热是治病因子\"风、寒、湿\"的克星，熏蒸有效排除体内的\"风、寒、湿\"邪，对因\"风、寒、湿\"邪引起的疾病，热疗能起到非常明显的效果。</p>");
document.writeln("                                        <a href=\"javascript:void(0);return false;\" onclick=\"openZoosUrl();return false;\" target=\"_blank\">点击咨询该疗法</a> </div>");
document.writeln("                        </li>");
document.writeln("                        <li> <img src=\"/zt/yyjs/images/therapy3.jpg\">");
document.writeln("                                <div>");
document.writeln("                                        <h2>银屑病的终结者<br />");
document.writeln("                                                靶向针对患者病灶   临床康复率高达96.8%</h2>");
document.writeln("                                        <p>功效：靶向针对病灶，不损伤正常皮肤，消除传统调制窄脉产生的波形畸变、只能微处理器控制，高稳定性、高可靠性，可渗透16nm深层组织，修复受损细胞。</p>");
document.writeln("                                        <a href=\"javascript:void(0);return false;\" onclick=\"openZoosUrl();return false;\" target=\"_blank\">点击咨询该疗法</a> </div>");
document.writeln("                        </li>");
document.writeln("                        <li> <img src=\"/zt/yyjs/images/therapy4.jpg\">");
document.writeln("                                <div>");
document.writeln("                                        <h2>311-312nm最佳有效波长      无创、无痛、非介入治疗</h2>");
document.writeln("                                        <p>功效：充分接受窄谱UVB发射的光线波长在311-312纳米范围内的光照，同时UVB治疗不需要服用其他辅助医物，避免了在传统PUVA方法中使用光敏医物所带来的副作用。</p>");
document.writeln("                                        <a href=\"javascript:void(0);return false;\" onclick=\"openZoosUrl();return false;\" target=\"_blank\">点击咨询该疗法</a> </div>");
document.writeln("                        </li>");
document.writeln("                        <li> <img src=\"/zt/yyjs/images/therapy5.jpg\">");
document.writeln("                                <div>");
document.writeln("                                        <h2>杀菌能力30000倍于抗生素      0毒副作用</h2>");
document.writeln("                                        <p>功效：结合\"治外必治内，治内必治根\"施治理论，将蓝氧导入血液，增加血氧含量改善细胞代谢与活性，促进受损皮肤细胞修复；清除体内致病因子和毒素，激活免疫系统预防反复。</p>");
document.writeln("                                        <a href=\"javascript:void(0);return false;\" onclick=\"openZoosUrl();return false;\" target=\"_blank\">点击咨询该疗法</a> </div>");
document.writeln("                        </li>");
document.writeln("                        <li> <img src=\"/zt/yyjs/images/therapy6.jpg\">");
document.writeln("                                <div>");
document.writeln("                                        <h2>刺激经络    平衡阴阳   调和气血   调整脏腑</h2>");
document.writeln("                                        <p>功效：根据针灸学理论,通过针具和药线在穴位内产生刺激经络、平衡阴阳、调和气血、调整脏腑，达到治疗疾病的目的。</p>");
document.writeln("                                        <a href=\"javascript:void(0);return false;\" onclick=\"openZoosUrl();return false;\" target=\"_blank\">点击咨询该疗法</a> </div>");
document.writeln("                        </li>");
document.writeln("                        <li> <img src=\"/zt/yyjs/images/therapy7.jpg\">");
document.writeln("                                <div>");
document.writeln("                                        <h2>提升抵御外界细菌的能力，提升抵抗力低下，及时控制感染。</h2>");
document.writeln("                                        <p>功效：抗感染治疗包括抗细菌、抗病毒、抗表浅真菌及抗寄生虫等，快速控制病灶部位感染，提升自体皮肤免疫功能，促进新陈代谢达到治疗的目的。</p>");
document.writeln("                                        <a href=\"javascript:void(0);return false;\" onclick=\"openZoosUrl();return false;\" target=\"_blank\">点击咨询该疗法</a> </div>");
document.writeln("                        </li>");
document.writeln("                </ul>");
document.writeln("        </div>");
document.writeln("</div>");
document.writeln("<script>");
document.writeln("/*therapy*/");
document.writeln("$(function(){");
document.writeln("	var aBtn=$(\'#therapy ol li\');");
document.writeln("	var aCut=$(\'#therapy ul li\');");
document.writeln("	tabSwitch(aBtn,aCut);");
document.writeln("})");
document.writeln("</script>");
document.writeln("");