// JavaScript Document
document.writeln("                <!--expert-->");
document.writeln("                <style>");
document.writeln("                /*expert*/");
document.writeln("		#expert .bd li{ border:1px solid #e3e3e3;}");
document.writeln("		#expert .bd dt{ padding:3px; width:45%; box-sizing:border-box;}");
document.writeln("		#expert .bd dd{ font-size:2.4rem; color:#666666; width:48%; margin-right:1.6%;}");
document.writeln("		#expert .bd h2{ font-size:4.4rem; color:#0070bc; line-height:2;}");
document.writeln("		#expert .bd i{ font-size:2.4rem; color:#666666; margin-left:5px;}");
document.writeln("		#expert .bd p{ margin-bottom:4%;}");
document.writeln("		#expert .bd h3{ margin-top:8%; line-height:1.45;}");
document.writeln("		#expert .bd strong{ color:#0070bc;}");
document.writeln("		#expert .bd div{ margin-top:9%;}");
document.writeln("		#expert .bd a{ color:#fff; background:#0070bc; line-height:2; width:45%; text-align:center; border-radius:5px;}");
document.writeln("		#expert .bd a:nth-of-type(2){ background:#ff9000;}");
document.writeln("		#expert .hd{ text-align:center; margin-top:2%;}");
document.writeln("		#expert .hd li{ width:12px; height:12px; background:#cecece; display:inline-block; margin:0 5px; border-radius:50%;}");
document.writeln("		#expert .hd li.on{ background:#0070bc;}");
document.writeln("                </style>");
document.writeln("                <div id=\"expert\">");
document.writeln("                        <ul class=\"bd\">");
document.writeln("                        	<li>");
document.writeln("                                	<dl class=\"clearFix\">");
document.writeln("                                        	<dt class=\"fl\">");
document.writeln("                                                	<img src=\"tongyong/images/expert1.jpg\" />");
document.writeln("                                                </dt>");
document.writeln("                                                <dd class=\"fr\">");
document.writeln("                                                	<h2>顾昌林<i>主任医师</i></h2>");
document.writeln("                                                        <p>国务院特殊津贴获得者</p>");
document.writeln("                                                        <p>国家科技进步奖获得者</p>");
document.writeln("                                                        <h3><strong>擅长治疗：</strong>白癜风、牛皮癣等多种皮肤病。</h3>");
document.writeln("                                                        <div class=\"clearFix\">");
document.writeln("                                                                <a href=\"#\" target=\"_blank\" class=\"fl\">了解更多</a>");
document.writeln("                                                                <a href=\"#\" target=\"_blank\" class=\"fr\">立即预约</a>");
document.writeln("                                                        </div>");
document.writeln("                                                </dd>");
document.writeln("                                        </dl>");
document.writeln("                                </li>");
document.writeln("                        	<li>");
document.writeln("                                	<dl class=\"clearFix\">");
document.writeln("                                        	<dt class=\"fl\">");
document.writeln("                                                	<img src=\"tongyong/images/expert2.jpg\" />");
document.writeln("                                                </dt>");
document.writeln("                                                <dd class=\"fr\">");
document.writeln("                                                	<h2>陶家喜<i>副主任医师</i></h2>");
document.writeln("                                                        <p>军队优秀医务工作者</p>");
document.writeln("                                                        <p>荣获三等功2次</p>");
document.writeln("                                                        <h3><strong>擅长治疗：</strong>擅长治疗各种类型银屑病。</h3>");
document.writeln("                                                        <div class=\"clearFix\">");
document.writeln("                                                                <a href=\"#\" target=\"_blank\" class=\"fl\">了解更多</a>");
document.writeln("                                                                <a href=\"#\" target=\"_blank\" class=\"fr\">立即预约</a>");
document.writeln("                                                        </div>");
document.writeln("                                                </dd>");
document.writeln("                                        </dl>");
document.writeln("                                </li>");
document.writeln("                        	<li>");
document.writeln("                                	<dl class=\"clearFix\">");
document.writeln("                                        	<dt class=\"fl\">");
document.writeln("                                                	<img src=\"tongyong/images/expert3.jpg\" />");
document.writeln("                                                </dt>");
document.writeln("                                                <dd class=\"fr\">");
document.writeln("                                                	<h2>罗兰珍<i>特聘专家</i></h2>");
document.writeln("                                                        <p>上海江城皮肤病医院专家组成员</p>");
document.writeln("                                                        <p>拥有丰富的临床诊疗经验</p>");
document.writeln("                                                        <h3><strong>擅长治疗：</strong>银屑病、白癜风等慢性顽固性皮肤病。</h3>");
document.writeln("                                                        <div class=\"clearFix\">");
document.writeln("                                                                <a href=\"#\" target=\"_blank\" class=\"fl\">了解更多</a>");
document.writeln("                                                                <a href=\"#\" target=\"_blank\" class=\"fr\">立即预约</a>");
document.writeln("                                                        </div>");
document.writeln("                                                </dd>");
document.writeln("                                        </dl>");
document.writeln("                                </li>");
document.writeln("                        </ul>");
document.writeln("                        <div class=\"hd\">");
document.writeln("                        	<ul class=\"clearFix\">");
document.writeln("                                	<li class=\"on\"></li>");
document.writeln("                                	<li></li>");
document.writeln("                                	<li></li>");
document.writeln("                                </ul>");
document.writeln("                        </div>");
document.writeln("                </div>");
document.writeln("");