// JavaScript Document
document.writeln("        <!--night-->");
document.writeln("        <div id=\"night\"><a href=\"#\" target=\"_blank\"><img src=\"tongyong/images/night.jpg\" /></a></div>");
document.writeln("        ");
document.writeln("        <!--tils-->");
document.writeln("        <div id=\"tils\">就诊绿色通道</div>");
document.writeln("        ");
document.writeln("        <!--forms-->");
document.writeln("        <div id=\"forms\">");
document.writeln("        	<h2><em><img src=\"tongyong/images/hint.jpg\" /></em>我院郑重承诺，患者填写一下信息绝对保密。</h2>");
document.writeln("        	<form method=\"post\" action=\"http://swt.gssmart.com/guahao/sockt.php\" name=\"comment\">");
document.writeln("                	<div class=\"clearFix\">");
document.writeln("                                <label class=\"fl\" for=\"username\">姓名：</label>");
document.writeln("                                <input type=\"text\" id=\"username\" name=\"username\" class=\"fr\" placeholder=\"请输入你的姓名\" required=\"required\" />");
document.writeln("                        </div>");
document.writeln("                	<div class=\"clearFix\">");
document.writeln("                                <label class=\"fl\">性别：</label>");
document.writeln("                                <input type=\"radio\" name=\"sex\" id=\"man\" checked=\"checked\" /><label for=\"man\">男</label>");
document.writeln("                                <input type=\"radio\" name=\"sex\" id=\"woman\" /><label for=\"woman\">女</label>");
document.writeln("                        </div>");
document.writeln("                	<div class=\"clearFix\">");
document.writeln("                                <label class=\"fl\" for=\"phone\">联系方式：</label>");
document.writeln("                                <input type=\"tel\" name=\"tel\" id=\"phone\" class=\"fr\" placeholder=\"请输入你的联系方式\"  required=\"required\"/>");
document.writeln("                        </div>");
document.writeln("                	<div class=\"clearFix\">");
document.writeln("                                <label class=\"fl\" for=\"content\">疾病：</label>");
document.writeln("                                <textarea type=\"text\" name=\"content\" id=\"content\" class=\"fr\" placeholder=\"请简述病情\" /></textarea>");
document.writeln("                        </div>");
document.writeln("                        <div class=\"submit\">");
document.writeln("                        	<input type=\"submit\" value=\"提交在线挂号\" onclick=\"return checkForm();\" />");
document.writeln("                        </div>");
document.writeln("                </form>");
document.writeln("                <h2><i>温馨提醒：</i>我院收到您的详细信息后，会及时发出专家号及详细来源路线到您的手机，请注意查收。</h2>");
document.writeln("        </div>");
document.writeln("        ");
document.writeln("        <!--footer-->");
document.writeln("        <div id=\"footer\">");
document.writeln("        	<img src=\"tongyong/images/footer.jpg\" />");
document.writeln("                <div>");
document.writeln("                	<p>医院地址：上海杨浦区黄兴路286号</p>");
document.writeln("                	<p>接诊时间 : 8:00--21:00 节假日不休息</p>");
document.writeln("                	<p>咨询电话：021-52721929</p>");
document.writeln("                </div>");
document.writeln("        </div>");
document.writeln("        ");
document.writeln("        <!--fixedNav-->");
document.writeln("        <div id=\"fixedNav\">");
document.writeln("                <a href=\"tel:021-52721929\" target=\"_blank\" class=\"phone\"><img src=\"tongyong/images/phone.png\"/>电话咨询</a>");
document.writeln("                <a href=\"/\" target=\"_blank\" class=\"home\"><img src=\"tongyong/images/home.png\"/>首　页</a>");
document.writeln("                <a href=\"javascript:void(0);return false;\" onclick=\"openZoosUrl();return false;\" class=\"message\"><img src=\"tongyong/images/message.png\"/>你的消息</a>");
document.writeln("        </div>");