// JavaScript Document
document.writeln("");
document.writeln("        <!--top-->");
document.writeln("        <div id=\"top\">");
document.writeln("        	<dl class=\"clearFix\">");
document.writeln("                	<dt class=\"fl\">");
document.writeln("                        	<a href=\"#\" target=\"_blank\">回到首页</a>");
document.writeln("                        	<a href=\"#\" target=\"_blank\">免费挂号</a>");
document.writeln("                        </dt>");
document.writeln("                        <dd class=\"fr\">咨询热线：<i>021-52721929</i></dd>");
document.writeln("                </dl>");
document.writeln("        </div>");
document.writeln("        ");
document.writeln("        <!--logo-->");
document.writeln("        <div id=\"logo\"><img src=\"tongyong/images/logo.jpg\" /></div>");
document.writeln("        ");
document.writeln("        <!--nav-->");
document.writeln("        <div id=\"nav\">");
document.writeln("        	<ul class=\"clearFix\">");
document.writeln("                        <li>");
document.writeln("                                <em><img src=\"tongyong/images/nav1.jpg\" /></em>");
document.writeln("                                <p>医院介绍</p>                        ");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                                <em><img src=\"tongyong/images/nav2.jpg\" /></em>");
document.writeln("                                <p>科室首页</p>                        ");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                                <em><img src=\"tongyong/images/nav3.jpg\" /></em>");
document.writeln("                                <p>医院简介</p>                        ");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                                <em><img src=\"tongyong/images/nav4.jpg\" /></em>");
document.writeln("                                <p>权威专家</p>                        ");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                                <em><img src=\"tongyong/images/nav5.jpg\" /></em>");
document.writeln("                                <p>先进设备</p>                        ");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                                <em><img src=\"tongyong/images/nav6.jpg\" /></em>");
document.writeln("                                <p>媒体报道</p>                        ");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                                <em><img src=\"tongyong/images/nav7.jpg\" /></em>");
document.writeln("                                <p>典型案例</p>                        ");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                                <em><img src=\"tongyong/images/nav8.jpg\" /></em>");
document.writeln("                                <p>来院路线</p>                        ");
document.writeln("                        </li>");
document.writeln("                </ul>");
document.writeln("        </div>");