// JavaScript Document
document.writeln("                <!--therapy-->");
document.writeln("                <style>                ");
document.writeln("		/*therapy*/");
document.writeln("		#therapy li{ border:1px solid #d6d6d6; padding:1.6% 0; margin-bottom:1%;}");
document.writeln("		#therapy a{ width:100%;}");
document.writeln("		#therapy em{ vertical-align:middle; margin:0 1.7% 0 1.2%; width:5.8%;}");
document.writeln("		#therapy strong{ vertical-align:middle; font-size:2.8rem; color:#0070bc; line-height:1.28;}");
document.writeln("		#therapy i{ font-size:2.4rem; color:#999;}");
document.writeln("		#therapy small{ float:right; margin-right:4.8%; width:5.3%;}");
document.writeln("                </style>");
document.writeln("                <div id=\"therapy\">");
document.writeln("                        <ul>");
document.writeln("                        	<li>");
document.writeln("                                	<a class=\"clearFix\" href=\"#\" target=\"_blank\">");
document.writeln("                                                <em><img src=\"tongyong/images/therapy1.jpg\" /></em>");
document.writeln("                                                <strong>中药药离子熏蒸<i>/fumigation</i></strong>                                        ");
document.writeln("                                                <small><img src=\"tongyong/images/therapy.jpg\" /></small>");
document.writeln("                                        </a>");
document.writeln("                                </li>");
document.writeln("                        	<li>");
document.writeln("                                	<a class=\"clearFix\" href=\"#\" target=\"_blank\">");
document.writeln("                                                <em><img src=\"tongyong/images/therapy2.jpg\" /></em>");
document.writeln("                                                <strong>美国308nm激光<i>/American 308nm laser</i></strong>                                        ");
document.writeln("                                                <small><img src=\"tongyong/images/therapy.jpg\" /></small>");
document.writeln("                                        </a>");
document.writeln("                                </li>");
document.writeln("                        	<li>");
document.writeln("                                	<a class=\"clearFix\" href=\"#\" target=\"_blank\">");
document.writeln("                                                <em><img src=\"tongyong/images/therapy3.jpg\" /></em>");
document.writeln("                                                <strong>特配独家中药药浴<i>/Sole Chinese medicine</i></strong>                                        ");
document.writeln("                                                <small><img src=\"tongyong/images/therapy.jpg\" /></small>");
document.writeln("                                        </a>");
document.writeln("                                </li>");
document.writeln("                        	<li>");
document.writeln("                                	<a class=\"clearFix\" href=\"#\" target=\"_blank\">");
document.writeln("                                                <em><img src=\"tongyong/images/therapy4.jpg\" /></em>");
document.writeln("                                                <strong>德国311窄谱UVB治疗仪<i>/UVB treatment</i></strong>                                        ");
document.writeln("                                                <small><img src=\"tongyong/images/therapy.jpg\" /></small>");
document.writeln("                                        </a>");
document.writeln("                                </li>");
document.writeln("                        	<li>");
document.writeln("                                	<a class=\"clearFix\" href=\"#\" target=\"_blank\">");
document.writeln("                                                <em><img src=\"tongyong/images/therapy5.jpg\" /></em>");
document.writeln("                                                <strong>蓝氧自体净血<i>/O3 Net autologous blood</i></strong>                                        ");
document.writeln("                                                <small><img src=\"tongyong/images/therapy.jpg\" /></small>");
document.writeln("                                        </a>");
document.writeln("                                </li>");
document.writeln("                        	<li>");
document.writeln("                                	<a class=\"clearFix\" href=\"#\" target=\"_blank\">");
document.writeln("                                                <em><img src=\"tongyong/images/therapy6.jpg\" /></em>");
document.writeln("                                                <strong>穴位埋线抗体疗法<i>/antibody therapy</i></strong>                                        ");
document.writeln("                                                <small><img src=\"tongyong/images/therapy.jpg\" /></small>");
document.writeln("                                        </a>");
document.writeln("                                </li>");
document.writeln("                        	<li>");
document.writeln("                                	<a class=\"clearFix\" href=\"#\" target=\"_blank\">");
document.writeln("                                                <em><img src=\"tongyong/images/therapy7.jpg\" /></em>");
document.writeln("                                                <strong>抗感染疗法<i>/Anti-infection therapy</i></strong>                                        ");
document.writeln("                                                <small><img src=\"tongyong/images/therapy.jpg\" /></small>");
document.writeln("                                        </a>");
document.writeln("                                </li>");
document.writeln("                        </ul>");
document.writeln("                </div>");