//JavaScript Document
document.writeln("<style>");
document.writeln("/** 清除内外边距 **/");
document.writeln("    body, h1, h2, h3, h4, h5, h6, hr, p,");
document.writeln("    blockquote,   /* structural elements 结构元素 */");
document.writeln("    dl, dt, dd, ul, ol, li, /* list elements 列表元素 */");
document.writeln("    pre, /* text formatting elements 文本格式元素 */");
document.writeln("    form, fieldset, legend, button, input, textarea, /* form elements 表单元素 */");
document.writeln("    th, td, /* table elements 表格元素 */");
document.writeln("    img/* img elements 图片元素 */{");
document.writeln("	border:medium none;");
document.writeln("	margin: 0;");
document.writeln("	padding: 0;");
document.writeln("	list-style-type: none;");
document.writeln("	vertical-align: middle;");
document.writeln("    }");
document.writeln("    /** 设置默认字体 **/");
document.writeln("    body,button, input, select, textarea {");
document.writeln("    font: 12px/1.5 \'宋体\',tahoma, Srial, helvetica, sans-serif; }");
document.writeln("    h1, h2, h3, h4, h5, h6 { font-size: 100%; }");
document.writeln("    em{font-style:normal;}");
document.writeln("    /** 重置列表元素 **/");
document.writeln("    ul, ol,{ list-style: none; }");
document.writeln("    /** 重置超链接元素 **/");
document.writeln("    a { text-decoration: none; color:#333;}");
document.writeln("    /** 重置图片元素 **/");
document.writeln("    img{ border:0px;}");
document.writeln("    /** 重置表格元素 **/");

document.writeln("");
document.writeln("");
document.writeln(".w980{ width:980px; margin:0 auto;}");
document.writeln(".w995{ width:995px; margin:0 auto;}");
document.writeln(".fl{ float:left;}");
document.writeln(".clr{ clear:both;}");
document.writeln(".mt20{ margin-top:20px;}");
document.writeln(".b1{ border:1px solid #dcdcdc; border-top:none;}");
document.writeln("");

document.writeln("/*====头部====*/");
document.writeln(".db_nav{ background:url(http://pfb.skinjc.com/images/wyqzt_01.jpg) repeat-x; height:35px; width:100%; line-height:35px;min-width:995px}");
document.writeln(".so_01 {background: url(http://pfb.skinjc.com/images/wyqzt_03.jpg) no-repeat;border: 0 none;float: left;height: 26px;line-height: 26px;margin: 5px 40px 0 45px;padding-left: 26px;width:263px;}");
document.writeln(".anniutop{background: url(http://pfb.skinjc.com/images/wyqzt_03.jpg) no-repeat;border: 0 none;float: left;height: 26px;line-height: 26px;margin: 5px 40px 0 45px;padding-left: 26px;width:263px;}");
document.writeln(".so_02 {background: none repeat scroll 0 0 rgba(0, 0, 0, 0);border: medium none;height: 24px;width: 184px;z-index: 3;}");
document.writeln(".so_03 { height: 26px;width: 45px;cursor: pointer;}");
document.writeln(".db_nav a{ font-size:12px; color:#777; font-family:\"宋体\"!important; line-height:35px;}");
document.writeln(".nav {background:url(http://pfb.skinjc.com/img_new/jcx_01.jpg) repeat-x center top;height:42px;margin:5px auto 0;}");
document.writeln(".nav ul {margin-left:10px;}");
document.writeln(".nav li {float:left;line-height:42px;text-align:center;width:92px;font-size:14px;background:url(http://pfb.skinjc.com/img_new/jcx_02.jpg) no-repeat right center;font-weight:bold;}");
document.writeln(".nav li.last {background:none;}");
document.writeln(".nav li a {color:#fff;display: block; font-family:\"宋体\"!important;}");
document.writeln("</style>");

if(window.location.host=="daye-pfb.skinjc.com" || window.location.host=="daye-xgl.skinjc.com"|| window.location.host=="daye-bdf.skinjc.com"|| window.location.host=="daye-mr.skinjc.com"){
	document.writeln("	<div class=\"db_nav\">");
	document.writeln("    	<div class=\"w980\">");
	document.writeln("        	<p class=\"fl\">&nbsp;&nbsp;");
	document.writeln("            	<a href=\"http://pfb.skinjc.com/\" target=\"_blank\">网站首页</a>&nbsp;  |  ");
	document.writeln("                <a style=\"background:url(http://pfb.skinjc.com/images/wyqzt_02.jpg) left no-repeat;\" href=\"http://wap.skinjc.com\" target=\"_blank\">&nbsp;&nbsp;手机版</a>&nbsp;  |  ");
	document.writeln("                <a href=\"http://pfb.skinjc.com/\" target=\"_blank\">科室疾病</a>&nbsp;  |  ");
	document.writeln("                <a href=\"http://pfb.skinjc.com/special/zjzt/\" target=\"_blank\">权威专家</a>&nbsp;  |  ");
	document.writeln("                <a href=\"http://pfb.skinjc.com/map.shtml\" target=\"_blank\">来院路线</a>");
	document.writeln("            </p>");
	document.writeln("            <div class=\"anniutop\">");
	document.writeln("		   	<form action=\"http://pfb.skinjc.com/plus/search.php\" name=\"formsearch\" target=\"_blank\">");
	document.writeln("		  	 <input  name=\"keyword\" type=\"text\" id=\"Keyword\" size=\"15\" class=\"so_02\" onblur=\'if(this.value==\"\"){this.value=\"查找皮肤疾病\";this.style.color=\"#BCBCBD\";}else{this.style.color=\"#000000\";}\' onfocus=\'if(this.value==\"查找皮肤疾病\")this.value=\"\";this.style.color=\"#000000\";\' value=\"查找皮肤疾病\" />");
	document.writeln("			<input type=\"submit\" value=\"\" style=\"background:none\" id=\"btnSearch\" class=\"so_03 search-submit\"> </form>");
	document.writeln("	 		</div>");
	document.writeln("            <p class=\"fl\">");
	document.writeln("            	<a href=\"/zt/xnzc\" target=\"_blank\">2015新年致辞</a>");
	document.writeln("            </p>");
	document.writeln("        </div>");
	document.writeln("    </div>");
	document.writeln("    <div class=\"w980\"><img src=\"http://daye-pfb.skinjc.com/images/wyqzt_04.jpg\" /></div>");
	document.writeln("    <div class=\"nav\">");
	document.writeln("  <div class=\"w995\">");
	document.writeln("    <ul>");
	document.writeln("      <li style=\"width:67px;\"><a href=\"/\" target=\"_blank\">首页</a></li>");
	document.writeln("      <li><a href=\"/special/yyjs\" target=\"_blank\">医院简介</a></li>");
	document.writeln("      <li style=\"width:87px;\"><a href=\"/special/yysb/\" target=\"_blank\">医院设备</a></li>");
	document.writeln("      <li><a href=\"/special/zjzt/index.html\" target=\"_blank\">权威专家</a></li>");
	document.writeln("      <li><a href=\"/special/jcgk/\" target=\"_blank\">公开课</a></li>");
	document.writeln("      <li><a style=\"background: url(\'http://pfb.skinjc.com/images/06.gif\') no-repeat scroll 100% 10% transparent;\"  href=\"/special/jcal/\" target=\"_blank\">典型病例</a></li>");
	document.writeln("      <li><a href=\"/pbl/\" target=\"_blank\">病例墙</a></li>");
	document.writeln("      <li><a href=\"/special/kbjl/\" target=\"_blank\">看病经历</a></li>");
	document.writeln("      <li><a style=\"background: url(\'http://pfb.skinjc.com/images/06.gif\') no-repeat scroll 100% 10% transparent;\"  href=\"/zt/mtbd/\" target=\"_blank\"> 社会公益</a></li>");
	document.writeln("      <li><a href=\"http://pfb.skinjc.com/guahao/\" target=\"_blank\">自助挂号</a></li>");
	document.writeln("      <li class=\"last\"><a href=\"/special/map/\" target=\"_blank\">来院路线</a></li>");
	document.writeln("    </ul>");
	document.writeln("  </div>");
	document.writeln("</div>");}else{
	document.writeln("	<div class=\"db_nav\">");
	document.writeln("    	<div class=\"w980\">");
	document.writeln("        	<p class=\"fl\">&nbsp;&nbsp;");
	document.writeln("            	<a href=\"http://pfb.skinjc.com/\" target=\"_blank\">网站首页</a>&nbsp;  |  ");
	document.writeln("                <a style=\"background:url(http://pfb.skinjc.com/images/wyqzt_02.jpg) left no-repeat;\" href=\"http://wap.skinjc.com\" target=\"_blank\">&nbsp;&nbsp;手机版</a>&nbsp;  |  ");
	document.writeln("                <a href=\"http://pfb.skinjc.com/\" target=\"_blank\">科室疾病</a>&nbsp;  |  ");
	document.writeln("                <a href=\"http://pfb.skinjc.com/special/zjzt/\" target=\"_blank\">权威专家</a>&nbsp;  |  ");
	document.writeln("                <a href=\"http://pfb.skinjc.com/map.shtml\" target=\"_blank\">来院路线</a>");
	document.writeln("            </p>");
	document.writeln("            <div class=\"anniutop\">");
	document.writeln("		   	<form action=\"http://pfb.skinjc.com/plus/search.php\" name=\"formsearch\" target=\"_blank\">");
	document.writeln("		  	 <input  name=\"keyword\" type=\"text\" id=\"Keyword\" size=\"15\" class=\"so_02\" onblur=\'if(this.value==\"\"){this.value=\"查找皮肤疾病\";this.style.color=\"#BCBCBD\";}else{this.style.color=\"#000000\";}\' onfocus=\'if(this.value==\"查找皮肤疾病\")this.value=\"\";this.style.color=\"#000000\";\' value=\"查找皮肤疾病\" />");
	document.writeln("			<input type=\"submit\" value=\"\" style=\"background:none\" id=\"btnSearch\" class=\"so_03 search-submit\"> </form>");
	document.writeln("	 		</div>");
	document.writeln("            <p class=\"fl\">");
	document.writeln("            	<a href=\"/zt/xnzc\" target=\"_blank\">2015新年致辞</a>");
	document.writeln("            </p>");
	document.writeln("        </div>");
	document.writeln("    </div>");
	document.writeln("    <div class=\"w980\"><img src=\"http://pfb.skinjc.com/images/wyqzt_04.jpg\" /></div>");
	document.writeln("    <div class=\"nav\">");
	document.writeln("  <div class=\"w995\">");
	document.writeln("    <ul>");
	document.writeln("      <li style=\"width:67px;\"><a href=\"/\" target=\"_blank\">首页</a></li>");
	document.writeln("      <li><a href=\"/special/yyjs\" target=\"_blank\">医院简介</a></li>");
	document.writeln("      <li style=\"width:87px;\"><a href=\"/special/yysb/\" target=\"_blank\">医院设备</a></li>");
	document.writeln("      <li><a href=\"/special/zjzt/index.html\" target=\"_blank\">权威专家</a></li>");
	document.writeln("      <li><a href=\"/special/jcgk/\" target=\"_blank\">公开课</a></li>");
	document.writeln("      <li><a style=\"background: url(\'http://pfb.skinjc.com/images/06.gif\') no-repeat scroll 100% 10% transparent;\"  href=\"/special/jcal/\" target=\"_blank\">典型病例</a></li>");
	document.writeln("      <li><a href=\"/pbl/\" target=\"_blank\">病例墙</a></li>");
	document.writeln("      <li><a href=\"/special/kbjl/\" target=\"_blank\">看病经历</a></li>");
	document.writeln("      <li><a style=\"background: url(\'http://pfb.skinjc.com/images/06.gif\') no-repeat scroll 100% 10% transparent;\"  href=\"/zt/mtbd/\" target=\"_blank\">社会公益</a></li>");
	document.writeln("      <li><a href=\"http://pfb.skinjc.com/guahao/\" target=\"_blank\">自助挂号</a></li>");
	document.writeln("      <li class=\"last\"><a href=\"/special/map/\" target=\"_blank\">来院路线</a></li>");
	document.writeln("    </ul>");
	document.writeln("  </div>");
	document.writeln("</div>");
}